// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: about.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getAboutBanner = `-- name: GetAboutBanner :one
SELECT id, media_type, image_url, video_url, updated_at FROM about_page_banner WHERE id = 1
`

func (q *Queries) GetAboutBanner(ctx context.Context) (AboutPageBanner, error) {
	row := q.db.QueryRowContext(ctx, getAboutBanner)
	var i AboutPageBanner
	err := row.Scan(
		&i.ID,
		&i.MediaType,
		&i.ImageUrl,
		&i.VideoUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const listAboutSegments = `-- name: ListAboutSegments :many
SELECT id, segment, title, body, updated_at FROM about_page_segments ORDER BY segment ASC
`

func (q *Queries) ListAboutSegments(ctx context.Context) ([]AboutPageSegment, error) {
	rows, err := q.db.QueryContext(ctx, listAboutSegments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AboutPageSegment{}
	for rows.Next() {
		var i AboutPageSegment
		if err := rows.Scan(
			&i.ID,
			&i.Segment,
			&i.Title,
			&i.Body,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAboutBanner = `-- name: UpdateAboutBanner :exec
UPDATE about_page_banner SET media_type = ?, image_url = ?, video_url = ? WHERE id = 1
`

type UpdateAboutBannerParams struct {
	MediaType AboutPageBannerMediaType `json:"media_type"`
	ImageUrl  sql.NullString           `json:"image_url"`
	VideoUrl  sql.NullString           `json:"video_url"`
}

func (q *Queries) UpdateAboutBanner(ctx context.Context, arg UpdateAboutBannerParams) error {
	_, err := q.db.ExecContext(ctx, updateAboutBanner, arg.MediaType, arg.ImageUrl, arg.VideoUrl)
	return err
}

const updateAboutSegment = `-- name: UpdateAboutSegment :exec
UPDATE about_page_segments SET title = ?, body = ? WHERE segment = ?
`

type UpdateAboutSegmentParams struct {
	Title   string                   `json:"title"`
	Body    string                   `json:"body"`
	Segment AboutPageSegmentsSegment `json:"segment"`
}

func (q *Queries) UpdateAboutSegment(ctx context.Context, arg UpdateAboutSegmentParams) error {
	_, err := q.db.ExecContext(ctx, updateAboutSegment, arg.Title, arg.Body, arg.Segment)
	return err
}
