// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ads.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAdBanner = `-- name: CreateAdBanner :execresult
INSERT INTO ad_banners (slot, title, alt_text, image_url, link_url, sort_order, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAdBannerParams struct {
	Slot      AdBannersSlot  `json:"slot"`
	Title     string         `json:"title"`
	AltText   string         `json:"alt_text"`
	ImageUrl  string         `json:"image_url"`
	LinkUrl   sql.NullString `json:"link_url"`
	SortOrder int32          `json:"sort_order"`
	IsActive  bool           `json:"is_active"`
}

func (q *Queries) CreateAdBanner(ctx context.Context, arg CreateAdBannerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAdBanner,
		arg.Slot,
		arg.Title,
		arg.AltText,
		arg.ImageUrl,
		arg.LinkUrl,
		arg.SortOrder,
		arg.IsActive,
	)
}

const createAdBannerPage = `-- name: CreateAdBannerPage :exec
INSERT INTO ad_banner_pages (banner_id, page) VALUES (?, ?)
`

type CreateAdBannerPageParams struct {
	BannerID uint64            `json:"banner_id"`
	Page     AdBannerPagesPage `json:"page"`
}

func (q *Queries) CreateAdBannerPage(ctx context.Context, arg CreateAdBannerPageParams) error {
	_, err := q.db.ExecContext(ctx, createAdBannerPage, arg.BannerID, arg.Page)
	return err
}

const deleteAdBanner = `-- name: DeleteAdBanner :exec
DELETE FROM ad_banners WHERE id = ?
`

func (q *Queries) DeleteAdBanner(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteAdBanner, id)
	return err
}

const deleteAdBannerPages = `-- name: DeleteAdBannerPages :exec
DELETE FROM ad_banner_pages WHERE banner_id = ?
`

func (q *Queries) DeleteAdBannerPages(ctx context.Context, bannerID uint64) error {
	_, err := q.db.ExecContext(ctx, deleteAdBannerPages, bannerID)
	return err
}

const getAdBanner = `-- name: GetAdBanner :one
SELECT id, slot, title, alt_text, image_url, link_url, sort_order, is_active, created_at, updated_at FROM ad_banners WHERE id = ?
`

func (q *Queries) GetAdBanner(ctx context.Context, id uint64) (AdBanner, error) {
	row := q.db.QueryRowContext(ctx, getAdBanner, id)
	var i AdBanner
	err := row.Scan(
		&i.ID,
		&i.Slot,
		&i.Title,
		&i.AltText,
		&i.ImageUrl,
		&i.LinkUrl,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdBannerPages = `-- name: GetAdBannerPages :many
SELECT page FROM ad_banner_pages WHERE banner_id = ?
`

func (q *Queries) GetAdBannerPages(ctx context.Context, bannerID uint64) ([]AdBannerPagesPage, error) {
	rows, err := q.db.QueryContext(ctx, getAdBannerPages, bannerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdBannerPagesPage{}
	for rows.Next() {
		var page AdBannerPagesPage
		if err := rows.Scan(&page); err != nil {
			return nil, err
		}
		items = append(items, page)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAdBannersForPage = `-- name: ListActiveAdBannersForPage :many
SELECT b.id, b.slot, b.title, b.alt_text, b.image_url, b.link_url, b.sort_order, b.is_active, b.created_at, b.updated_at FROM ad_banners b
WHERE b.is_active = 1
  AND (
    NOT EXISTS (SELECT 1 FROM ad_banner_pages p WHERE p.banner_id = b.id)
    OR EXISTS (SELECT 1 FROM ad_banner_pages p WHERE p.banner_id = b.id AND p.page = ?)
  )
ORDER BY b.slot ASC, b.sort_order ASC, b.id ASC
`

func (q *Queries) ListActiveAdBannersForPage(ctx context.Context, page AdBannerPagesPage) ([]AdBanner, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAdBannersForPage, page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdBanner{}
	for rows.Next() {
		var i AdBanner
		if err := rows.Scan(
			&i.ID,
			&i.Slot,
			&i.Title,
			&i.AltText,
			&i.ImageUrl,
			&i.LinkUrl,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdBannerPages = `-- name: ListAdBannerPages :many
SELECT banner_id, page FROM ad_banner_pages
`

func (q *Queries) ListAdBannerPages(ctx context.Context) ([]AdBannerPage, error) {
	rows, err := q.db.QueryContext(ctx, listAdBannerPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdBannerPage{}
	for rows.Next() {
		var i AdBannerPage
		if err := rows.Scan(&i.BannerID, &i.Page); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdBanners = `-- name: ListAdBanners :many
SELECT id, slot, title, alt_text, image_url, link_url, sort_order, is_active, created_at, updated_at FROM ad_banners ORDER BY slot ASC, sort_order ASC, id ASC
`

func (q *Queries) ListAdBanners(ctx context.Context) ([]AdBanner, error) {
	rows, err := q.db.QueryContext(ctx, listAdBanners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdBanner{}
	for rows.Next() {
		var i AdBanner
		if err := rows.Scan(
			&i.ID,
			&i.Slot,
			&i.Title,
			&i.AltText,
			&i.ImageUrl,
			&i.LinkUrl,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdSlots = `-- name: ListAdSlots :many
SELECT slot, label, display_mode, rotate_secs, show_placeholder, placeholder_text, is_active, updated_at FROM ad_slots ORDER BY slot ASC
`

func (q *Queries) ListAdSlots(ctx context.Context) ([]AdSlot, error) {
	rows, err := q.db.QueryContext(ctx, listAdSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdSlot{}
	for rows.Next() {
		var i AdSlot
		if err := rows.Scan(
			&i.Slot,
			&i.Label,
			&i.DisplayMode,
			&i.RotateSecs,
			&i.ShowPlaceholder,
			&i.PlaceholderText,
			&i.IsActive,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdBanner = `-- name: UpdateAdBanner :exec
UPDATE ad_banners
SET slot=?, title=?, alt_text=?, image_url=?, link_url=?, sort_order=?, is_active=?
WHERE id=?
`

type UpdateAdBannerParams struct {
	Slot      AdBannersSlot  `json:"slot"`
	Title     string         `json:"title"`
	AltText   string         `json:"alt_text"`
	ImageUrl  string         `json:"image_url"`
	LinkUrl   sql.NullString `json:"link_url"`
	SortOrder int32          `json:"sort_order"`
	IsActive  bool           `json:"is_active"`
	ID        uint64         `json:"id"`
}

func (q *Queries) UpdateAdBanner(ctx context.Context, arg UpdateAdBannerParams) error {
	_, err := q.db.ExecContext(ctx, updateAdBanner,
		arg.Slot,
		arg.Title,
		arg.AltText,
		arg.ImageUrl,
		arg.LinkUrl,
		arg.SortOrder,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updateAdSlot = `-- name: UpdateAdSlot :exec
UPDATE ad_slots
SET display_mode = ?, rotate_secs = ?, show_placeholder = ?, placeholder_text = ?, is_active = ?
WHERE slot = ?
`

type UpdateAdSlotParams struct {
	DisplayMode     AdSlotsDisplayMode `json:"display_mode"`
	RotateSecs      int32              `json:"rotate_secs"`
	ShowPlaceholder bool               `json:"show_placeholder"`
	PlaceholderText string             `json:"placeholder_text"`
	IsActive        bool               `json:"is_active"`
	Slot            AdSlotsSlot        `json:"slot"`
}

func (q *Queries) UpdateAdSlot(ctx context.Context, arg UpdateAdSlotParams) error {
	_, err := q.db.ExecContext(ctx, updateAdSlot,
		arg.DisplayMode,
		arg.RotateSecs,
		arg.ShowPlaceholder,
		arg.PlaceholderText,
		arg.IsActive,
		arg.Slot,
	)
	return err
}
