// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit_logs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
`

func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (user_id, user_email_snapshot, action, entity_type, entity_id, detail, ip_address)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAuditLogParams struct {
	UserID            sql.NullInt64 `json:"user_id"`
	UserEmailSnapshot string        `json:"user_email_snapshot"`
	Action            string        `json:"action"`
	EntityType        string        `json:"entity_type"`
	EntityID          sql.NullInt64 `json:"entity_id"`
	Detail            string        `json:"detail"`
	IpAddress         string        `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.UserID,
		arg.UserEmailSnapshot,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Detail,
		arg.IpAddress,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, user_email_snapshot, action, entity_type, entity_id, detail, ip_address, created_at FROM audit_logs ORDER BY created_at DESC, id DESC LIMIT ? OFFSET ?
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmailSnapshot,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Detail,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
