// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE name LIKE ? OR email LIKE ?
`

type CountUsersParams struct {
	Search string `json:"search"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers, arg.Search, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, user_id, expires_at)
VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	Token     string    `json:"token"`
	UserID    uint64    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (email, password_hash, name, role, is_active)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
	Role         UsersRole `json:"role"`
	IsActive     bool      `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
		arg.IsActive,
	)
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID uint64) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserID, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT
  s.token, s.user_id, s.expires_at,
  u.email, u.name, u.role
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token = ? AND s.expires_at > NOW() AND u.is_active = 1
`

type GetSessionRow struct {
	Token     string    `json:"token"`
	UserID    uint64    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Role      UsersRole `json:"role"`
}

func (q *Queries) GetSession(ctx context.Context, token string) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var i GetSessionRow
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.Email,
		&i.Name,
		&i.Role,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, created_at, role, is_active FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, created_at, role, is_active FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id uint64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, name, created_at, role, is_active FROM users
WHERE name LIKE ? OR email LIKE ?
ORDER BY
  CASE WHEN ? = 'name' AND ? = 'asc' THEN name END ASC,
  CASE WHEN ? = 'name' AND ? = 'desc' THEN name END DESC,
  CASE WHEN ? = 'email' AND ? = 'asc' THEN email END ASC,
  CASE WHEN ? = 'email' AND ? = 'desc' THEN email END DESC,
  name ASC, id ASC
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Search string      `json:"search"`
	Sort   interface{} `json:"sort"`
	Dir    interface{} `json:"dir"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers,
		arg.Search,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.CreatedAt,
			&i.Role,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET name = ?, email = ?, role = ?, is_active = ? WHERE id = ?
`

type UpdateUserParams struct {
	Name     string    `json:"name"`
	Email    string    `json:"email"`
	Role     UsersRole `json:"role"`
	IsActive bool      `json:"is_active"`
	ID       uint64    `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = ? WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           uint64 `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
