// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: broadcasters.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countBroadcasters = `-- name: CountBroadcasters :one
SELECT COUNT(*) FROM broadcasters
WHERE name LIKE ? OR slug LIKE ?
`

type CountBroadcastersParams struct {
	Search string `json:"search"`
}

func (q *Queries) CountBroadcasters(ctx context.Context, arg CountBroadcastersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBroadcasters, arg.Search, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBroadcaster = `-- name: CreateBroadcaster :execresult
INSERT INTO broadcasters (name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, facebook, sort_order, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateBroadcasterParams struct {
	Name       string         `json:"name"`
	Slug       string         `json:"slug"`
	Role       sql.NullString `json:"role"`
	PhotoUrl   sql.NullString `json:"photo_url"`
	Bio        sql.NullString `json:"bio"`
	BirthPlace sql.NullString `json:"birth_place"`
	BirthDate  sql.NullString `json:"birth_date"`
	Instagram  sql.NullString `json:"instagram"`
	Twitter    sql.NullString `json:"twitter"`
	Facebook   sql.NullString `json:"facebook"`
	SortOrder  int32          `json:"sort_order"`
	IsActive   bool           `json:"is_active"`
}

func (q *Queries) CreateBroadcaster(ctx context.Context, arg CreateBroadcasterParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBroadcaster,
		arg.Name,
		arg.Slug,
		arg.Role,
		arg.PhotoUrl,
		arg.Bio,
		arg.BirthPlace,
		arg.BirthDate,
		arg.Instagram,
		arg.Twitter,
		arg.Facebook,
		arg.SortOrder,
		arg.IsActive,
	)
}

const deleteBroadcaster = `-- name: DeleteBroadcaster :exec
DELETE FROM broadcasters WHERE id = ?
`

func (q *Queries) DeleteBroadcaster(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteBroadcaster, id)
	return err
}

const getActiveBroadcasterBySlug = `-- name: GetActiveBroadcasterBySlug :one
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, facebook, sort_order, is_active, created_at, updated_at FROM broadcasters WHERE slug = ? AND is_active = 1
`

func (q *Queries) GetActiveBroadcasterBySlug(ctx context.Context, slug string) (Broadcaster, error) {
	row := q.db.QueryRowContext(ctx, getActiveBroadcasterBySlug, slug)
	var i Broadcaster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Role,
		&i.PhotoUrl,
		&i.Bio,
		&i.BirthPlace,
		&i.BirthDate,
		&i.Instagram,
		&i.Twitter,
		&i.Facebook,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBroadcaster = `-- name: GetBroadcaster :one
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, facebook, sort_order, is_active, created_at, updated_at FROM broadcasters WHERE id = ?
`

func (q *Queries) GetBroadcaster(ctx context.Context, id uint64) (Broadcaster, error) {
	row := q.db.QueryRowContext(ctx, getBroadcaster, id)
	var i Broadcaster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Role,
		&i.PhotoUrl,
		&i.Bio,
		&i.BirthPlace,
		&i.BirthDate,
		&i.Instagram,
		&i.Twitter,
		&i.Facebook,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveBroadcasters = `-- name: ListActiveBroadcasters :many
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, facebook, sort_order, is_active, created_at, updated_at FROM broadcasters WHERE is_active = 1 ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListActiveBroadcasters(ctx context.Context) ([]Broadcaster, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBroadcasters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Broadcaster{}
	for rows.Next() {
		var i Broadcaster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.PhotoUrl,
			&i.Bio,
			&i.BirthPlace,
			&i.BirthDate,
			&i.Instagram,
			&i.Twitter,
			&i.Facebook,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBroadcasters = `-- name: ListAllBroadcasters :many
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, facebook, sort_order, is_active, created_at, updated_at FROM broadcasters ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListAllBroadcasters(ctx context.Context) ([]Broadcaster, error) {
	rows, err := q.db.QueryContext(ctx, listAllBroadcasters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Broadcaster{}
	for rows.Next() {
		var i Broadcaster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.PhotoUrl,
			&i.Bio,
			&i.BirthPlace,
			&i.BirthDate,
			&i.Instagram,
			&i.Twitter,
			&i.Facebook,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBroadcasterProgramLinks = `-- name: ListBroadcasterProgramLinks :many

SELECT DISTINCT COALESCE(ps.broadcaster_id, p.broadcaster_id) AS broadcaster_id, ps.program_id
FROM program_schedules ps
JOIN programs p ON p.id = ps.program_id
WHERE COALESCE(ps.broadcaster_id, p.broadcaster_id) IS NOT NULL AND p.is_active = 1
`

type ListBroadcasterProgramLinksRow struct {
	BroadcasterID sql.NullInt64 `json:"broadcaster_id"`
	ProgramID     uint64        `json:"program_id"`
}

// ListBroadcasterProgramLinks stays driven by program_schedules: it feeds the "on air
// now" badge, which needs an actual time slot to measure against.
func (q *Queries) ListBroadcasterProgramLinks(ctx context.Context) ([]ListBroadcasterProgramLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listBroadcasterProgramLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBroadcasterProgramLinksRow{}
	for rows.Next() {
		var i ListBroadcasterProgramLinksRow
		if err := rows.Scan(&i.BroadcasterID, &i.ProgramID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBroadcasters = `-- name: ListBroadcasters :many
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, facebook, sort_order, is_active, created_at, updated_at FROM broadcasters
WHERE name LIKE ? OR slug LIKE ?
ORDER BY
  CASE WHEN ? = 'name' AND ? = 'asc' THEN name END ASC,
  CASE WHEN ? = 'name' AND ? = 'desc' THEN name END DESC,
  CASE WHEN ? = 'slug' AND ? = 'asc' THEN slug END ASC,
  CASE WHEN ? = 'slug' AND ? = 'desc' THEN slug END DESC,
  CASE WHEN ? = 'role' AND ? = 'asc' THEN role END ASC,
  CASE WHEN ? = 'role' AND ? = 'desc' THEN role END DESC,
  CASE WHEN ? = 'sort_order' AND ? = 'asc' THEN sort_order END ASC,
  CASE WHEN ? = 'sort_order' AND ? = 'desc' THEN sort_order END DESC,
  sort_order ASC, name ASC, id ASC
LIMIT ? OFFSET ?
`

type ListBroadcastersParams struct {
	Search string      `json:"search"`
	Sort   interface{} `json:"sort"`
	Dir    interface{} `json:"dir"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListBroadcasters(ctx context.Context, arg ListBroadcastersParams) ([]Broadcaster, error) {
	rows, err := q.db.QueryContext(ctx, listBroadcasters,
		arg.Search,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Broadcaster{}
	for rows.Next() {
		var i Broadcaster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.PhotoUrl,
			&i.Bio,
			&i.BirthPlace,
			&i.BirthDate,
			&i.Instagram,
			&i.Twitter,
			&i.Facebook,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBroadcastersForProgram = `-- name: ListBroadcastersForProgram :many
SELECT DISTINCT b.id, b.name, b.slug, b.role, b.photo_url, b.bio, b.birth_place, b.birth_date, b.instagram, b.twitter, b.facebook, b.sort_order, b.is_active, b.created_at, b.updated_at FROM programs p
LEFT JOIN program_schedules ps ON ps.program_id = p.id
JOIN broadcasters b ON b.id = COALESCE(ps.broadcaster_id, p.broadcaster_id)
WHERE p.id = ? AND b.is_active = 1
ORDER BY b.sort_order ASC, b.name ASC
`

func (q *Queries) ListBroadcastersForProgram(ctx context.Context, id uint64) ([]Broadcaster, error) {
	rows, err := q.db.QueryContext(ctx, listBroadcastersForProgram, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Broadcaster{}
	for rows.Next() {
		var i Broadcaster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.PhotoUrl,
			&i.Bio,
			&i.BirthPlace,
			&i.BirthDate,
			&i.Instagram,
			&i.Twitter,
			&i.Facebook,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsForBroadcaster = `-- name: ListProgramsForBroadcaster :many

SELECT DISTINCT p.id, p.title, p.slug, p.description, p.image_url, p.sort_order, p.is_active, p.created_at, p.updated_at, p.broadcaster_id FROM programs p
LEFT JOIN program_schedules ps ON ps.program_id = p.id
WHERE COALESCE(ps.broadcaster_id, p.broadcaster_id) = ? AND p.is_active = 1
ORDER BY p.sort_order ASC, p.title ASC
`

// The program<->broadcaster relation is derived: a broadcaster presents a program if
// they are assigned to one of its schedule slots, or if they are the program's default
// broadcaster. The LEFT JOIN (rather than driving from program_schedules) is what lets a
// program that has a default but no slots yet still resolve.
func (q *Queries) ListProgramsForBroadcaster(ctx context.Context, broadcasterID sql.NullInt64) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsForBroadcaster, broadcasterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BroadcasterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBroadcaster = `-- name: UpdateBroadcaster :exec
UPDATE broadcasters
SET name=?, slug=?, role=?, photo_url=?, bio=?, birth_place=?, birth_date=?, instagram=?, twitter=?, facebook=?, sort_order=?, is_active=?
WHERE id=?
`

type UpdateBroadcasterParams struct {
	Name       string         `json:"name"`
	Slug       string         `json:"slug"`
	Role       sql.NullString `json:"role"`
	PhotoUrl   sql.NullString `json:"photo_url"`
	Bio        sql.NullString `json:"bio"`
	BirthPlace sql.NullString `json:"birth_place"`
	BirthDate  sql.NullString `json:"birth_date"`
	Instagram  sql.NullString `json:"instagram"`
	Twitter    sql.NullString `json:"twitter"`
	Facebook   sql.NullString `json:"facebook"`
	SortOrder  int32          `json:"sort_order"`
	IsActive   bool           `json:"is_active"`
	ID         uint64         `json:"id"`
}

func (q *Queries) UpdateBroadcaster(ctx context.Context, arg UpdateBroadcasterParams) error {
	_, err := q.db.ExecContext(ctx, updateBroadcaster,
		arg.Name,
		arg.Slug,
		arg.Role,
		arg.PhotoUrl,
		arg.Bio,
		arg.BirthPlace,
		arg.BirthDate,
		arg.Instagram,
		arg.Twitter,
		arg.Facebook,
		arg.SortOrder,
		arg.IsActive,
		arg.ID,
	)
	return err
}
