// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: broadcasters.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countBroadcasters = `-- name: CountBroadcasters :one
SELECT COUNT(*) FROM broadcasters
WHERE name LIKE ? OR slug LIKE ?
`

type CountBroadcastersParams struct {
	Search string `json:"search"`
}

func (q *Queries) CountBroadcasters(ctx context.Context, arg CountBroadcastersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBroadcasters, arg.Search, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBroadcaster = `-- name: CreateBroadcaster :execresult
INSERT INTO broadcasters (name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, tiktok, sort_order, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateBroadcasterParams struct {
	Name       string         `json:"name"`
	Slug       string         `json:"slug"`
	Role       sql.NullString `json:"role"`
	PhotoUrl   sql.NullString `json:"photo_url"`
	Bio        sql.NullString `json:"bio"`
	BirthPlace sql.NullString `json:"birth_place"`
	BirthDate  sql.NullString `json:"birth_date"`
	Instagram  sql.NullString `json:"instagram"`
	Twitter    sql.NullString `json:"twitter"`
	Tiktok     sql.NullString `json:"tiktok"`
	SortOrder  int32          `json:"sort_order"`
	IsActive   bool           `json:"is_active"`
}

func (q *Queries) CreateBroadcaster(ctx context.Context, arg CreateBroadcasterParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBroadcaster,
		arg.Name,
		arg.Slug,
		arg.Role,
		arg.PhotoUrl,
		arg.Bio,
		arg.BirthPlace,
		arg.BirthDate,
		arg.Instagram,
		arg.Twitter,
		arg.Tiktok,
		arg.SortOrder,
		arg.IsActive,
	)
}

const deleteBroadcaster = `-- name: DeleteBroadcaster :exec
DELETE FROM broadcasters WHERE id = ?
`

func (q *Queries) DeleteBroadcaster(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteBroadcaster, id)
	return err
}

const getActiveBroadcasterBySlug = `-- name: GetActiveBroadcasterBySlug :one
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, sort_order, is_active, created_at, updated_at, tiktok FROM broadcasters WHERE slug = ? AND is_active = 1
`

func (q *Queries) GetActiveBroadcasterBySlug(ctx context.Context, slug string) (Broadcaster, error) {
	row := q.db.QueryRowContext(ctx, getActiveBroadcasterBySlug, slug)
	var i Broadcaster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Role,
		&i.PhotoUrl,
		&i.Bio,
		&i.BirthPlace,
		&i.BirthDate,
		&i.Instagram,
		&i.Twitter,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tiktok,
	)
	return i, err
}

const getBroadcaster = `-- name: GetBroadcaster :one
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, sort_order, is_active, created_at, updated_at, tiktok FROM broadcasters WHERE id = ?
`

func (q *Queries) GetBroadcaster(ctx context.Context, id uint64) (Broadcaster, error) {
	row := q.db.QueryRowContext(ctx, getBroadcaster, id)
	var i Broadcaster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Role,
		&i.PhotoUrl,
		&i.Bio,
		&i.BirthPlace,
		&i.BirthDate,
		&i.Instagram,
		&i.Twitter,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tiktok,
	)
	return i, err
}

const listActiveBroadcasters = `-- name: ListActiveBroadcasters :many
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, sort_order, is_active, created_at, updated_at, tiktok FROM broadcasters WHERE is_active = 1 ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListActiveBroadcasters(ctx context.Context) ([]Broadcaster, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBroadcasters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Broadcaster{}
	for rows.Next() {
		var i Broadcaster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.PhotoUrl,
			&i.Bio,
			&i.BirthPlace,
			&i.BirthDate,
			&i.Instagram,
			&i.Twitter,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tiktok,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBroadcasters = `-- name: ListAllBroadcasters :many
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, sort_order, is_active, created_at, updated_at, tiktok FROM broadcasters ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListAllBroadcasters(ctx context.Context) ([]Broadcaster, error) {
	rows, err := q.db.QueryContext(ctx, listAllBroadcasters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Broadcaster{}
	for rows.Next() {
		var i Broadcaster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.PhotoUrl,
			&i.Bio,
			&i.BirthPlace,
			&i.BirthDate,
			&i.Instagram,
			&i.Twitter,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tiktok,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBroadcasterProgramLinks = `-- name: ListBroadcasterProgramLinks :many

SELECT DISTINCT sb.broadcaster_id, s.program_id
FROM schedule_broadcasters sb
JOIN program_schedules s ON s.id = sb.schedule_id
JOIN programs p ON p.id = s.program_id
WHERE p.is_active = 1
UNION
SELECT DISTINCT pb.broadcaster_id, s.program_id
FROM program_schedules s
JOIN programs p ON p.id = s.program_id
JOIN program_broadcasters pb ON pb.program_id = s.program_id
WHERE p.is_active = 1
  AND NOT EXISTS (SELECT 1 FROM schedule_broadcasters sb WHERE sb.schedule_id = s.id)
`

type ListBroadcasterProgramLinksRow struct {
	BroadcasterID uint64 `json:"broadcaster_id"`
	ProgramID     uint64 `json:"program_id"`
}

// ListBroadcasterProgramLinks, by contrast, must stay exactly effective-per-slot: it
// feeds the "on air now" badge, which needs a real time slot to measure against. Hence
// the UNION - slot assignments, plus the program's defaults for the slots that have no
// assignment of their own.
func (q *Queries) ListBroadcasterProgramLinks(ctx context.Context) ([]ListBroadcasterProgramLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listBroadcasterProgramLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBroadcasterProgramLinksRow{}
	for rows.Next() {
		var i ListBroadcasterProgramLinksRow
		if err := rows.Scan(&i.BroadcasterID, &i.ProgramID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBroadcasters = `-- name: ListBroadcasters :many
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, sort_order, is_active, created_at, updated_at, tiktok FROM broadcasters
WHERE name LIKE ? OR slug LIKE ?
ORDER BY
  CASE WHEN ? = 'name' AND ? = 'asc' THEN name END ASC,
  CASE WHEN ? = 'name' AND ? = 'desc' THEN name END DESC,
  CASE WHEN ? = 'slug' AND ? = 'asc' THEN slug END ASC,
  CASE WHEN ? = 'slug' AND ? = 'desc' THEN slug END DESC,
  CASE WHEN ? = 'role' AND ? = 'asc' THEN role END ASC,
  CASE WHEN ? = 'role' AND ? = 'desc' THEN role END DESC,
  CASE WHEN ? = 'sort_order' AND ? = 'asc' THEN sort_order END ASC,
  CASE WHEN ? = 'sort_order' AND ? = 'desc' THEN sort_order END DESC,
  sort_order ASC, name ASC, id ASC
LIMIT ? OFFSET ?
`

type ListBroadcastersParams struct {
	Search string      `json:"search"`
	Sort   interface{} `json:"sort"`
	Dir    interface{} `json:"dir"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListBroadcasters(ctx context.Context, arg ListBroadcastersParams) ([]Broadcaster, error) {
	rows, err := q.db.QueryContext(ctx, listBroadcasters,
		arg.Search,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Broadcaster{}
	for rows.Next() {
		var i Broadcaster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.PhotoUrl,
			&i.Bio,
			&i.BirthPlace,
			&i.BirthDate,
			&i.Instagram,
			&i.Twitter,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tiktok,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBroadcastersForProgram = `-- name: ListBroadcastersForProgram :many
SELECT b.id, b.name, b.slug, b.role, b.photo_url, b.bio, b.birth_place, b.birth_date, b.instagram, b.twitter, b.sort_order, b.is_active, b.created_at, b.updated_at, b.tiktok FROM broadcasters b
WHERE b.is_active = 1 AND (
  EXISTS (SELECT 1 FROM program_broadcasters pb
           WHERE pb.broadcaster_id = b.id AND pb.program_id = ?)
  OR EXISTS (SELECT 1 FROM schedule_broadcasters sb
               JOIN program_schedules s ON s.id = sb.schedule_id
              WHERE sb.broadcaster_id = b.id AND s.program_id = ?)
)
ORDER BY b.sort_order ASC, b.name ASC
`

type ListBroadcastersForProgramParams struct {
	ProgramID uint64 `json:"program_id"`
}

func (q *Queries) ListBroadcastersForProgram(ctx context.Context, arg ListBroadcastersForProgramParams) ([]Broadcaster, error) {
	rows, err := q.db.QueryContext(ctx, listBroadcastersForProgram, arg.ProgramID, arg.ProgramID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Broadcaster{}
	for rows.Next() {
		var i Broadcaster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.PhotoUrl,
			&i.Bio,
			&i.BirthPlace,
			&i.BirthDate,
			&i.Instagram,
			&i.Twitter,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tiktok,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEffectiveBroadcastersForSchedule = `-- name: ListEffectiveBroadcastersForSchedule :many
SELECT b.id, b.name, b.slug, b.role, b.photo_url, b.bio, b.birth_place, b.birth_date, b.instagram, b.twitter, b.sort_order, b.is_active, b.created_at, b.updated_at, b.tiktok FROM broadcasters b
WHERE b.is_active = 1 AND b.id IN (
  SELECT sb.broadcaster_id FROM schedule_broadcasters sb WHERE sb.schedule_id = ?
  UNION
  SELECT pb.broadcaster_id FROM program_broadcasters pb
   WHERE pb.program_id = ?
     AND NOT EXISTS (SELECT 1 FROM schedule_broadcasters x WHERE x.schedule_id = ?)
)
ORDER BY b.sort_order ASC, b.name ASC
`

type ListEffectiveBroadcastersForScheduleParams struct {
	ScheduleID uint64 `json:"schedule_id"`
	ProgramID  uint64 `json:"program_id"`
}

// ListEffectiveBroadcastersForSchedule returns the effective broadcaster set for ONE
// schedule slot: its own schedule_broadcasters if it has any, otherwise the program's
// program_broadcasters defaults. Same UNION + NOT EXISTS rule as the broadcaster_name
// GROUP_CONCAT in programs.sql, but selecting the rows (photo/slug) instead of joining
// names - /live's on-air announcer avatars need the full broadcaster records. schedule_id
// is bound twice (membership test + the defaults' NOT EXISTS guard).
func (q *Queries) ListEffectiveBroadcastersForSchedule(ctx context.Context, arg ListEffectiveBroadcastersForScheduleParams) ([]Broadcaster, error) {
	rows, err := q.db.QueryContext(ctx, listEffectiveBroadcastersForSchedule, arg.ScheduleID, arg.ProgramID, arg.ScheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Broadcaster{}
	for rows.Next() {
		var i Broadcaster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.PhotoUrl,
			&i.Bio,
			&i.BirthPlace,
			&i.BirthDate,
			&i.Instagram,
			&i.Twitter,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tiktok,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsForBroadcaster = `-- name: ListProgramsForBroadcaster :many

SELECT p.id, p.title, p.slug, p.description, p.image_url, p.sort_order, p.is_active, p.created_at, p.updated_at FROM programs p
WHERE p.is_active = 1 AND (
  EXISTS (SELECT 1 FROM program_broadcasters pb
           WHERE pb.program_id = p.id AND pb.broadcaster_id = ?)
  OR EXISTS (SELECT 1 FROM schedule_broadcasters sb
               JOIN program_schedules s ON s.id = sb.schedule_id
              WHERE s.program_id = p.id AND sb.broadcaster_id = ?)
)
ORDER BY p.sort_order ASC, p.title ASC
`

type ListProgramsForBroadcasterParams struct {
	BroadcasterID uint64 `json:"broadcaster_id"`
}

// The two queries below answer "who presents this program" / "what does this broadcaster
// present" for chip lists, and deliberately take the loose reading: a program's default
// broadcaster counts even if every slot happens to override them. They are display
// lists, and someone assigned to the program is one of its broadcasters regardless of
// which slots they actually cover.
func (q *Queries) ListProgramsForBroadcaster(ctx context.Context, arg ListProgramsForBroadcasterParams) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsForBroadcaster, arg.BroadcasterID, arg.BroadcasterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBroadcaster = `-- name: UpdateBroadcaster :exec
UPDATE broadcasters
SET name=?, slug=?, role=?, photo_url=?, bio=?, birth_place=?, birth_date=?, instagram=?, twitter=?, tiktok=?, sort_order=?, is_active=?
WHERE id=?
`

type UpdateBroadcasterParams struct {
	Name       string         `json:"name"`
	Slug       string         `json:"slug"`
	Role       sql.NullString `json:"role"`
	PhotoUrl   sql.NullString `json:"photo_url"`
	Bio        sql.NullString `json:"bio"`
	BirthPlace sql.NullString `json:"birth_place"`
	BirthDate  sql.NullString `json:"birth_date"`
	Instagram  sql.NullString `json:"instagram"`
	Twitter    sql.NullString `json:"twitter"`
	Tiktok     sql.NullString `json:"tiktok"`
	SortOrder  int32          `json:"sort_order"`
	IsActive   bool           `json:"is_active"`
	ID         uint64         `json:"id"`
}

func (q *Queries) UpdateBroadcaster(ctx context.Context, arg UpdateBroadcasterParams) error {
	_, err := q.db.ExecContext(ctx, updateBroadcaster,
		arg.Name,
		arg.Slug,
		arg.Role,
		arg.PhotoUrl,
		arg.Bio,
		arg.BirthPlace,
		arg.BirthDate,
		arg.Instagram,
		arg.Twitter,
		arg.Tiktok,
		arg.SortOrder,
		arg.IsActive,
		arg.ID,
	)
	return err
}
