// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: broadcasters.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countBroadcasters = `-- name: CountBroadcasters :one
SELECT COUNT(*) FROM broadcasters
WHERE name LIKE ? OR slug LIKE ?
`

type CountBroadcastersParams struct {
	Search string `json:"search"`
}

func (q *Queries) CountBroadcasters(ctx context.Context, arg CountBroadcastersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBroadcasters, arg.Search, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBroadcaster = `-- name: CreateBroadcaster :execresult
INSERT INTO broadcasters (name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, facebook, sort_order, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateBroadcasterParams struct {
	Name       string         `json:"name"`
	Slug       string         `json:"slug"`
	Role       sql.NullString `json:"role"`
	PhotoUrl   sql.NullString `json:"photo_url"`
	Bio        sql.NullString `json:"bio"`
	BirthPlace sql.NullString `json:"birth_place"`
	BirthDate  sql.NullString `json:"birth_date"`
	Instagram  sql.NullString `json:"instagram"`
	Twitter    sql.NullString `json:"twitter"`
	Facebook   sql.NullString `json:"facebook"`
	SortOrder  int32          `json:"sort_order"`
	IsActive   bool           `json:"is_active"`
}

func (q *Queries) CreateBroadcaster(ctx context.Context, arg CreateBroadcasterParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBroadcaster,
		arg.Name,
		arg.Slug,
		arg.Role,
		arg.PhotoUrl,
		arg.Bio,
		arg.BirthPlace,
		arg.BirthDate,
		arg.Instagram,
		arg.Twitter,
		arg.Facebook,
		arg.SortOrder,
		arg.IsActive,
	)
}

const deleteBroadcaster = `-- name: DeleteBroadcaster :exec
DELETE FROM broadcasters WHERE id = ?
`

func (q *Queries) DeleteBroadcaster(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteBroadcaster, id)
	return err
}

const getActiveBroadcasterBySlug = `-- name: GetActiveBroadcasterBySlug :one
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, facebook, sort_order, is_active, created_at, updated_at FROM broadcasters WHERE slug = ? AND is_active = 1
`

func (q *Queries) GetActiveBroadcasterBySlug(ctx context.Context, slug string) (Broadcaster, error) {
	row := q.db.QueryRowContext(ctx, getActiveBroadcasterBySlug, slug)
	var i Broadcaster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Role,
		&i.PhotoUrl,
		&i.Bio,
		&i.BirthPlace,
		&i.BirthDate,
		&i.Instagram,
		&i.Twitter,
		&i.Facebook,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBroadcaster = `-- name: GetBroadcaster :one
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, facebook, sort_order, is_active, created_at, updated_at FROM broadcasters WHERE id = ?
`

func (q *Queries) GetBroadcaster(ctx context.Context, id uint64) (Broadcaster, error) {
	row := q.db.QueryRowContext(ctx, getBroadcaster, id)
	var i Broadcaster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Role,
		&i.PhotoUrl,
		&i.Bio,
		&i.BirthPlace,
		&i.BirthDate,
		&i.Instagram,
		&i.Twitter,
		&i.Facebook,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveBroadcasters = `-- name: ListActiveBroadcasters :many
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, facebook, sort_order, is_active, created_at, updated_at FROM broadcasters WHERE is_active = 1 ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListActiveBroadcasters(ctx context.Context) ([]Broadcaster, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBroadcasters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Broadcaster{}
	for rows.Next() {
		var i Broadcaster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.PhotoUrl,
			&i.Bio,
			&i.BirthPlace,
			&i.BirthDate,
			&i.Instagram,
			&i.Twitter,
			&i.Facebook,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBroadcasters = `-- name: ListBroadcasters :many
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, facebook, sort_order, is_active, created_at, updated_at FROM broadcasters
WHERE name LIKE ? OR slug LIKE ?
ORDER BY
  CASE WHEN ? = 'name' AND ? = 'asc' THEN name END ASC,
  CASE WHEN ? = 'name' AND ? = 'desc' THEN name END DESC,
  CASE WHEN ? = 'slug' AND ? = 'asc' THEN slug END ASC,
  CASE WHEN ? = 'slug' AND ? = 'desc' THEN slug END DESC,
  CASE WHEN ? = 'role' AND ? = 'asc' THEN role END ASC,
  CASE WHEN ? = 'role' AND ? = 'desc' THEN role END DESC,
  CASE WHEN ? = 'sort_order' AND ? = 'asc' THEN sort_order END ASC,
  CASE WHEN ? = 'sort_order' AND ? = 'desc' THEN sort_order END DESC,
  sort_order ASC, name ASC, id ASC
LIMIT ? OFFSET ?
`

type ListBroadcastersParams struct {
	Search string      `json:"search"`
	Sort   interface{} `json:"sort"`
	Dir    interface{} `json:"dir"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListBroadcasters(ctx context.Context, arg ListBroadcastersParams) ([]Broadcaster, error) {
	rows, err := q.db.QueryContext(ctx, listBroadcasters,
		arg.Search,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Broadcaster{}
	for rows.Next() {
		var i Broadcaster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.PhotoUrl,
			&i.Bio,
			&i.BirthPlace,
			&i.BirthDate,
			&i.Instagram,
			&i.Twitter,
			&i.Facebook,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBroadcaster = `-- name: UpdateBroadcaster :exec
UPDATE broadcasters
SET name=?, slug=?, role=?, photo_url=?, bio=?, birth_place=?, birth_date=?, instagram=?, twitter=?, facebook=?, sort_order=?, is_active=?
WHERE id=?
`

type UpdateBroadcasterParams struct {
	Name       string         `json:"name"`
	Slug       string         `json:"slug"`
	Role       sql.NullString `json:"role"`
	PhotoUrl   sql.NullString `json:"photo_url"`
	Bio        sql.NullString `json:"bio"`
	BirthPlace sql.NullString `json:"birth_place"`
	BirthDate  sql.NullString `json:"birth_date"`
	Instagram  sql.NullString `json:"instagram"`
	Twitter    sql.NullString `json:"twitter"`
	Facebook   sql.NullString `json:"facebook"`
	SortOrder  int32          `json:"sort_order"`
	IsActive   bool           `json:"is_active"`
	ID         uint64         `json:"id"`
}

func (q *Queries) UpdateBroadcaster(ctx context.Context, arg UpdateBroadcasterParams) error {
	_, err := q.db.ExecContext(ctx, updateBroadcaster,
		arg.Name,
		arg.Slug,
		arg.Role,
		arg.PhotoUrl,
		arg.Bio,
		arg.BirthPlace,
		arg.BirthDate,
		arg.Instagram,
		arg.Twitter,
		arg.Facebook,
		arg.SortOrder,
		arg.IsActive,
		arg.ID,
	)
	return err
}
