// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: classiers.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countClassiers = `-- name: CountClassiers :one
SELECT COUNT(*) FROM classiers
WHERE name LIKE ? OR slug LIKE ?
`

type CountClassiersParams struct {
	Search string `json:"search"`
}

func (q *Queries) CountClassiers(ctx context.Context, arg CountClassiersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClassiers, arg.Search, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClassier = `-- name: CreateClassier :execresult
INSERT INTO classiers (name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, facebook, sort_order, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateClassierParams struct {
	Name       string         `json:"name"`
	Slug       string         `json:"slug"`
	Role       sql.NullString `json:"role"`
	PhotoUrl   sql.NullString `json:"photo_url"`
	Bio        sql.NullString `json:"bio"`
	BirthPlace sql.NullString `json:"birth_place"`
	BirthDate  sql.NullString `json:"birth_date"`
	Instagram  sql.NullString `json:"instagram"`
	Twitter    sql.NullString `json:"twitter"`
	Facebook   sql.NullString `json:"facebook"`
	SortOrder  int32          `json:"sort_order"`
	IsActive   bool           `json:"is_active"`
}

func (q *Queries) CreateClassier(ctx context.Context, arg CreateClassierParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createClassier,
		arg.Name,
		arg.Slug,
		arg.Role,
		arg.PhotoUrl,
		arg.Bio,
		arg.BirthPlace,
		arg.BirthDate,
		arg.Instagram,
		arg.Twitter,
		arg.Facebook,
		arg.SortOrder,
		arg.IsActive,
	)
}

const deleteClassier = `-- name: DeleteClassier :exec
DELETE FROM classiers WHERE id = ?
`

func (q *Queries) DeleteClassier(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteClassier, id)
	return err
}

const getActiveClassierBySlug = `-- name: GetActiveClassierBySlug :one
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, facebook, sort_order, is_active, created_at, updated_at FROM classiers WHERE slug = ? AND is_active = 1
`

func (q *Queries) GetActiveClassierBySlug(ctx context.Context, slug string) (Classier, error) {
	row := q.db.QueryRowContext(ctx, getActiveClassierBySlug, slug)
	var i Classier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Role,
		&i.PhotoUrl,
		&i.Bio,
		&i.BirthPlace,
		&i.BirthDate,
		&i.Instagram,
		&i.Twitter,
		&i.Facebook,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassier = `-- name: GetClassier :one
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, facebook, sort_order, is_active, created_at, updated_at FROM classiers WHERE id = ?
`

func (q *Queries) GetClassier(ctx context.Context, id uint64) (Classier, error) {
	row := q.db.QueryRowContext(ctx, getClassier, id)
	var i Classier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Role,
		&i.PhotoUrl,
		&i.Bio,
		&i.BirthPlace,
		&i.BirthDate,
		&i.Instagram,
		&i.Twitter,
		&i.Facebook,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveClassiers = `-- name: ListActiveClassiers :many
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, facebook, sort_order, is_active, created_at, updated_at FROM classiers WHERE is_active = 1 ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListActiveClassiers(ctx context.Context) ([]Classier, error) {
	rows, err := q.db.QueryContext(ctx, listActiveClassiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Classier{}
	for rows.Next() {
		var i Classier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.PhotoUrl,
			&i.Bio,
			&i.BirthPlace,
			&i.BirthDate,
			&i.Instagram,
			&i.Twitter,
			&i.Facebook,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassiers = `-- name: ListClassiers :many
SELECT id, name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, facebook, sort_order, is_active, created_at, updated_at FROM classiers
WHERE name LIKE ? OR slug LIKE ?
ORDER BY
  CASE WHEN ? = 'name' AND ? = 'asc' THEN name END ASC,
  CASE WHEN ? = 'name' AND ? = 'desc' THEN name END DESC,
  CASE WHEN ? = 'slug' AND ? = 'asc' THEN slug END ASC,
  CASE WHEN ? = 'slug' AND ? = 'desc' THEN slug END DESC,
  CASE WHEN ? = 'role' AND ? = 'asc' THEN role END ASC,
  CASE WHEN ? = 'role' AND ? = 'desc' THEN role END DESC,
  CASE WHEN ? = 'sort_order' AND ? = 'asc' THEN sort_order END ASC,
  CASE WHEN ? = 'sort_order' AND ? = 'desc' THEN sort_order END DESC,
  sort_order ASC, name ASC, id ASC
LIMIT ? OFFSET ?
`

type ListClassiersParams struct {
	Search string      `json:"search"`
	Sort   interface{} `json:"sort"`
	Dir    interface{} `json:"dir"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListClassiers(ctx context.Context, arg ListClassiersParams) ([]Classier, error) {
	rows, err := q.db.QueryContext(ctx, listClassiers,
		arg.Search,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Classier{}
	for rows.Next() {
		var i Classier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.PhotoUrl,
			&i.Bio,
			&i.BirthPlace,
			&i.BirthDate,
			&i.Instagram,
			&i.Twitter,
			&i.Facebook,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClassier = `-- name: UpdateClassier :exec
UPDATE classiers
SET name=?, slug=?, role=?, photo_url=?, bio=?, birth_place=?, birth_date=?, instagram=?, twitter=?, facebook=?, sort_order=?, is_active=?
WHERE id=?
`

type UpdateClassierParams struct {
	Name       string         `json:"name"`
	Slug       string         `json:"slug"`
	Role       sql.NullString `json:"role"`
	PhotoUrl   sql.NullString `json:"photo_url"`
	Bio        sql.NullString `json:"bio"`
	BirthPlace sql.NullString `json:"birth_place"`
	BirthDate  sql.NullString `json:"birth_date"`
	Instagram  sql.NullString `json:"instagram"`
	Twitter    sql.NullString `json:"twitter"`
	Facebook   sql.NullString `json:"facebook"`
	SortOrder  int32          `json:"sort_order"`
	IsActive   bool           `json:"is_active"`
	ID         uint64         `json:"id"`
}

func (q *Queries) UpdateClassier(ctx context.Context, arg UpdateClassierParams) error {
	_, err := q.db.ExecContext(ctx, updateClassier,
		arg.Name,
		arg.Slug,
		arg.Role,
		arg.PhotoUrl,
		arg.Bio,
		arg.BirthPlace,
		arg.BirthDate,
		arg.Instagram,
		arg.Twitter,
		arg.Facebook,
		arg.SortOrder,
		arg.IsActive,
		arg.ID,
	)
	return err
}
