// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connect.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const banChatUser = `-- name: BanChatUser :exec
UPDATE chat_users SET is_banned = 1 WHERE id = ?
`

func (q *Queries) BanChatUser(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, banChatUser, id)
	return err
}

const createChatMessage = `-- name: CreateChatMessage :execresult
INSERT INTO chat_messages (chat_user_id, body) VALUES (?, ?)
`

type CreateChatMessageParams struct {
	ChatUserID uint64 `json:"chat_user_id"`
	Body       string `json:"body"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChatMessage, arg.ChatUserID, arg.Body)
}

const getChatUserByGoogleSub = `-- name: GetChatUserByGoogleSub :one
SELECT id, google_sub, email, name, avatar_url, is_admin, is_banned, created_at, updated_at FROM chat_users WHERE google_sub = ?
`

func (q *Queries) GetChatUserByGoogleSub(ctx context.Context, googleSub string) (ChatUser, error) {
	row := q.db.QueryRowContext(ctx, getChatUserByGoogleSub, googleSub)
	var i ChatUser
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatUserByID = `-- name: GetChatUserByID :one
SELECT id, google_sub, email, name, avatar_url, is_admin, is_banned, created_at, updated_at FROM chat_users WHERE id = ?
`

func (q *Queries) GetChatUserByID(ctx context.Context, id uint64) (ChatUser, error) {
	row := q.db.QueryRowContext(ctx, getChatUserByID, id)
	var i ChatUser
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChatMessagesSince = `-- name: ListChatMessagesSince :many
SELECT
  m.id, m.chat_user_id, m.body, m.created_at,
  u.name AS author_name, u.avatar_url AS author_avatar, u.is_admin AS author_is_admin
FROM chat_messages m
JOIN chat_users u ON u.id = m.chat_user_id
WHERE m.is_deleted = 0 AND m.id > ?
ORDER BY m.id ASC
LIMIT ?
`

type ListChatMessagesSinceParams struct {
	ID    uint64 `json:"id"`
	Limit int32  `json:"limit"`
}

type ListChatMessagesSinceRow struct {
	ID            uint64         `json:"id"`
	ChatUserID    uint64         `json:"chat_user_id"`
	Body          string         `json:"body"`
	CreatedAt     time.Time      `json:"created_at"`
	AuthorName    string         `json:"author_name"`
	AuthorAvatar  sql.NullString `json:"author_avatar"`
	AuthorIsAdmin bool           `json:"author_is_admin"`
}

func (q *Queries) ListChatMessagesSince(ctx context.Context, arg ListChatMessagesSinceParams) ([]ListChatMessagesSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatMessagesSince, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChatMessagesSinceRow{}
	for rows.Next() {
		var i ListChatMessagesSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatUserID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorIsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentChatMessages = `-- name: ListRecentChatMessages :many
SELECT
  m.id, m.chat_user_id, m.body, m.created_at,
  u.name AS author_name, u.avatar_url AS author_avatar, u.is_admin AS author_is_admin
FROM chat_messages m
JOIN chat_users u ON u.id = m.chat_user_id
WHERE m.is_deleted = 0
ORDER BY m.id DESC
LIMIT ?
`

type ListRecentChatMessagesRow struct {
	ID            uint64         `json:"id"`
	ChatUserID    uint64         `json:"chat_user_id"`
	Body          string         `json:"body"`
	CreatedAt     time.Time      `json:"created_at"`
	AuthorName    string         `json:"author_name"`
	AuthorAvatar  sql.NullString `json:"author_avatar"`
	AuthorIsAdmin bool           `json:"author_is_admin"`
}

func (q *Queries) ListRecentChatMessages(ctx context.Context, limit int32) ([]ListRecentChatMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentChatMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentChatMessagesRow{}
	for rows.Next() {
		var i ListRecentChatMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatUserID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorIsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteChatMessage = `-- name: SoftDeleteChatMessage :exec
UPDATE chat_messages SET is_deleted = 1 WHERE id = ?
`

func (q *Queries) SoftDeleteChatMessage(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, softDeleteChatMessage, id)
	return err
}

const upsertChatUser = `-- name: UpsertChatUser :execresult
INSERT INTO chat_users (google_sub, email, name, avatar_url, is_admin)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  email = VALUES(email),
  name = VALUES(name),
  avatar_url = VALUES(avatar_url),
  is_admin = VALUES(is_admin)
`

type UpsertChatUserParams struct {
	GoogleSub string         `json:"google_sub"`
	Email     string         `json:"email"`
	Name      string         `json:"name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	IsAdmin   bool           `json:"is_admin"`
}

// Called on every Google login: creates the chat user on first sign-in, and on return
// refreshes profile fields plus the is_admin badge snapshot (recomputed by the handler).
// created_at/updated_at are driven by the column defaults, not listed here.
func (q *Queries) UpsertChatUser(ctx context.Context, arg UpsertChatUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertChatUser,
		arg.GoogleSub,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.IsAdmin,
	)
}
