// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact_settings.sql

package sqlc

import (
	"context"
)

const getContactSettings = `-- name: GetContactSettings :one
SELECT id, whatsapp_number, whatsapp_message, phone, email, updated_at FROM contact_settings WHERE id = 1
`

func (q *Queries) GetContactSettings(ctx context.Context) (ContactSetting, error) {
	row := q.db.QueryRowContext(ctx, getContactSettings)
	var i ContactSetting
	err := row.Scan(
		&i.ID,
		&i.WhatsappNumber,
		&i.WhatsappMessage,
		&i.Phone,
		&i.Email,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContactSettings = `-- name: UpdateContactSettings :exec
UPDATE contact_settings
SET whatsapp_number = ?, whatsapp_message = ?, phone = ?, email = ?
WHERE id = 1
`

type UpdateContactSettingsParams struct {
	WhatsappNumber  string `json:"whatsapp_number"`
	WhatsappMessage string `json:"whatsapp_message"`
	Phone           string `json:"phone"`
	Email           string `json:"email"`
}

func (q *Queries) UpdateContactSettings(ctx context.Context, arg UpdateContactSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateContactSettings,
		arg.WhatsappNumber,
		arg.WhatsappMessage,
		arg.Phone,
		arg.Email,
	)
	return err
}
