// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*) FROM events WHERE title LIKE ?
`

func (q *Queries) CountEvents(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEvents, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedEvents = `-- name: CountPublishedEvents :one
SELECT COUNT(*) FROM events WHERE is_published = 1
`

func (q *Queries) CountPublishedEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedEventsByCategory = `-- name: CountPublishedEventsByCategory :one
SELECT COUNT(*) FROM events WHERE is_published = 1 AND category = ?
`

func (q *Queries) CountPublishedEventsByCategory(ctx context.Context, category EventsCategory) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedEventsByCategory, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :execresult
INSERT INTO events (title, slug, category, description, image_url, event_date, location, link_url, is_published)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEventParams struct {
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Category    EventsCategory `json:"category"`
	Description string         `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	EventDate   sql.NullTime   `json:"event_date"`
	Location    sql.NullString `json:"location"`
	LinkUrl     sql.NullString `json:"link_url"`
	IsPublished bool           `json:"is_published"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEvent,
		arg.Title,
		arg.Slug,
		arg.Category,
		arg.Description,
		arg.ImageUrl,
		arg.EventDate,
		arg.Location,
		arg.LinkUrl,
		arg.IsPublished,
	)
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = ?
`

func (q *Queries) DeleteEvent(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, title, slug, category, description, image_url, event_date, location, link_url, is_published, created_at, updated_at FROM events WHERE id = ?
`

func (q *Queries) GetEvent(ctx context.Context, id uint64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Category,
		&i.Description,
		&i.ImageUrl,
		&i.EventDate,
		&i.Location,
		&i.LinkUrl,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventBySlug = `-- name: GetEventBySlug :one
SELECT id, title, slug, category, description, image_url, event_date, location, link_url, is_published, created_at, updated_at FROM events WHERE slug = ?
`

func (q *Queries) GetEventBySlug(ctx context.Context, slug string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventBySlug, slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Category,
		&i.Description,
		&i.ImageUrl,
		&i.EventDate,
		&i.Location,
		&i.LinkUrl,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedEventBySlug = `-- name: GetPublishedEventBySlug :one
SELECT id, title, slug, category, description, image_url, event_date, location, link_url, is_published, created_at, updated_at FROM events WHERE slug = ? AND is_published = 1
`

func (q *Queries) GetPublishedEventBySlug(ctx context.Context, slug string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getPublishedEventBySlug, slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Category,
		&i.Description,
		&i.ImageUrl,
		&i.EventDate,
		&i.Location,
		&i.LinkUrl,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, title, slug, category, description, image_url, event_date, location, link_url, is_published, created_at, updated_at FROM events
WHERE title LIKE ?
ORDER BY
  CASE WHEN ? = 'title' AND ? = 'asc' THEN title END ASC,
  CASE WHEN ? = 'title' AND ? = 'desc' THEN title END DESC,
  CASE WHEN ? = 'created_at' AND ? = 'asc' THEN created_at END ASC,
  CASE WHEN ? = 'created_at' AND ? = 'desc' THEN created_at END DESC,
  created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListEventsParams struct {
	Search string      `json:"search"`
	Sort   interface{} `json:"sort"`
	Dir    interface{} `json:"dir"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Category,
			&i.Description,
			&i.ImageUrl,
			&i.EventDate,
			&i.Location,
			&i.LinkUrl,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEvents = `-- name: ListPublishedEvents :many

SELECT id, title, slug, category, description, image_url, event_date, location, link_url, is_published, created_at, updated_at FROM events
WHERE is_published = 1
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListPublishedEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Events are admin-authored (title, description, and uploaded banner are all real form
// input), so unlike podcasts.sql there is no GROUP_CONCAT broadcaster subquery and no
// importer/refresh queries. The public list is newest-first, optionally filtered to one
// category; the admin list adds search + dynamic sort. See 0041_events.up.sql.
func (q *Queries) ListPublishedEvents(ctx context.Context, arg ListPublishedEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Category,
			&i.Description,
			&i.ImageUrl,
			&i.EventDate,
			&i.Location,
			&i.LinkUrl,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEventsByCategory = `-- name: ListPublishedEventsByCategory :many
SELECT id, title, slug, category, description, image_url, event_date, location, link_url, is_published, created_at, updated_at FROM events
WHERE is_published = 1 AND category = ?
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListPublishedEventsByCategoryParams struct {
	Category EventsCategory `json:"category"`
	Limit    int32          `json:"limit"`
	Offset   int32          `json:"offset"`
}

func (q *Queries) ListPublishedEventsByCategory(ctx context.Context, arg ListPublishedEventsByCategoryParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedEventsByCategory, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Category,
			&i.Description,
			&i.ImageUrl,
			&i.EventDate,
			&i.Location,
			&i.LinkUrl,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEventPublished = `-- name: SetEventPublished :exec
UPDATE events SET is_published = ? WHERE id = ?
`

type SetEventPublishedParams struct {
	IsPublished bool   `json:"is_published"`
	ID          uint64 `json:"id"`
}

func (q *Queries) SetEventPublished(ctx context.Context, arg SetEventPublishedParams) error {
	_, err := q.db.ExecContext(ctx, setEventPublished, arg.IsPublished, arg.ID)
	return err
}

const updateEvent = `-- name: UpdateEvent :exec
UPDATE events
SET title = ?, slug = ?, category = ?, description = ?, image_url = ?, event_date = ?, location = ?, link_url = ?, is_published = ?
WHERE id = ?
`

type UpdateEventParams struct {
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Category    EventsCategory `json:"category"`
	Description string         `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	EventDate   sql.NullTime   `json:"event_date"`
	Location    sql.NullString `json:"location"`
	LinkUrl     sql.NullString `json:"link_url"`
	IsPublished bool           `json:"is_published"`
	ID          uint64         `json:"id"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.ExecContext(ctx, updateEvent,
		arg.Title,
		arg.Slug,
		arg.Category,
		arg.Description,
		arg.ImageUrl,
		arg.EventDate,
		arg.Location,
		arg.LinkUrl,
		arg.IsPublished,
		arg.ID,
	)
	return err
}
