// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feed_sources.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getFeedSource = `-- name: GetFeedSource :one
SELECT id, source, is_enabled, endpoint, last_fetched_at, last_status, item_count FROM feed_sources WHERE source = ?
`

func (q *Queries) GetFeedSource(ctx context.Context, source FeedSourcesSource) (FeedSource, error) {
	row := q.db.QueryRowContext(ctx, getFeedSource, source)
	var i FeedSource
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.IsEnabled,
		&i.Endpoint,
		&i.LastFetchedAt,
		&i.LastStatus,
		&i.ItemCount,
	)
	return i, err
}

const listFeedSources = `-- name: ListFeedSources :many
SELECT id, source, is_enabled, endpoint, last_fetched_at, last_status, item_count FROM feed_sources ORDER BY source ASC
`

func (q *Queries) ListFeedSources(ctx context.Context) ([]FeedSource, error) {
	rows, err := q.db.QueryContext(ctx, listFeedSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeedSource{}
	for rows.Next() {
		var i FeedSource
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.IsEnabled,
			&i.Endpoint,
			&i.LastFetchedAt,
			&i.LastStatus,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeedSourceConfig = `-- name: UpdateFeedSourceConfig :exec
UPDATE feed_sources SET is_enabled = ?, endpoint = ? WHERE source = ?
`

type UpdateFeedSourceConfigParams struct {
	IsEnabled bool              `json:"is_enabled"`
	Endpoint  sql.NullString    `json:"endpoint"`
	Source    FeedSourcesSource `json:"source"`
}

func (q *Queries) UpdateFeedSourceConfig(ctx context.Context, arg UpdateFeedSourceConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedSourceConfig, arg.IsEnabled, arg.Endpoint, arg.Source)
	return err
}

const updateFeedSourceStatus = `-- name: UpdateFeedSourceStatus :exec
UPDATE feed_sources
SET last_fetched_at = ?, last_status = ?, item_count = ?
WHERE source = ?
`

type UpdateFeedSourceStatusParams struct {
	LastFetchedAt sql.NullTime      `json:"last_fetched_at"`
	LastStatus    sql.NullString    `json:"last_status"`
	ItemCount     int32             `json:"item_count"`
	Source        FeedSourcesSource `json:"source"`
}

func (q *Queries) UpdateFeedSourceStatus(ctx context.Context, arg UpdateFeedSourceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedSourceStatus,
		arg.LastFetchedAt,
		arg.LastStatus,
		arg.ItemCount,
		arg.Source,
	)
	return err
}
