// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hero.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countHeroSlides = `-- name: CountHeroSlides :one
SELECT COUNT(*) FROM hero_slides
WHERE title LIKE ? OR badge_label LIKE ?
`

type CountHeroSlidesParams struct {
	Search string `json:"search"`
}

func (q *Queries) CountHeroSlides(ctx context.Context, arg CountHeroSlidesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHeroSlides, arg.Search, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHeroSlide = `-- name: CreateHeroSlide :execresult
INSERT INTO hero_slides (title, badge_label, excerpt, image_url, link_url, open_in_new_tab, sort_order, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateHeroSlideParams struct {
	Title        string         `json:"title"`
	BadgeLabel   string         `json:"badge_label"`
	Excerpt      sql.NullString `json:"excerpt"`
	ImageUrl     string         `json:"image_url"`
	LinkUrl      sql.NullString `json:"link_url"`
	OpenInNewTab bool           `json:"open_in_new_tab"`
	SortOrder    int32          `json:"sort_order"`
	IsActive     bool           `json:"is_active"`
}

func (q *Queries) CreateHeroSlide(ctx context.Context, arg CreateHeroSlideParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createHeroSlide,
		arg.Title,
		arg.BadgeLabel,
		arg.Excerpt,
		arg.ImageUrl,
		arg.LinkUrl,
		arg.OpenInNewTab,
		arg.SortOrder,
		arg.IsActive,
	)
}

const deleteHeroSlide = `-- name: DeleteHeroSlide :exec
DELETE FROM hero_slides WHERE id = ?
`

func (q *Queries) DeleteHeroSlide(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteHeroSlide, id)
	return err
}

const getHeroSettings = `-- name: GetHeroSettings :one

SELECT id, order_mode, news_count, max_images, updated_at FROM hero_settings WHERE id = 1
`

// Home page hero slideshow. The public side reads exactly two of these
// (settings + active slides) and mixes the result with the latest news; see
// internal/handlers/public/hero.go. The rest serve /admin/hero.
func (q *Queries) GetHeroSettings(ctx context.Context) (HeroSetting, error) {
	row := q.db.QueryRowContext(ctx, getHeroSettings)
	var i HeroSetting
	err := row.Scan(
		&i.ID,
		&i.OrderMode,
		&i.NewsCount,
		&i.MaxImages,
		&i.UpdatedAt,
	)
	return i, err
}

const getHeroSlide = `-- name: GetHeroSlide :one
SELECT id, title, badge_label, excerpt, image_url, link_url, open_in_new_tab, sort_order, is_active, created_at, updated_at FROM hero_slides WHERE id = ?
`

func (q *Queries) GetHeroSlide(ctx context.Context, id uint64) (HeroSlide, error) {
	row := q.db.QueryRowContext(ctx, getHeroSlide, id)
	var i HeroSlide
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.BadgeLabel,
		&i.Excerpt,
		&i.ImageUrl,
		&i.LinkUrl,
		&i.OpenInNewTab,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveHeroSlides = `-- name: ListActiveHeroSlides :many
SELECT id, title, badge_label, excerpt, image_url, link_url, open_in_new_tab, sort_order, is_active, created_at, updated_at FROM hero_slides
WHERE is_active = 1 AND image_url <> ''
ORDER BY sort_order ASC, id ASC
LIMIT ?
`

// The admin form requires an image, but the image_url <> ” guard keeps a
// hand-edited or otherwise blank row from reaching the template, where it would
// emit <img src=""> - which browsers resolve against the page URL and actually
// fetch.
func (q *Queries) ListActiveHeroSlides(ctx context.Context, limit int32) ([]HeroSlide, error) {
	rows, err := q.db.QueryContext(ctx, listActiveHeroSlides, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeroSlide{}
	for rows.Next() {
		var i HeroSlide
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.BadgeLabel,
			&i.Excerpt,
			&i.ImageUrl,
			&i.LinkUrl,
			&i.OpenInNewTab,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeroSlides = `-- name: ListHeroSlides :many
SELECT id, title, badge_label, excerpt, image_url, link_url, open_in_new_tab, sort_order, is_active, created_at, updated_at FROM hero_slides
WHERE title LIKE ? OR badge_label LIKE ?
ORDER BY
  CASE WHEN ? = 'title' AND ? = 'asc' THEN title END ASC,
  CASE WHEN ? = 'title' AND ? = 'desc' THEN title END DESC,
  CASE WHEN ? = 'badge_label' AND ? = 'asc' THEN badge_label END ASC,
  CASE WHEN ? = 'badge_label' AND ? = 'desc' THEN badge_label END DESC,
  CASE WHEN ? = 'sort_order' AND ? = 'asc' THEN sort_order END ASC,
  CASE WHEN ? = 'sort_order' AND ? = 'desc' THEN sort_order END DESC,
  CASE WHEN ? = 'updated_at' AND ? = 'asc' THEN updated_at END ASC,
  CASE WHEN ? = 'updated_at' AND ? = 'desc' THEN updated_at END DESC,
  sort_order ASC, id ASC
LIMIT ? OFFSET ?
`

type ListHeroSlidesParams struct {
	Search string      `json:"search"`
	Sort   interface{} `json:"sort"`
	Dir    interface{} `json:"dir"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListHeroSlides(ctx context.Context, arg ListHeroSlidesParams) ([]HeroSlide, error) {
	rows, err := q.db.QueryContext(ctx, listHeroSlides,
		arg.Search,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeroSlide{}
	for rows.Next() {
		var i HeroSlide
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.BadgeLabel,
			&i.Excerpt,
			&i.ImageUrl,
			&i.LinkUrl,
			&i.OpenInNewTab,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHeroSettings = `-- name: UpdateHeroSettings :exec
UPDATE hero_settings SET order_mode = ?, news_count = ?, max_images = ? WHERE id = 1
`

type UpdateHeroSettingsParams struct {
	OrderMode HeroSettingsOrderMode `json:"order_mode"`
	NewsCount int32                 `json:"news_count"`
	MaxImages int32                 `json:"max_images"`
}

func (q *Queries) UpdateHeroSettings(ctx context.Context, arg UpdateHeroSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateHeroSettings, arg.OrderMode, arg.NewsCount, arg.MaxImages)
	return err
}

const updateHeroSlide = `-- name: UpdateHeroSlide :exec
UPDATE hero_slides
SET title=?, badge_label=?, excerpt=?, image_url=?, link_url=?, open_in_new_tab=?, sort_order=?, is_active=?
WHERE id=?
`

type UpdateHeroSlideParams struct {
	Title        string         `json:"title"`
	BadgeLabel   string         `json:"badge_label"`
	Excerpt      sql.NullString `json:"excerpt"`
	ImageUrl     string         `json:"image_url"`
	LinkUrl      sql.NullString `json:"link_url"`
	OpenInNewTab bool           `json:"open_in_new_tab"`
	SortOrder    int32          `json:"sort_order"`
	IsActive     bool           `json:"is_active"`
	ID           uint64         `json:"id"`
}

func (q *Queries) UpdateHeroSlide(ctx context.Context, arg UpdateHeroSlideParams) error {
	_, err := q.db.ExecContext(ctx, updateHeroSlide,
		arg.Title,
		arg.BadgeLabel,
		arg.Excerpt,
		arg.ImageUrl,
		arg.LinkUrl,
		arg.OpenInNewTab,
		arg.SortOrder,
		arg.IsActive,
		arg.ID,
	)
	return err
}
