// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: legal_pages.sql

package sqlc

import (
	"context"
)

const getLegalPage = `-- name: GetLegalPage :one
SELECT slug, title, intro, body, updated_at FROM legal_pages WHERE slug = ?
`

func (q *Queries) GetLegalPage(ctx context.Context, slug LegalPagesSlug) (LegalPage, error) {
	row := q.db.QueryRowContext(ctx, getLegalPage, slug)
	var i LegalPage
	err := row.Scan(
		&i.Slug,
		&i.Title,
		&i.Intro,
		&i.Body,
		&i.UpdatedAt,
	)
	return i, err
}

const listLegalPages = `-- name: ListLegalPages :many
SELECT slug, title, intro, body, updated_at FROM legal_pages ORDER BY slug
`

func (q *Queries) ListLegalPages(ctx context.Context) ([]LegalPage, error) {
	rows, err := q.db.QueryContext(ctx, listLegalPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LegalPage{}
	for rows.Next() {
		var i LegalPage
		if err := rows.Scan(
			&i.Slug,
			&i.Title,
			&i.Intro,
			&i.Body,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLegalPage = `-- name: UpdateLegalPage :exec
UPDATE legal_pages SET title = ?, intro = ?, body = ? WHERE slug = ?
`

type UpdateLegalPageParams struct {
	Title string         `json:"title"`
	Intro string         `json:"intro"`
	Body  string         `json:"body"`
	Slug  LegalPagesSlug `json:"slug"`
}

func (q *Queries) UpdateLegalPage(ctx context.Context, arg UpdateLegalPageParams) error {
	_, err := q.db.ExecContext(ctx, updateLegalPage,
		arg.Title,
		arg.Intro,
		arg.Body,
		arg.Slug,
	)
	return err
}
