// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: listeners.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getListenerDay = `-- name: GetListenerDay :one
SELECT stat_date, peak_listeners, peak_at, last_listeners, sample_count, created_at, updated_at FROM listener_stats WHERE stat_date = ?
`

func (q *Queries) GetListenerDay(ctx context.Context, statDate time.Time) (ListenerStat, error) {
	row := q.db.QueryRowContext(ctx, getListenerDay, statDate)
	var i ListenerStat
	err := row.Scan(
		&i.StatDate,
		&i.PeakListeners,
		&i.PeakAt,
		&i.LastListeners,
		&i.SampleCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertListenerSample = `-- name: InsertListenerSample :exec

INSERT INTO listener_samples (sampled_at, listeners, is_live) VALUES (?, ?, ?)
`

type InsertListenerSampleParams struct {
	SampledAt time.Time `json:"sampled_at"`
	Listeners uint32    `json:"listeners"`
	IsLive    bool      `json:"is_live"`
}

// Listener history: written by internal/listeners.Sampler, read by the admin
// dashboard's listener chart (internal/handlers/admin/dashboard_charts.go).
// See migration 0028 for why the daily rollup and the raw trail are separate.
func (q *Queries) InsertListenerSample(ctx context.Context, arg InsertListenerSampleParams) error {
	_, err := q.db.ExecContext(ctx, insertListenerSample, arg.SampledAt, arg.Listeners, arg.IsLive)
	return err
}

const listListenerStats = `-- name: ListListenerStats :many
SELECT stat_date, peak_listeners, peak_at, last_listeners, sample_count, created_at, updated_at FROM listener_stats WHERE stat_date >= ? ORDER BY stat_date ASC
`

func (q *Queries) ListListenerStats(ctx context.Context, statDate time.Time) ([]ListenerStat, error) {
	rows, err := q.db.QueryContext(ctx, listListenerStats, statDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListenerStat{}
	for rows.Next() {
		var i ListenerStat
		if err := rows.Scan(
			&i.StatDate,
			&i.PeakListeners,
			&i.PeakAt,
			&i.LastListeners,
			&i.SampleCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneListenerSamples = `-- name: PruneListenerSamples :exec
DELETE FROM listener_samples WHERE sampled_at < ?
`

func (q *Queries) PruneListenerSamples(ctx context.Context, sampledAt time.Time) error {
	_, err := q.db.ExecContext(ctx, pruneListenerSamples, sampledAt)
	return err
}

const upsertListenerDay = `-- name: UpsertListenerDay :exec
INSERT INTO listener_stats (stat_date, peak_listeners, peak_at, last_listeners, sample_count)
VALUES (?, ?, ?, ?, 1)
ON DUPLICATE KEY UPDATE
  peak_at        = IF(? > peak_listeners, ?, peak_at),
  peak_listeners = GREATEST(peak_listeners, ?),
  last_listeners = ?,
  sample_count   = sample_count + 1
`

type UpsertListenerDayParams struct {
	StatDate  time.Time    `json:"stat_date"`
	Listeners uint32       `json:"listeners"`
	SampledAt sql.NullTime `json:"sampled_at"`
}

// Folds one sample into its day's row, monotonic in peak_listeners so a quiet
// afternoon can never lower the morning's peak.
//
// peak_at is assigned before peak_listeners on purpose: MySQL evaluates the SET
// list left to right, so the comparison has to run while peak_listeners still
// holds the old value.
func (q *Queries) UpsertListenerDay(ctx context.Context, arg UpsertListenerDayParams) error {
	_, err := q.db.ExecContext(ctx, upsertListenerDay,
		arg.StatDate,
		arg.Listeners,
		arg.SampledAt,
		arg.Listeners,
		arg.Listeners,
		arg.SampledAt,
		arg.Listeners,
		arg.Listeners,
	)
	return err
}
