// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: media_links.sql

package sqlc

import (
	"context"
)

const listMediaLinks = `-- name: ListMediaLinks :many
SELECT id, url, platform FROM media_links
ORDER BY platform ASC
`

func (q *Queries) ListMediaLinks(ctx context.Context) ([]MediaLink, error) {
	rows, err := q.db.QueryContext(ctx, listMediaLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaLink{}
	for rows.Next() {
		var i MediaLink
		if err := rows.Scan(&i.ID, &i.Url, &i.Platform); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaLinkURL = `-- name: UpdateMediaLinkURL :exec
UPDATE media_links SET url = ? WHERE platform = ?
`

type UpdateMediaLinkURLParams struct {
	Url      string             `json:"url"`
	Platform MediaLinksPlatform `json:"platform"`
}

func (q *Queries) UpdateMediaLinkURL(ctx context.Context, arg UpdateMediaLinkURLParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaLinkURL, arg.Url, arg.Platform)
	return err
}
