// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menu_settings.sql

package sqlc

import (
	"context"
)

const getMenuSettings = `-- name: GetMenuSettings :one
SELECT id, show_news, show_podcast, show_event, updated_at FROM menu_settings WHERE id = 1
`

func (q *Queries) GetMenuSettings(ctx context.Context) (MenuSetting, error) {
	row := q.db.QueryRowContext(ctx, getMenuSettings)
	var i MenuSetting
	err := row.Scan(
		&i.ID,
		&i.ShowNews,
		&i.ShowPodcast,
		&i.ShowEvent,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMenuSettings = `-- name: UpdateMenuSettings :exec
UPDATE menu_settings
SET show_news = ?, show_podcast = ?, show_event = ?
WHERE id = 1
`

type UpdateMenuSettingsParams struct {
	ShowNews    bool `json:"show_news"`
	ShowPodcast bool `json:"show_podcast"`
	ShowEvent   bool `json:"show_event"`
}

func (q *Queries) UpdateMenuSettings(ctx context.Context, arg UpdateMenuSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateMenuSettings, arg.ShowNews, arg.ShowPodcast, arg.ShowEvent)
	return err
}
