// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type AboutPageBannerMediaType string

const (
	AboutPageBannerMediaTypeImage AboutPageBannerMediaType = "image"
	AboutPageBannerMediaTypeVideo AboutPageBannerMediaType = "video"
)

func (e *AboutPageBannerMediaType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AboutPageBannerMediaType(s)
	case string:
		*e = AboutPageBannerMediaType(s)
	default:
		return fmt.Errorf("unsupported scan type for AboutPageBannerMediaType: %T", src)
	}
	return nil
}

type NullAboutPageBannerMediaType struct {
	AboutPageBannerMediaType AboutPageBannerMediaType `json:"about_page_banner_media_type"`
	Valid                    bool                     `json:"valid"` // Valid is true if AboutPageBannerMediaType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAboutPageBannerMediaType) Scan(value interface{}) error {
	if value == nil {
		ns.AboutPageBannerMediaType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AboutPageBannerMediaType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAboutPageBannerMediaType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AboutPageBannerMediaType), nil
}

type AboutPageSegmentsSegment string

const (
	AboutPageSegmentsSegmentProfile  AboutPageSegmentsSegment = "profile"
	AboutPageSegmentsSegmentMusic    AboutPageSegmentsSegment = "music"
	AboutPageSegmentsSegmentAudience AboutPageSegmentsSegment = "audience"
)

func (e *AboutPageSegmentsSegment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AboutPageSegmentsSegment(s)
	case string:
		*e = AboutPageSegmentsSegment(s)
	default:
		return fmt.Errorf("unsupported scan type for AboutPageSegmentsSegment: %T", src)
	}
	return nil
}

type NullAboutPageSegmentsSegment struct {
	AboutPageSegmentsSegment AboutPageSegmentsSegment `json:"about_page_segments_segment"`
	Valid                    bool                     `json:"valid"` // Valid is true if AboutPageSegmentsSegment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAboutPageSegmentsSegment) Scan(value interface{}) error {
	if value == nil {
		ns.AboutPageSegmentsSegment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AboutPageSegmentsSegment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAboutPageSegmentsSegment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AboutPageSegmentsSegment), nil
}

type AdBannerPagesPage string

const (
	AdBannerPagesPageHome              AdBannerPagesPage = "home"
	AdBannerPagesPageAbout             AdBannerPagesPage = "about"
	AdBannerPagesPageProgram           AdBannerPagesPage = "program"
	AdBannerPagesPageProgramDetail     AdBannerPagesPage = "program_detail"
	AdBannerPagesPageLive              AdBannerPagesPage = "live"
	AdBannerPagesPageNews              AdBannerPagesPage = "news"
	AdBannerPagesPageNewsDetail        AdBannerPagesPage = "news_detail"
	AdBannerPagesPageBroadcasters      AdBannerPagesPage = "broadcasters"
	AdBannerPagesPageBroadcasterDetail AdBannerPagesPage = "broadcaster_detail"
)

func (e *AdBannerPagesPage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdBannerPagesPage(s)
	case string:
		*e = AdBannerPagesPage(s)
	default:
		return fmt.Errorf("unsupported scan type for AdBannerPagesPage: %T", src)
	}
	return nil
}

type NullAdBannerPagesPage struct {
	AdBannerPagesPage AdBannerPagesPage `json:"ad_banner_pages_page"`
	Valid             bool              `json:"valid"` // Valid is true if AdBannerPagesPage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdBannerPagesPage) Scan(value interface{}) error {
	if value == nil {
		ns.AdBannerPagesPage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdBannerPagesPage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdBannerPagesPage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdBannerPagesPage), nil
}

type AdBannersSlot string

const (
	AdBannersSlotTop    AdBannersSlot = "top"
	AdBannersSlotBottom AdBannersSlot = "bottom"
)

func (e *AdBannersSlot) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdBannersSlot(s)
	case string:
		*e = AdBannersSlot(s)
	default:
		return fmt.Errorf("unsupported scan type for AdBannersSlot: %T", src)
	}
	return nil
}

type NullAdBannersSlot struct {
	AdBannersSlot AdBannersSlot `json:"ad_banners_slot"`
	Valid         bool          `json:"valid"` // Valid is true if AdBannersSlot is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdBannersSlot) Scan(value interface{}) error {
	if value == nil {
		ns.AdBannersSlot, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdBannersSlot.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdBannersSlot) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdBannersSlot), nil
}

type AdSlotsDisplayMode string

const (
	AdSlotsDisplayModeStacked   AdSlotsDisplayMode = "stacked"
	AdSlotsDisplayModeSlideshow AdSlotsDisplayMode = "slideshow"
)

func (e *AdSlotsDisplayMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdSlotsDisplayMode(s)
	case string:
		*e = AdSlotsDisplayMode(s)
	default:
		return fmt.Errorf("unsupported scan type for AdSlotsDisplayMode: %T", src)
	}
	return nil
}

type NullAdSlotsDisplayMode struct {
	AdSlotsDisplayMode AdSlotsDisplayMode `json:"ad_slots_display_mode"`
	Valid              bool               `json:"valid"` // Valid is true if AdSlotsDisplayMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdSlotsDisplayMode) Scan(value interface{}) error {
	if value == nil {
		ns.AdSlotsDisplayMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdSlotsDisplayMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdSlotsDisplayMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdSlotsDisplayMode), nil
}

type AdSlotsSlot string

const (
	AdSlotsSlotTop    AdSlotsSlot = "top"
	AdSlotsSlotBottom AdSlotsSlot = "bottom"
)

func (e *AdSlotsSlot) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdSlotsSlot(s)
	case string:
		*e = AdSlotsSlot(s)
	default:
		return fmt.Errorf("unsupported scan type for AdSlotsSlot: %T", src)
	}
	return nil
}

type NullAdSlotsSlot struct {
	AdSlotsSlot AdSlotsSlot `json:"ad_slots_slot"`
	Valid       bool        `json:"valid"` // Valid is true if AdSlotsSlot is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdSlotsSlot) Scan(value interface{}) error {
	if value == nil {
		ns.AdSlotsSlot, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdSlotsSlot.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdSlotsSlot) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdSlotsSlot), nil
}

type FeedSourcesSource string

const (
	FeedSourcesSourceYoutube     FeedSourcesSource = "youtube"
	FeedSourcesSourceKlikpositif FeedSourcesSource = "klikpositif"
	FeedSourcesSourceKatasumbar  FeedSourcesSource = "katasumbar"
)

func (e *FeedSourcesSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeedSourcesSource(s)
	case string:
		*e = FeedSourcesSource(s)
	default:
		return fmt.Errorf("unsupported scan type for FeedSourcesSource: %T", src)
	}
	return nil
}

type NullFeedSourcesSource struct {
	FeedSourcesSource FeedSourcesSource `json:"feed_sources_source"`
	Valid             bool              `json:"valid"` // Valid is true if FeedSourcesSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFeedSourcesSource) Scan(value interface{}) error {
	if value == nil {
		ns.FeedSourcesSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FeedSourcesSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFeedSourcesSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FeedSourcesSource), nil
}

type HeroSettingsOrderMode string

const (
	HeroSettingsOrderModeRandom      HeroSettingsOrderMode = "random"
	HeroSettingsOrderModeUpdated     HeroSettingsOrderMode = "updated"
	HeroSettingsOrderModeNewsFirst   HeroSettingsOrderMode = "news_first"
	HeroSettingsOrderModeImagesFirst HeroSettingsOrderMode = "images_first"
)

func (e *HeroSettingsOrderMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HeroSettingsOrderMode(s)
	case string:
		*e = HeroSettingsOrderMode(s)
	default:
		return fmt.Errorf("unsupported scan type for HeroSettingsOrderMode: %T", src)
	}
	return nil
}

type NullHeroSettingsOrderMode struct {
	HeroSettingsOrderMode HeroSettingsOrderMode `json:"hero_settings_order_mode"`
	Valid                 bool                  `json:"valid"` // Valid is true if HeroSettingsOrderMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHeroSettingsOrderMode) Scan(value interface{}) error {
	if value == nil {
		ns.HeroSettingsOrderMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HeroSettingsOrderMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHeroSettingsOrderMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HeroSettingsOrderMode), nil
}

type MediaLinksPlatform string

const (
	MediaLinksPlatformInstagram MediaLinksPlatform = "instagram"
	MediaLinksPlatformFacebook  MediaLinksPlatform = "facebook"
	MediaLinksPlatformX         MediaLinksPlatform = "x"
	MediaLinksPlatformYoutube   MediaLinksPlatform = "youtube"
	MediaLinksPlatformSpotify   MediaLinksPlatform = "spotify"
	MediaLinksPlatformTiktok    MediaLinksPlatform = "tiktok"
)

func (e *MediaLinksPlatform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaLinksPlatform(s)
	case string:
		*e = MediaLinksPlatform(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaLinksPlatform: %T", src)
	}
	return nil
}

type NullMediaLinksPlatform struct {
	MediaLinksPlatform MediaLinksPlatform `json:"media_links_platform"`
	Valid              bool               `json:"valid"` // Valid is true if MediaLinksPlatform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaLinksPlatform) Scan(value interface{}) error {
	if value == nil {
		ns.MediaLinksPlatform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaLinksPlatform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaLinksPlatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaLinksPlatform), nil
}

type NewsItemsSource string

const (
	NewsItemsSourceYoutube     NewsItemsSource = "youtube"
	NewsItemsSourceKlikpositif NewsItemsSource = "klikpositif"
	NewsItemsSourceKatasumbar  NewsItemsSource = "katasumbar"
	NewsItemsSourceHotRelease  NewsItemsSource = "hot_release"
)

func (e *NewsItemsSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NewsItemsSource(s)
	case string:
		*e = NewsItemsSource(s)
	default:
		return fmt.Errorf("unsupported scan type for NewsItemsSource: %T", src)
	}
	return nil
}

type NullNewsItemsSource struct {
	NewsItemsSource NewsItemsSource `json:"news_items_source"`
	Valid           bool            `json:"valid"` // Valid is true if NewsItemsSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNewsItemsSource) Scan(value interface{}) error {
	if value == nil {
		ns.NewsItemsSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NewsItemsSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNewsItemsSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NewsItemsSource), nil
}

type UsersRole string

const (
	UsersRoleSuperadmin UsersRole = "superadmin"
	UsersRoleAdmin      UsersRole = "admin"
)

func (e *UsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRole(s)
	case string:
		*e = UsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRole: %T", src)
	}
	return nil
}

type NullUsersRole struct {
	UsersRole UsersRole `json:"users_role"`
	Valid     bool      `json:"valid"` // Valid is true if UsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRole), nil
}

type AboutPageBanner struct {
	ID        uint8                    `json:"id"`
	MediaType AboutPageBannerMediaType `json:"media_type"`
	ImageUrl  sql.NullString           `json:"image_url"`
	VideoUrl  sql.NullString           `json:"video_url"`
	UpdatedAt time.Time                `json:"updated_at"`
}

type AboutPageSegment struct {
	ID        uint64                   `json:"id"`
	Segment   AboutPageSegmentsSegment `json:"segment"`
	Title     string                   `json:"title"`
	Body      string                   `json:"body"`
	UpdatedAt time.Time                `json:"updated_at"`
}

type AdBanner struct {
	ID        uint64         `json:"id"`
	Slot      AdBannersSlot  `json:"slot"`
	Title     string         `json:"title"`
	AltText   string         `json:"alt_text"`
	ImageUrl  string         `json:"image_url"`
	LinkUrl   sql.NullString `json:"link_url"`
	SortOrder int32          `json:"sort_order"`
	IsActive  bool           `json:"is_active"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type AdBannerPage struct {
	BannerID uint64            `json:"banner_id"`
	Page     AdBannerPagesPage `json:"page"`
}

type AdSlot struct {
	Slot            AdSlotsSlot        `json:"slot"`
	Label           string             `json:"label"`
	DisplayMode     AdSlotsDisplayMode `json:"display_mode"`
	RotateSecs      int32              `json:"rotate_secs"`
	ShowPlaceholder bool               `json:"show_placeholder"`
	PlaceholderText string             `json:"placeholder_text"`
	IsActive        bool               `json:"is_active"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type AuditLog struct {
	ID                uint64        `json:"id"`
	UserID            sql.NullInt64 `json:"user_id"`
	UserEmailSnapshot string        `json:"user_email_snapshot"`
	Action            string        `json:"action"`
	EntityType        string        `json:"entity_type"`
	EntityID          sql.NullInt64 `json:"entity_id"`
	Detail            string        `json:"detail"`
	IpAddress         string        `json:"ip_address"`
	CreatedAt         time.Time     `json:"created_at"`
}

type Broadcaster struct {
	ID         uint64         `json:"id"`
	Name       string         `json:"name"`
	Slug       string         `json:"slug"`
	Role       sql.NullString `json:"role"`
	PhotoUrl   sql.NullString `json:"photo_url"`
	Bio        sql.NullString `json:"bio"`
	BirthPlace sql.NullString `json:"birth_place"`
	BirthDate  sql.NullString `json:"birth_date"`
	Instagram  sql.NullString `json:"instagram"`
	Twitter    sql.NullString `json:"twitter"`
	Facebook   sql.NullString `json:"facebook"`
	SortOrder  int32          `json:"sort_order"`
	IsActive   bool           `json:"is_active"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type FeedSource struct {
	ID            uint64            `json:"id"`
	Source        FeedSourcesSource `json:"source"`
	IsEnabled     bool              `json:"is_enabled"`
	Endpoint      sql.NullString    `json:"endpoint"`
	LastFetchedAt sql.NullTime      `json:"last_fetched_at"`
	LastStatus    sql.NullString    `json:"last_status"`
	ItemCount     int32             `json:"item_count"`
}

type HeroSetting struct {
	ID        uint8                 `json:"id"`
	OrderMode HeroSettingsOrderMode `json:"order_mode"`
	NewsCount int32                 `json:"news_count"`
	MaxImages int32                 `json:"max_images"`
	UpdatedAt time.Time             `json:"updated_at"`
}

type HeroSlide struct {
	ID           uint64         `json:"id"`
	Title        string         `json:"title"`
	BadgeLabel   string         `json:"badge_label"`
	Excerpt      sql.NullString `json:"excerpt"`
	ImageUrl     string         `json:"image_url"`
	LinkUrl      sql.NullString `json:"link_url"`
	OpenInNewTab bool           `json:"open_in_new_tab"`
	SortOrder    int32          `json:"sort_order"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type ListenerSample struct {
	ID        uint64    `json:"id"`
	SampledAt time.Time `json:"sampled_at"`
	Listeners uint32    `json:"listeners"`
	IsLive    bool      `json:"is_live"`
}

type ListenerStat struct {
	StatDate      time.Time    `json:"stat_date"`
	PeakListeners uint32       `json:"peak_listeners"`
	PeakAt        sql.NullTime `json:"peak_at"`
	LastListeners uint32       `json:"last_listeners"`
	SampleCount   uint32       `json:"sample_count"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
}

type MediaLink struct {
	ID       uint64             `json:"id"`
	Url      string             `json:"url"`
	Platform MediaLinksPlatform `json:"platform"`
}

type NewsItem struct {
	ID          uint64          `json:"id"`
	Source      NewsItemsSource `json:"source"`
	ExternalID  sql.NullString  `json:"external_id"`
	Title       string          `json:"title"`
	Slug        sql.NullString  `json:"slug"`
	Excerpt     sql.NullString  `json:"excerpt"`
	Content     sql.NullString  `json:"content"`
	Url         sql.NullString  `json:"url"`
	ImageUrl    sql.NullString  `json:"image_url"`
	PublishedAt time.Time       `json:"published_at"`
	IsPublished bool            `json:"is_published"`
	IsFeatured  bool            `json:"is_featured"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	ThumbUrl    sql.NullString  `json:"thumb_url"`
}

type PasswordResetToken struct {
	TokenHash string       `json:"token_hash"`
	UserID    uint64       `json:"user_id"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type Podcast struct {
	ID          uint64         `json:"id"`
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Description string         `json:"description"`
	SpotifyUrl  string         `json:"spotify_url"`
	ThumbUrl    sql.NullString `json:"thumb_url"`
	IsPublished bool           `json:"is_published"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	SeriesID    uint64         `json:"series_id"`
}

type PodcastBroadcaster struct {
	PodcastID     uint64 `json:"podcast_id"`
	BroadcasterID uint64 `json:"broadcaster_id"`
}

type PodcastSeries struct {
	ID        uint64    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Program struct {
	ID          uint64         `json:"id"`
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	SortOrder   int32          `json:"sort_order"`
	IsActive    bool           `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type ProgramBroadcaster struct {
	ProgramID     uint64 `json:"program_id"`
	BroadcasterID uint64 `json:"broadcaster_id"`
}

type ProgramSchedule struct {
	ID        uint64 `json:"id"`
	ProgramID uint64 `json:"program_id"`
	DayOfWeek int8   `json:"day_of_week"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
}

type ScheduleBroadcaster struct {
	ScheduleID    uint64 `json:"schedule_id"`
	BroadcasterID uint64 `json:"broadcaster_id"`
}

type Session struct {
	Token     string    `json:"token"`
	UserID    uint64    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

type Setting struct {
	K string `json:"k"`
	V string `json:"v"`
}

type User struct {
	ID           uint64    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
	CreatedAt    time.Time `json:"created_at"`
	Role         UsersRole `json:"role"`
	IsActive     bool      `json:"is_active"`
}
