// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type FeedSourcesSource string

const (
	FeedSourcesSourceYoutube     FeedSourcesSource = "youtube"
	FeedSourcesSourceKlikpositif FeedSourcesSource = "klikpositif"
	FeedSourcesSourceKatasumbar  FeedSourcesSource = "katasumbar"
)

func (e *FeedSourcesSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeedSourcesSource(s)
	case string:
		*e = FeedSourcesSource(s)
	default:
		return fmt.Errorf("unsupported scan type for FeedSourcesSource: %T", src)
	}
	return nil
}

type NullFeedSourcesSource struct {
	FeedSourcesSource FeedSourcesSource `json:"feed_sources_source"`
	Valid             bool              `json:"valid"` // Valid is true if FeedSourcesSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFeedSourcesSource) Scan(value interface{}) error {
	if value == nil {
		ns.FeedSourcesSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FeedSourcesSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFeedSourcesSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FeedSourcesSource), nil
}

type MediaLinksPlatform string

const (
	MediaLinksPlatformInstagram MediaLinksPlatform = "instagram"
	MediaLinksPlatformFacebook  MediaLinksPlatform = "facebook"
	MediaLinksPlatformX         MediaLinksPlatform = "x"
	MediaLinksPlatformYoutube   MediaLinksPlatform = "youtube"
	MediaLinksPlatformSpotify   MediaLinksPlatform = "spotify"
)

func (e *MediaLinksPlatform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaLinksPlatform(s)
	case string:
		*e = MediaLinksPlatform(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaLinksPlatform: %T", src)
	}
	return nil
}

type NullMediaLinksPlatform struct {
	MediaLinksPlatform MediaLinksPlatform `json:"media_links_platform"`
	Valid              bool               `json:"valid"` // Valid is true if MediaLinksPlatform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaLinksPlatform) Scan(value interface{}) error {
	if value == nil {
		ns.MediaLinksPlatform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaLinksPlatform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaLinksPlatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaLinksPlatform), nil
}

type NewsItemsSource string

const (
	NewsItemsSourceYoutube     NewsItemsSource = "youtube"
	NewsItemsSourceKlikpositif NewsItemsSource = "klikpositif"
	NewsItemsSourceKatasumbar  NewsItemsSource = "katasumbar"
	NewsItemsSourceHotRelease  NewsItemsSource = "hot_release"
)

func (e *NewsItemsSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NewsItemsSource(s)
	case string:
		*e = NewsItemsSource(s)
	default:
		return fmt.Errorf("unsupported scan type for NewsItemsSource: %T", src)
	}
	return nil
}

type NullNewsItemsSource struct {
	NewsItemsSource NewsItemsSource `json:"news_items_source"`
	Valid           bool            `json:"valid"` // Valid is true if NewsItemsSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNewsItemsSource) Scan(value interface{}) error {
	if value == nil {
		ns.NewsItemsSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NewsItemsSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNewsItemsSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NewsItemsSource), nil
}

type UsersRole string

const (
	UsersRoleSuperadmin UsersRole = "superadmin"
	UsersRoleAdmin      UsersRole = "admin"
)

func (e *UsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRole(s)
	case string:
		*e = UsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRole: %T", src)
	}
	return nil
}

type NullUsersRole struct {
	UsersRole UsersRole `json:"users_role"`
	Valid     bool      `json:"valid"` // Valid is true if UsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRole), nil
}

type AuditLog struct {
	ID                uint64        `json:"id"`
	UserID            sql.NullInt64 `json:"user_id"`
	UserEmailSnapshot string        `json:"user_email_snapshot"`
	Action            string        `json:"action"`
	EntityType        string        `json:"entity_type"`
	EntityID          sql.NullInt64 `json:"entity_id"`
	Detail            string        `json:"detail"`
	IpAddress         string        `json:"ip_address"`
	CreatedAt         time.Time     `json:"created_at"`
}

type Classier struct {
	ID         uint64         `json:"id"`
	Name       string         `json:"name"`
	Slug       string         `json:"slug"`
	Role       sql.NullString `json:"role"`
	PhotoUrl   sql.NullString `json:"photo_url"`
	Bio        sql.NullString `json:"bio"`
	BirthPlace sql.NullString `json:"birth_place"`
	BirthDate  sql.NullString `json:"birth_date"`
	Instagram  sql.NullString `json:"instagram"`
	Twitter    sql.NullString `json:"twitter"`
	Facebook   sql.NullString `json:"facebook"`
	SortOrder  int32          `json:"sort_order"`
	IsActive   bool           `json:"is_active"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type FeedSource struct {
	ID            uint64            `json:"id"`
	Source        FeedSourcesSource `json:"source"`
	IsEnabled     bool              `json:"is_enabled"`
	Endpoint      sql.NullString    `json:"endpoint"`
	LastFetchedAt sql.NullTime      `json:"last_fetched_at"`
	LastStatus    sql.NullString    `json:"last_status"`
	ItemCount     int32             `json:"item_count"`
}

type MediaLink struct {
	ID       uint64             `json:"id"`
	Url      string             `json:"url"`
	Platform MediaLinksPlatform `json:"platform"`
}

type NewsItem struct {
	ID          uint64          `json:"id"`
	Source      NewsItemsSource `json:"source"`
	ExternalID  sql.NullString  `json:"external_id"`
	Title       string          `json:"title"`
	Slug        sql.NullString  `json:"slug"`
	Excerpt     sql.NullString  `json:"excerpt"`
	Content     sql.NullString  `json:"content"`
	Url         sql.NullString  `json:"url"`
	ImageUrl    sql.NullString  `json:"image_url"`
	PublishedAt time.Time       `json:"published_at"`
	IsPublished bool            `json:"is_published"`
	IsFeatured  bool            `json:"is_featured"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type PasswordResetToken struct {
	TokenHash string       `json:"token_hash"`
	UserID    uint64       `json:"user_id"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type Program struct {
	ID          uint64         `json:"id"`
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	Host        sql.NullString `json:"host"`
	ImageUrl    sql.NullString `json:"image_url"`
	SortOrder   int32          `json:"sort_order"`
	IsActive    bool           `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type ProgramSchedule struct {
	ID        uint64         `json:"id"`
	ProgramID uint64         `json:"program_id"`
	DayOfWeek int8           `json:"day_of_week"`
	StartTime string         `json:"start_time"`
	EndTime   string         `json:"end_time"`
	Host      sql.NullString `json:"host"`
}

type Session struct {
	Token     string    `json:"token"`
	UserID    uint64    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

type Setting struct {
	K string `json:"k"`
	V string `json:"v"`
}

type User struct {
	ID           uint64    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
	CreatedAt    time.Time `json:"created_at"`
	Role         UsersRole `json:"role"`
	IsActive     bool      `json:"is_active"`
}
