// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: news.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countAggregatedNews = `-- name: CountAggregatedNews :one
SELECT COUNT(*) FROM news_items
WHERE source != 'hot_release'
  AND (? = '' OR source = ?)
  AND title LIKE ?
`

type CountAggregatedNewsParams struct {
	Source NewsItemsSource `json:"source"`
	Search string          `json:"search"`
}

func (q *Queries) CountAggregatedNews(ctx context.Context, arg CountAggregatedNewsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAggregatedNews, arg.Source, arg.Source, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllHotRelease = `-- name: CountAllHotRelease :one
SELECT COUNT(*) FROM news_items WHERE source = 'hot_release' AND title LIKE ?
`

func (q *Queries) CountAllHotRelease(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllHotRelease, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedNews = `-- name: CountPublishedNews :one
SELECT COUNT(*) FROM news_items WHERE is_published = 1
`

func (q *Queries) CountPublishedNews(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedNews)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedNewsBySource = `-- name: CountPublishedNewsBySource :one
SELECT COUNT(*) FROM news_items WHERE is_published = 1 AND source = ?
`

func (q *Queries) CountPublishedNewsBySource(ctx context.Context, source NewsItemsSource) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedNewsBySource, source)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHotRelease = `-- name: CreateHotRelease :execresult
INSERT INTO news_items (source, title, slug, excerpt, content, image_url, thumb_url, middle_images, published_at, is_published, is_featured)
VALUES ('hot_release', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateHotReleaseParams struct {
	Title        string         `json:"title"`
	Slug         sql.NullString `json:"slug"`
	Excerpt      sql.NullString `json:"excerpt"`
	Content      sql.NullString `json:"content"`
	ImageUrl     sql.NullString `json:"image_url"`
	ThumbUrl     sql.NullString `json:"thumb_url"`
	MiddleImages sql.NullString `json:"middle_images"`
	PublishedAt  time.Time      `json:"published_at"`
	IsPublished  bool           `json:"is_published"`
	IsFeatured   bool           `json:"is_featured"`
}

func (q *Queries) CreateHotRelease(ctx context.Context, arg CreateHotReleaseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createHotRelease,
		arg.Title,
		arg.Slug,
		arg.Excerpt,
		arg.Content,
		arg.ImageUrl,
		arg.ThumbUrl,
		arg.MiddleImages,
		arg.PublishedAt,
		arg.IsPublished,
		arg.IsFeatured,
	)
}

const createHotReleaseImported = `-- name: CreateHotReleaseImported :execresult
INSERT INTO news_items (source, title, slug, excerpt, content, url, image_url, thumb_url, published_at, is_published, is_featured)
VALUES ('hot_release', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateHotReleaseImportedParams struct {
	Title       string         `json:"title"`
	Slug        sql.NullString `json:"slug"`
	Excerpt     sql.NullString `json:"excerpt"`
	Content     sql.NullString `json:"content"`
	Url         sql.NullString `json:"url"`
	ImageUrl    sql.NullString `json:"image_url"`
	ThumbUrl    sql.NullString `json:"thumb_url"`
	PublishedAt time.Time      `json:"published_at"`
	IsPublished bool           `json:"is_published"`
	IsFeatured  bool           `json:"is_featured"`
}

// Same as CreateHotRelease but also records the source article's URL on the old
// site (classyfm.co.id), used by cmd/importhotrelease to dedupe on re-runs.
func (q *Queries) CreateHotReleaseImported(ctx context.Context, arg CreateHotReleaseImportedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createHotReleaseImported,
		arg.Title,
		arg.Slug,
		arg.Excerpt,
		arg.Content,
		arg.Url,
		arg.ImageUrl,
		arg.ThumbUrl,
		arg.PublishedAt,
		arg.IsPublished,
		arg.IsFeatured,
	)
}

const deleteNewsItem = `-- name: DeleteNewsItem :exec
DELETE FROM news_items WHERE id = ?
`

func (q *Queries) DeleteNewsItem(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteNewsItem, id)
	return err
}

const getNewsItem = `-- name: GetNewsItem :one
SELECT id, source, external_id, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured, created_at, updated_at, thumb_url, middle_images FROM news_items WHERE id = ?
`

func (q *Queries) GetNewsItem(ctx context.Context, id uint64) (NewsItem, error) {
	row := q.db.QueryRowContext(ctx, getNewsItem, id)
	var i NewsItem
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Content,
		&i.Url,
		&i.ImageUrl,
		&i.PublishedAt,
		&i.IsPublished,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbUrl,
		&i.MiddleImages,
	)
	return i, err
}

const getNewsItemBySlug = `-- name: GetNewsItemBySlug :one
SELECT id, source, external_id, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured, created_at, updated_at, thumb_url, middle_images FROM news_items WHERE slug = ?
`

func (q *Queries) GetNewsItemBySlug(ctx context.Context, slug sql.NullString) (NewsItem, error) {
	row := q.db.QueryRowContext(ctx, getNewsItemBySlug, slug)
	var i NewsItem
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Content,
		&i.Url,
		&i.ImageUrl,
		&i.PublishedAt,
		&i.IsPublished,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbUrl,
		&i.MiddleImages,
	)
	return i, err
}

const getNewsItemImages = `-- name: GetNewsItemImages :one
SELECT image_url, thumb_url FROM news_items WHERE source = ? AND external_id = ?
`

type GetNewsItemImagesParams struct {
	Source     NewsItemsSource `json:"source"`
	ExternalID sql.NullString  `json:"external_id"`
}

type GetNewsItemImagesRow struct {
	ImageUrl sql.NullString `json:"image_url"`
	ThumbUrl sql.NullString `json:"thumb_url"`
}

// Used by the feed worker to check what's already stored before overwriting
// image_url/thumb_url on a refresh, so a transient resolution failure can't
// downgrade an already-upgraded image (see feeds.PreferImage).
func (q *Queries) GetNewsItemImages(ctx context.Context, arg GetNewsItemImagesParams) (GetNewsItemImagesRow, error) {
	row := q.db.QueryRowContext(ctx, getNewsItemImages, arg.Source, arg.ExternalID)
	var i GetNewsItemImagesRow
	err := row.Scan(&i.ImageUrl, &i.ThumbUrl)
	return i, err
}

const getPublishedNewsItemBySlug = `-- name: GetPublishedNewsItemBySlug :one
SELECT id, source, external_id, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured, created_at, updated_at, thumb_url, middle_images FROM news_items WHERE slug = ? AND is_published = 1
`

func (q *Queries) GetPublishedNewsItemBySlug(ctx context.Context, slug sql.NullString) (NewsItem, error) {
	row := q.db.QueryRowContext(ctx, getPublishedNewsItemBySlug, slug)
	var i NewsItem
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Content,
		&i.Url,
		&i.ImageUrl,
		&i.PublishedAt,
		&i.IsPublished,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbUrl,
		&i.MiddleImages,
	)
	return i, err
}

const listAggregatedNews = `-- name: ListAggregatedNews :many
SELECT id, source, external_id, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured, created_at, updated_at, thumb_url, middle_images FROM news_items
WHERE source != 'hot_release'
  AND (? = '' OR source = ?)
  AND title LIKE ?
ORDER BY
  CASE WHEN ? = 'title' AND ? = 'asc' THEN title END ASC,
  CASE WHEN ? = 'title' AND ? = 'desc' THEN title END DESC,
  CASE WHEN ? = 'source' AND ? = 'asc' THEN source END ASC,
  CASE WHEN ? = 'source' AND ? = 'desc' THEN source END DESC,
  CASE WHEN ? = 'published_at' AND ? = 'asc' THEN published_at END ASC,
  CASE WHEN ? = 'published_at' AND ? = 'desc' THEN published_at END DESC,
  published_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListAggregatedNewsParams struct {
	Source NewsItemsSource `json:"source"`
	Search string          `json:"search"`
	Sort   interface{}     `json:"sort"`
	Dir    interface{}     `json:"dir"`
	Limit  int32           `json:"limit"`
	Offset int32           `json:"offset"`
}

func (q *Queries) ListAggregatedNews(ctx context.Context, arg ListAggregatedNewsParams) ([]NewsItem, error) {
	rows, err := q.db.QueryContext(ctx, listAggregatedNews,
		arg.Source,
		arg.Source,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsItem{}
	for rows.Next() {
		var i NewsItem
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Content,
			&i.Url,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.IsPublished,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbUrl,
			&i.MiddleImages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllHotRelease = `-- name: ListAllHotRelease :many
SELECT id, source, external_id, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured, created_at, updated_at, thumb_url, middle_images FROM news_items
WHERE source = 'hot_release' AND title LIKE ?
ORDER BY
  CASE WHEN ? = 'title' AND ? = 'asc' THEN title END ASC,
  CASE WHEN ? = 'title' AND ? = 'desc' THEN title END DESC,
  CASE WHEN ? = 'published_at' AND ? = 'asc' THEN published_at END ASC,
  CASE WHEN ? = 'published_at' AND ? = 'desc' THEN published_at END DESC,
  published_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListAllHotReleaseParams struct {
	Search string      `json:"search"`
	Sort   interface{} `json:"sort"`
	Dir    interface{} `json:"dir"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListAllHotRelease(ctx context.Context, arg ListAllHotReleaseParams) ([]NewsItem, error) {
	rows, err := q.db.QueryContext(ctx, listAllHotRelease,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsItem{}
	for rows.Next() {
		var i NewsItem
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Content,
			&i.Url,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.IsPublished,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbUrl,
			&i.MiddleImages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHotRelease = `-- name: ListHotRelease :many
SELECT id, source, external_id, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured, created_at, updated_at, thumb_url, middle_images FROM news_items
WHERE source = 'hot_release' AND is_published = 1
ORDER BY published_at DESC
LIMIT ?
`

func (q *Queries) ListHotRelease(ctx context.Context, limit int32) ([]NewsItem, error) {
	rows, err := q.db.QueryContext(ctx, listHotRelease, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsItem{}
	for rows.Next() {
		var i NewsItem
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Content,
			&i.Url,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.IsPublished,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbUrl,
			&i.MiddleImages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestPublished = `-- name: ListLatestPublished :many
SELECT id, source, external_id, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured, created_at, updated_at, thumb_url, middle_images FROM news_items
WHERE is_published = 1
ORDER BY published_at DESC
LIMIT ?
`

func (q *Queries) ListLatestPublished(ctx context.Context, limit int32) ([]NewsItem, error) {
	rows, err := q.db.QueryContext(ctx, listLatestPublished, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsItem{}
	for rows.Next() {
		var i NewsItem
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Content,
			&i.Url,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.IsPublished,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbUrl,
			&i.MiddleImages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedNews = `-- name: ListPublishedNews :many
SELECT id, source, external_id, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured, created_at, updated_at, thumb_url, middle_images FROM news_items
WHERE is_published = 1
ORDER BY published_at DESC
LIMIT ? OFFSET ?
`

type ListPublishedNewsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublishedNews(ctx context.Context, arg ListPublishedNewsParams) ([]NewsItem, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedNews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsItem{}
	for rows.Next() {
		var i NewsItem
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Content,
			&i.Url,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.IsPublished,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbUrl,
			&i.MiddleImages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedNewsBySource = `-- name: ListPublishedNewsBySource :many
SELECT id, source, external_id, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured, created_at, updated_at, thumb_url, middle_images FROM news_items
WHERE is_published = 1 AND source = ?
ORDER BY published_at DESC
LIMIT ? OFFSET ?
`

type ListPublishedNewsBySourceParams struct {
	Source NewsItemsSource `json:"source"`
	Limit  int32           `json:"limit"`
	Offset int32           `json:"offset"`
}

func (q *Queries) ListPublishedNewsBySource(ctx context.Context, arg ListPublishedNewsBySourceParams) ([]NewsItem, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedNewsBySource, arg.Source, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsItem{}
	for rows.Next() {
		var i NewsItem
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Content,
			&i.Url,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.IsPublished,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbUrl,
			&i.MiddleImages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentNewsArrivals = `-- name: ListRecentNewsArrivals :many
SELECT source, created_at FROM news_items
WHERE source <> 'hot_release' AND created_at >= ?
ORDER BY created_at
`

type ListRecentNewsArrivalsRow struct {
	Source    NewsItemsSource `json:"source"`
	CreatedAt time.Time       `json:"created_at"`
}

// Raw arrival timestamps for the dashboard's ingest chart, bucketed into days by the
// caller. Deliberately not a GROUP BY DATE(created_at): that buckets by whatever
// timezone the MySQL session runs in - the host's - while the chart has to read in the
// station's (Asia/Jakarta). Grouping in Go against schedule.Loc is correct by
// construction, and two weeks of two columns is a few hundred rows.
// hot_release is excluded because those rows arrive in one historical import (a
// thousand-plus on a single day), which would flatten every real day to nothing.
func (q *Queries) ListRecentNewsArrivals(ctx context.Context, since time.Time) ([]ListRecentNewsArrivalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentNewsArrivals, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentNewsArrivalsRow{}
	for rows.Next() {
		var i ListRecentNewsArrivalsRow
		if err := rows.Scan(&i.Source, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newsStatsBySource = `-- name: NewsStatsBySource :many
SELECT source,
       COUNT(*) AS total,
       CAST(SUM(is_published = 1) AS SIGNED) AS published,
       CAST(SUM(created_at >= ?) AS SIGNED) AS recent,
       CAST(MAX(published_at) AS DATETIME) AS latest_published_at
FROM news_items
GROUP BY source
`

type NewsStatsBySourceRow struct {
	Source            NewsItemsSource `json:"source"`
	Total             int64           `json:"total"`
	Published         int64           `json:"published"`
	Recent            int64           `json:"recent"`
	LatestPublishedAt time.Time       `json:"latest_published_at"`
}

// One row per news source for the admin dashboard: how many items exist, how many
// are published (the rest are the newsfeed review queue), how many arrived since
// `since`, and when the newest published one was dated. latest_published_at is the
// real staleness signal - feed_sources.last_fetched_at only says the worker ran,
// not that anything new came back.
//
// Every CAST here is load-bearing, same family of trap as the scalar subqueries in
// programs.sql: a bare SUM() is DECIMAL and a bare MAX() of a DATETIME is untyped as
// far as sqlc is concerned, and both come back as interface{} instead of a number /
// time.Time. CAST(... AS SIGNED) and CAST(... AS DATETIME) pin them down. The
// DATETIME cast can't produce a NULL that breaks the time.Time scan: published_at is
// NOT NULL and GROUP BY never yields an empty group.
func (q *Queries) NewsStatsBySource(ctx context.Context, since time.Time) ([]NewsStatsBySourceRow, error) {
	rows, err := q.db.QueryContext(ctx, newsStatsBySource, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsStatsBySourceRow{}
	for rows.Next() {
		var i NewsStatsBySourceRow
		if err := rows.Scan(
			&i.Source,
			&i.Total,
			&i.Published,
			&i.Recent,
			&i.LatestPublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNewsItemFeatured = `-- name: SetNewsItemFeatured :exec
UPDATE news_items SET is_featured = ? WHERE id = ?
`

type SetNewsItemFeaturedParams struct {
	IsFeatured bool   `json:"is_featured"`
	ID         uint64 `json:"id"`
}

func (q *Queries) SetNewsItemFeatured(ctx context.Context, arg SetNewsItemFeaturedParams) error {
	_, err := q.db.ExecContext(ctx, setNewsItemFeatured, arg.IsFeatured, arg.ID)
	return err
}

const setNewsItemPublished = `-- name: SetNewsItemPublished :exec
UPDATE news_items SET is_published = ? WHERE id = ?
`

type SetNewsItemPublishedParams struct {
	IsPublished bool   `json:"is_published"`
	ID          uint64 `json:"id"`
}

func (q *Queries) SetNewsItemPublished(ctx context.Context, arg SetNewsItemPublishedParams) error {
	_, err := q.db.ExecContext(ctx, setNewsItemPublished, arg.IsPublished, arg.ID)
	return err
}

const unfeatureOthersBySource = `-- name: UnfeatureOthersBySource :exec
UPDATE news_items SET is_featured = 0 WHERE source = ? AND id <> ?
`

type UnfeatureOthersBySourceParams struct {
	Source NewsItemsSource `json:"source"`
	ID     uint64          `json:"id"`
}

func (q *Queries) UnfeatureOthersBySource(ctx context.Context, arg UnfeatureOthersBySourceParams) error {
	_, err := q.db.ExecContext(ctx, unfeatureOthersBySource, arg.Source, arg.ID)
	return err
}

const updateHotRelease = `-- name: UpdateHotRelease :exec
UPDATE news_items
SET title = ?, slug = ?, excerpt = ?, content = ?, image_url = ?, thumb_url = ?, middle_images = ?, published_at = ?, is_published = ?, is_featured = ?
WHERE id = ? AND source = 'hot_release'
`

type UpdateHotReleaseParams struct {
	Title        string         `json:"title"`
	Slug         sql.NullString `json:"slug"`
	Excerpt      sql.NullString `json:"excerpt"`
	Content      sql.NullString `json:"content"`
	ImageUrl     sql.NullString `json:"image_url"`
	ThumbUrl     sql.NullString `json:"thumb_url"`
	MiddleImages sql.NullString `json:"middle_images"`
	PublishedAt  time.Time      `json:"published_at"`
	IsPublished  bool           `json:"is_published"`
	IsFeatured   bool           `json:"is_featured"`
	ID           uint64         `json:"id"`
}

func (q *Queries) UpdateHotRelease(ctx context.Context, arg UpdateHotReleaseParams) error {
	_, err := q.db.ExecContext(ctx, updateHotRelease,
		arg.Title,
		arg.Slug,
		arg.Excerpt,
		arg.Content,
		arg.ImageUrl,
		arg.ThumbUrl,
		arg.MiddleImages,
		arg.PublishedAt,
		arg.IsPublished,
		arg.IsFeatured,
		arg.ID,
	)
	return err
}

const updateNewsItemImages = `-- name: UpdateNewsItemImages :exec
UPDATE news_items SET image_url = ?, thumb_url = ? WHERE id = ?
`

type UpdateNewsItemImagesParams struct {
	ImageUrl sql.NullString `json:"image_url"`
	ThumbUrl sql.NullString `json:"thumb_url"`
	ID       uint64         `json:"id"`
}

// Used by one-off backfill tools (e.g. cmd/upgradeimages) to swap in a
// higher-resolution image (and/or its list-sized thumbnail) for an
// already-aggregated item without touching anything else about the row.
func (q *Queries) UpdateNewsItemImages(ctx context.Context, arg UpdateNewsItemImagesParams) error {
	_, err := q.db.ExecContext(ctx, updateNewsItemImages, arg.ImageUrl, arg.ThumbUrl, arg.ID)
	return err
}

const upsertNewsItem = `-- name: UpsertNewsItem :exec
INSERT INTO news_items (source, external_id, title, excerpt, url, image_url, thumb_url, published_at, is_published)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1)
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  excerpt = VALUES(excerpt),
  url = VALUES(url),
  image_url = VALUES(image_url),
  thumb_url = VALUES(thumb_url),
  published_at = VALUES(published_at)
`

type UpsertNewsItemParams struct {
	Source      NewsItemsSource `json:"source"`
	ExternalID  sql.NullString  `json:"external_id"`
	Title       string          `json:"title"`
	Excerpt     sql.NullString  `json:"excerpt"`
	Url         sql.NullString  `json:"url"`
	ImageUrl    sql.NullString  `json:"image_url"`
	ThumbUrl    sql.NullString  `json:"thumb_url"`
	PublishedAt time.Time       `json:"published_at"`
}

// Inserts a new aggregated item as published, or refreshes content fields on an
// existing one. is_published/is_featured are intentionally left untouched on
// conflict so an admin's publish/feature decision survives the next fetch.
func (q *Queries) UpsertNewsItem(ctx context.Context, arg UpsertNewsItemParams) error {
	_, err := q.db.ExecContext(ctx, upsertNewsItem,
		arg.Source,
		arg.ExternalID,
		arg.Title,
		arg.Excerpt,
		arg.Url,
		arg.ImageUrl,
		arg.ThumbUrl,
		arg.PublishedAt,
	)
	return err
}
