// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: news.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countAggregatedNews = `-- name: CountAggregatedNews :one
SELECT COUNT(*) FROM news_items
WHERE source != 'hot_release'
  AND (? = '' OR source = ?)
  AND title LIKE ?
`

type CountAggregatedNewsParams struct {
	Source NewsItemsSource `json:"source"`
	Search string          `json:"search"`
}

func (q *Queries) CountAggregatedNews(ctx context.Context, arg CountAggregatedNewsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAggregatedNews, arg.Source, arg.Source, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllHotRelease = `-- name: CountAllHotRelease :one
SELECT COUNT(*) FROM news_items WHERE source = 'hot_release' AND title LIKE ?
`

func (q *Queries) CountAllHotRelease(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllHotRelease, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedNews = `-- name: CountPublishedNews :one
SELECT COUNT(*) FROM news_items WHERE is_published = 1
`

func (q *Queries) CountPublishedNews(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedNews)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedNewsBySource = `-- name: CountPublishedNewsBySource :one
SELECT COUNT(*) FROM news_items WHERE is_published = 1 AND source = ?
`

func (q *Queries) CountPublishedNewsBySource(ctx context.Context, source NewsItemsSource) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedNewsBySource, source)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHotRelease = `-- name: CreateHotRelease :execresult
INSERT INTO news_items (source, title, slug, excerpt, content, image_url, published_at, is_published, is_featured)
VALUES ('hot_release', ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateHotReleaseParams struct {
	Title       string         `json:"title"`
	Slug        sql.NullString `json:"slug"`
	Excerpt     sql.NullString `json:"excerpt"`
	Content     sql.NullString `json:"content"`
	ImageUrl    sql.NullString `json:"image_url"`
	PublishedAt time.Time      `json:"published_at"`
	IsPublished bool           `json:"is_published"`
	IsFeatured  bool           `json:"is_featured"`
}

func (q *Queries) CreateHotRelease(ctx context.Context, arg CreateHotReleaseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createHotRelease,
		arg.Title,
		arg.Slug,
		arg.Excerpt,
		arg.Content,
		arg.ImageUrl,
		arg.PublishedAt,
		arg.IsPublished,
		arg.IsFeatured,
	)
}

const createHotReleaseImported = `-- name: CreateHotReleaseImported :execresult
INSERT INTO news_items (source, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured)
VALUES ('hot_release', ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateHotReleaseImportedParams struct {
	Title       string         `json:"title"`
	Slug        sql.NullString `json:"slug"`
	Excerpt     sql.NullString `json:"excerpt"`
	Content     sql.NullString `json:"content"`
	Url         sql.NullString `json:"url"`
	ImageUrl    sql.NullString `json:"image_url"`
	PublishedAt time.Time      `json:"published_at"`
	IsPublished bool           `json:"is_published"`
	IsFeatured  bool           `json:"is_featured"`
}

// Same as CreateHotRelease but also records the source article's URL on the old
// site (classyfm.co.id), used by cmd/importhotrelease to dedupe on re-runs.
func (q *Queries) CreateHotReleaseImported(ctx context.Context, arg CreateHotReleaseImportedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createHotReleaseImported,
		arg.Title,
		arg.Slug,
		arg.Excerpt,
		arg.Content,
		arg.Url,
		arg.ImageUrl,
		arg.PublishedAt,
		arg.IsPublished,
		arg.IsFeatured,
	)
}

const deleteNewsItem = `-- name: DeleteNewsItem :exec
DELETE FROM news_items WHERE id = ?
`

func (q *Queries) DeleteNewsItem(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteNewsItem, id)
	return err
}

const getNewsItem = `-- name: GetNewsItem :one
SELECT id, source, external_id, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured, created_at, updated_at FROM news_items WHERE id = ?
`

func (q *Queries) GetNewsItem(ctx context.Context, id uint64) (NewsItem, error) {
	row := q.db.QueryRowContext(ctx, getNewsItem, id)
	var i NewsItem
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Content,
		&i.Url,
		&i.ImageUrl,
		&i.PublishedAt,
		&i.IsPublished,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedNewsItemBySlug = `-- name: GetPublishedNewsItemBySlug :one
SELECT id, source, external_id, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured, created_at, updated_at FROM news_items WHERE slug = ? AND is_published = 1
`

func (q *Queries) GetPublishedNewsItemBySlug(ctx context.Context, slug sql.NullString) (NewsItem, error) {
	row := q.db.QueryRowContext(ctx, getPublishedNewsItemBySlug, slug)
	var i NewsItem
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Content,
		&i.Url,
		&i.ImageUrl,
		&i.PublishedAt,
		&i.IsPublished,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAggregatedNews = `-- name: ListAggregatedNews :many
SELECT id, source, external_id, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured, created_at, updated_at FROM news_items
WHERE source != 'hot_release'
  AND (? = '' OR source = ?)
  AND title LIKE ?
ORDER BY
  CASE WHEN ? = 'title' AND ? = 'asc' THEN title END ASC,
  CASE WHEN ? = 'title' AND ? = 'desc' THEN title END DESC,
  CASE WHEN ? = 'source' AND ? = 'asc' THEN source END ASC,
  CASE WHEN ? = 'source' AND ? = 'desc' THEN source END DESC,
  CASE WHEN ? = 'published_at' AND ? = 'asc' THEN published_at END ASC,
  CASE WHEN ? = 'published_at' AND ? = 'desc' THEN published_at END DESC,
  published_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListAggregatedNewsParams struct {
	Source NewsItemsSource `json:"source"`
	Search string          `json:"search"`
	Sort   interface{}     `json:"sort"`
	Dir    interface{}     `json:"dir"`
	Limit  int32           `json:"limit"`
	Offset int32           `json:"offset"`
}

func (q *Queries) ListAggregatedNews(ctx context.Context, arg ListAggregatedNewsParams) ([]NewsItem, error) {
	rows, err := q.db.QueryContext(ctx, listAggregatedNews,
		arg.Source,
		arg.Source,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsItem{}
	for rows.Next() {
		var i NewsItem
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Content,
			&i.Url,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.IsPublished,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllHotRelease = `-- name: ListAllHotRelease :many
SELECT id, source, external_id, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured, created_at, updated_at FROM news_items
WHERE source = 'hot_release' AND title LIKE ?
ORDER BY
  CASE WHEN ? = 'title' AND ? = 'asc' THEN title END ASC,
  CASE WHEN ? = 'title' AND ? = 'desc' THEN title END DESC,
  CASE WHEN ? = 'published_at' AND ? = 'asc' THEN published_at END ASC,
  CASE WHEN ? = 'published_at' AND ? = 'desc' THEN published_at END DESC,
  published_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListAllHotReleaseParams struct {
	Search string      `json:"search"`
	Sort   interface{} `json:"sort"`
	Dir    interface{} `json:"dir"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListAllHotRelease(ctx context.Context, arg ListAllHotReleaseParams) ([]NewsItem, error) {
	rows, err := q.db.QueryContext(ctx, listAllHotRelease,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsItem{}
	for rows.Next() {
		var i NewsItem
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Content,
			&i.Url,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.IsPublished,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHotRelease = `-- name: ListHotRelease :many
SELECT id, source, external_id, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured, created_at, updated_at FROM news_items
WHERE source = 'hot_release' AND is_published = 1
ORDER BY published_at DESC
LIMIT ?
`

func (q *Queries) ListHotRelease(ctx context.Context, limit int32) ([]NewsItem, error) {
	rows, err := q.db.QueryContext(ctx, listHotRelease, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsItem{}
	for rows.Next() {
		var i NewsItem
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Content,
			&i.Url,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.IsPublished,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestPublished = `-- name: ListLatestPublished :many
SELECT id, source, external_id, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured, created_at, updated_at FROM news_items
WHERE is_published = 1
ORDER BY published_at DESC
LIMIT ?
`

func (q *Queries) ListLatestPublished(ctx context.Context, limit int32) ([]NewsItem, error) {
	rows, err := q.db.QueryContext(ctx, listLatestPublished, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsItem{}
	for rows.Next() {
		var i NewsItem
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Content,
			&i.Url,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.IsPublished,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedNews = `-- name: ListPublishedNews :many
SELECT id, source, external_id, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured, created_at, updated_at FROM news_items
WHERE is_published = 1
ORDER BY published_at DESC
LIMIT ? OFFSET ?
`

type ListPublishedNewsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublishedNews(ctx context.Context, arg ListPublishedNewsParams) ([]NewsItem, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedNews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsItem{}
	for rows.Next() {
		var i NewsItem
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Content,
			&i.Url,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.IsPublished,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedNewsBySource = `-- name: ListPublishedNewsBySource :many
SELECT id, source, external_id, title, slug, excerpt, content, url, image_url, published_at, is_published, is_featured, created_at, updated_at FROM news_items
WHERE is_published = 1 AND source = ?
ORDER BY published_at DESC
LIMIT ? OFFSET ?
`

type ListPublishedNewsBySourceParams struct {
	Source NewsItemsSource `json:"source"`
	Limit  int32           `json:"limit"`
	Offset int32           `json:"offset"`
}

func (q *Queries) ListPublishedNewsBySource(ctx context.Context, arg ListPublishedNewsBySourceParams) ([]NewsItem, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedNewsBySource, arg.Source, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsItem{}
	for rows.Next() {
		var i NewsItem
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Content,
			&i.Url,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.IsPublished,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNewsItemFeatured = `-- name: SetNewsItemFeatured :exec
UPDATE news_items SET is_featured = ? WHERE id = ?
`

type SetNewsItemFeaturedParams struct {
	IsFeatured bool   `json:"is_featured"`
	ID         uint64 `json:"id"`
}

func (q *Queries) SetNewsItemFeatured(ctx context.Context, arg SetNewsItemFeaturedParams) error {
	_, err := q.db.ExecContext(ctx, setNewsItemFeatured, arg.IsFeatured, arg.ID)
	return err
}

const setNewsItemPublished = `-- name: SetNewsItemPublished :exec
UPDATE news_items SET is_published = ? WHERE id = ?
`

type SetNewsItemPublishedParams struct {
	IsPublished bool   `json:"is_published"`
	ID          uint64 `json:"id"`
}

func (q *Queries) SetNewsItemPublished(ctx context.Context, arg SetNewsItemPublishedParams) error {
	_, err := q.db.ExecContext(ctx, setNewsItemPublished, arg.IsPublished, arg.ID)
	return err
}

const updateHotRelease = `-- name: UpdateHotRelease :exec
UPDATE news_items
SET title = ?, slug = ?, excerpt = ?, content = ?, image_url = ?, published_at = ?, is_published = ?, is_featured = ?
WHERE id = ? AND source = 'hot_release'
`

type UpdateHotReleaseParams struct {
	Title       string         `json:"title"`
	Slug        sql.NullString `json:"slug"`
	Excerpt     sql.NullString `json:"excerpt"`
	Content     sql.NullString `json:"content"`
	ImageUrl    sql.NullString `json:"image_url"`
	PublishedAt time.Time      `json:"published_at"`
	IsPublished bool           `json:"is_published"`
	IsFeatured  bool           `json:"is_featured"`
	ID          uint64         `json:"id"`
}

func (q *Queries) UpdateHotRelease(ctx context.Context, arg UpdateHotReleaseParams) error {
	_, err := q.db.ExecContext(ctx, updateHotRelease,
		arg.Title,
		arg.Slug,
		arg.Excerpt,
		arg.Content,
		arg.ImageUrl,
		arg.PublishedAt,
		arg.IsPublished,
		arg.IsFeatured,
		arg.ID,
	)
	return err
}

const upsertNewsItem = `-- name: UpsertNewsItem :exec
INSERT INTO news_items (source, external_id, title, excerpt, url, image_url, published_at, is_published)
VALUES (?, ?, ?, ?, ?, ?, ?, 1)
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  excerpt = VALUES(excerpt),
  url = VALUES(url),
  image_url = VALUES(image_url),
  published_at = VALUES(published_at)
`

type UpsertNewsItemParams struct {
	Source      NewsItemsSource `json:"source"`
	ExternalID  sql.NullString  `json:"external_id"`
	Title       string          `json:"title"`
	Excerpt     sql.NullString  `json:"excerpt"`
	Url         sql.NullString  `json:"url"`
	ImageUrl    sql.NullString  `json:"image_url"`
	PublishedAt time.Time       `json:"published_at"`
}

// Inserts a new aggregated item as published, or refreshes content fields on an
// existing one. is_published/is_featured are intentionally left untouched on
// conflict so an admin's publish/feature decision survives the next fetch.
func (q *Queries) UpsertNewsItem(ctx context.Context, arg UpsertNewsItemParams) error {
	_, err := q.db.ExecContext(ctx, upsertNewsItem,
		arg.Source,
		arg.ExternalID,
		arg.Title,
		arg.Excerpt,
		arg.Url,
		arg.ImageUrl,
		arg.PublishedAt,
	)
	return err
}
