// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: podcasts.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const addPodcastBroadcaster = `-- name: AddPodcastBroadcaster :exec
INSERT INTO podcast_broadcasters (podcast_id, broadcaster_id) VALUES (?, ?)
`

type AddPodcastBroadcasterParams struct {
	PodcastID     uint64 `json:"podcast_id"`
	BroadcasterID uint64 `json:"broadcaster_id"`
}

func (q *Queries) AddPodcastBroadcaster(ctx context.Context, arg AddPodcastBroadcasterParams) error {
	_, err := q.db.ExecContext(ctx, addPodcastBroadcaster, arg.PodcastID, arg.BroadcasterID)
	return err
}

const clearPodcastBroadcasters = `-- name: ClearPodcastBroadcasters :exec
DELETE FROM podcast_broadcasters WHERE podcast_id = ?
`

func (q *Queries) ClearPodcastBroadcasters(ctx context.Context, podcastID uint64) error {
	_, err := q.db.ExecContext(ctx, clearPodcastBroadcasters, podcastID)
	return err
}

const countPodcasts = `-- name: CountPodcasts :one
SELECT COUNT(*) FROM podcasts WHERE title LIKE ?
`

func (q *Queries) CountPodcasts(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPodcasts, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedPodcasts = `-- name: CountPublishedPodcasts :one
SELECT COUNT(*) FROM podcasts p
JOIN podcast_series s ON s.id = p.series_id
WHERE p.is_published = 1 AND s.is_active = 1
`

func (q *Queries) CountPublishedPodcasts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedPodcasts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedPodcastsBySeriesSlug = `-- name: CountPublishedPodcastsBySeriesSlug :one
SELECT COUNT(*) FROM podcasts p
JOIN podcast_series s ON s.id = p.series_id
WHERE p.is_published = 1 AND s.is_active = 1 AND s.slug = ?
`

func (q *Queries) CountPublishedPodcastsBySeriesSlug(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedPodcastsBySeriesSlug, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPodcast = `-- name: CreatePodcast :execresult
INSERT INTO podcasts (title, slug, series_id, description, spotify_url, thumb_url, is_published)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreatePodcastParams struct {
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	SeriesID    uint64         `json:"series_id"`
	Description string         `json:"description"`
	SpotifyUrl  string         `json:"spotify_url"`
	ThumbUrl    sql.NullString `json:"thumb_url"`
	IsPublished bool           `json:"is_published"`
}

func (q *Queries) CreatePodcast(ctx context.Context, arg CreatePodcastParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPodcast,
		arg.Title,
		arg.Slug,
		arg.SeriesID,
		arg.Description,
		arg.SpotifyUrl,
		arg.ThumbUrl,
		arg.IsPublished,
	)
}

const deletePodcast = `-- name: DeletePodcast :exec
DELETE FROM podcasts WHERE id = ?
`

func (q *Queries) DeletePodcast(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deletePodcast, id)
	return err
}

const getPodcast = `-- name: GetPodcast :one
SELECT id, title, slug, description, spotify_url, thumb_url, is_published, created_at, updated_at, series_id FROM podcasts WHERE id = ?
`

func (q *Queries) GetPodcast(ctx context.Context, id uint64) (Podcast, error) {
	row := q.db.QueryRowContext(ctx, getPodcast, id)
	var i Podcast
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.SpotifyUrl,
		&i.ThumbUrl,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SeriesID,
	)
	return i, err
}

const getPodcastBySlug = `-- name: GetPodcastBySlug :one
SELECT id, title, slug, description, spotify_url, thumb_url, is_published, created_at, updated_at, series_id FROM podcasts WHERE slug = ?
`

func (q *Queries) GetPodcastBySlug(ctx context.Context, slug string) (Podcast, error) {
	row := q.db.QueryRowContext(ctx, getPodcastBySlug, slug)
	var i Podcast
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.SpotifyUrl,
		&i.ThumbUrl,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SeriesID,
	)
	return i, err
}

const getPublishedPodcastBySlug = `-- name: GetPublishedPodcastBySlug :one
SELECT p.id, p.title, p.slug, p.description, p.spotify_url, p.thumb_url, p.is_published, p.created_at, p.updated_at, p.series_id FROM podcasts p
JOIN podcast_series s ON s.id = p.series_id
WHERE p.slug = ? AND p.is_published = 1 AND s.is_active = 1
`

func (q *Queries) GetPublishedPodcastBySlug(ctx context.Context, slug string) (Podcast, error) {
	row := q.db.QueryRowContext(ctx, getPublishedPodcastBySlug, slug)
	var i Podcast
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.SpotifyUrl,
		&i.ThumbUrl,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SeriesID,
	)
	return i, err
}

const listPodcastBroadcasters = `-- name: ListPodcastBroadcasters :many

SELECT b.id, b.name, b.slug, b.role, b.photo_url, b.bio, b.birth_place, b.birth_date, b.instagram, b.twitter, b.facebook, b.sort_order, b.is_active, b.created_at, b.updated_at FROM podcast_broadcasters pb
JOIN broadcasters b ON b.id = pb.broadcaster_id
WHERE pb.podcast_id = ?
ORDER BY b.sort_order ASC, b.name ASC
`

// Broadcaster assignments are written clear-then-insert, so there is no update query;
// the junction rows go away with their parent via ON DELETE CASCADE.
func (q *Queries) ListPodcastBroadcasters(ctx context.Context, podcastID uint64) ([]Broadcaster, error) {
	rows, err := q.db.QueryContext(ctx, listPodcastBroadcasters, podcastID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Broadcaster{}
	for rows.Next() {
		var i Broadcaster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.PhotoUrl,
			&i.Bio,
			&i.BirthPlace,
			&i.BirthDate,
			&i.Instagram,
			&i.Twitter,
			&i.Facebook,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPodcasts = `-- name: ListPodcasts :many
SELECT p.id, p.title, p.slug, p.description, p.spotify_url, p.thumb_url, p.is_published, p.created_at, p.updated_at, p.series_id,
  s.name AS series_name, s.slug AS series_slug,
  (SELECT GROUP_CONCAT(b.name ORDER BY b.sort_order, b.name SEPARATOR ', ')
     FROM broadcasters b
     JOIN podcast_broadcasters pb ON pb.broadcaster_id = b.id
    WHERE pb.podcast_id = p.id) AS broadcaster_name
FROM podcasts p
JOIN podcast_series s ON s.id = p.series_id
WHERE p.title LIKE ?
ORDER BY
  CASE WHEN ? = 'title' AND ? = 'asc' THEN p.title END ASC,
  CASE WHEN ? = 'title' AND ? = 'desc' THEN p.title END DESC,
  CASE WHEN ? = 'created_at' AND ? = 'asc' THEN p.created_at END ASC,
  CASE WHEN ? = 'created_at' AND ? = 'desc' THEN p.created_at END DESC,
  p.created_at DESC, p.id DESC
LIMIT ? OFFSET ?
`

type ListPodcastsParams struct {
	Search string      `json:"search"`
	Sort   interface{} `json:"sort"`
	Dir    interface{} `json:"dir"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListPodcastsRow struct {
	ID              uint64         `json:"id"`
	Title           string         `json:"title"`
	Slug            string         `json:"slug"`
	Description     string         `json:"description"`
	SpotifyUrl      string         `json:"spotify_url"`
	ThumbUrl        sql.NullString `json:"thumb_url"`
	IsPublished     bool           `json:"is_published"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	SeriesID        uint64         `json:"series_id"`
	SeriesName      string         `json:"series_name"`
	SeriesSlug      string         `json:"series_slug"`
	BroadcasterName sql.NullString `json:"broadcaster_name"`
}

func (q *Queries) ListPodcasts(ctx context.Context, arg ListPodcastsParams) ([]ListPodcastsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPodcasts,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPodcastsRow{}
	for rows.Next() {
		var i ListPodcastsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.SpotifyUrl,
			&i.ThumbUrl,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SeriesID,
			&i.SeriesName,
			&i.SeriesSlug,
			&i.BroadcasterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPodcasts = `-- name: ListPublishedPodcasts :many

SELECT p.id, p.title, p.slug, p.description, p.spotify_url, p.thumb_url, p.is_published, p.created_at, p.updated_at, p.series_id,
  s.name AS series_name, s.slug AS series_slug,
  (SELECT GROUP_CONCAT(b.name ORDER BY b.sort_order, b.name SEPARATOR ', ')
     FROM broadcasters b
     JOIN podcast_broadcasters pb ON pb.broadcaster_id = b.id
    WHERE pb.podcast_id = p.id) AS broadcaster_name
FROM podcasts p
JOIN podcast_series s ON s.id = p.series_id
WHERE p.is_published = 1 AND s.is_active = 1
ORDER BY p.created_at DESC, p.id DESC
LIMIT ? OFFSET ?
`

type ListPublishedPodcastsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPublishedPodcastsRow struct {
	ID              uint64         `json:"id"`
	Title           string         `json:"title"`
	Slug            string         `json:"slug"`
	Description     string         `json:"description"`
	SpotifyUrl      string         `json:"spotify_url"`
	ThumbUrl        sql.NullString `json:"thumb_url"`
	IsPublished     bool           `json:"is_published"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	SeriesID        uint64         `json:"series_id"`
	SeriesName      string         `json:"series_name"`
	SeriesSlug      string         `json:"series_slug"`
	BroadcasterName sql.NullString `json:"broadcaster_name"`
}

// broadcaster_name is the podcast's broadcaster set joined as "Anda, Yeni". Every
// consumer treats it as one display string, so the join happens here. It has to be a
// single scalar GROUP_CONCAT subquery, not a COALESCE of two: sqlc types a lone
// GROUP_CONCAT subquery as sql.NullString, but wrapping it in COALESCE defeats its
// inference and the field lands as interface{}. See the same note in programs.sql.
func (q *Queries) ListPublishedPodcasts(ctx context.Context, arg ListPublishedPodcastsParams) ([]ListPublishedPodcastsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedPodcasts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedPodcastsRow{}
	for rows.Next() {
		var i ListPublishedPodcastsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.SpotifyUrl,
			&i.ThumbUrl,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SeriesID,
			&i.SeriesName,
			&i.SeriesSlug,
			&i.BroadcasterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPodcastsBySeriesSlug = `-- name: ListPublishedPodcastsBySeriesSlug :many
SELECT p.id, p.title, p.slug, p.description, p.spotify_url, p.thumb_url, p.is_published, p.created_at, p.updated_at, p.series_id,
  s.name AS series_name, s.slug AS series_slug,
  (SELECT GROUP_CONCAT(b.name ORDER BY b.sort_order, b.name SEPARATOR ', ')
     FROM broadcasters b
     JOIN podcast_broadcasters pb ON pb.broadcaster_id = b.id
    WHERE pb.podcast_id = p.id) AS broadcaster_name
FROM podcasts p
JOIN podcast_series s ON s.id = p.series_id
WHERE p.is_published = 1 AND s.is_active = 1 AND s.slug = ?
ORDER BY p.created_at DESC, p.id DESC
LIMIT ? OFFSET ?
`

type ListPublishedPodcastsBySeriesSlugParams struct {
	Slug   string `json:"slug"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListPublishedPodcastsBySeriesSlugRow struct {
	ID              uint64         `json:"id"`
	Title           string         `json:"title"`
	Slug            string         `json:"slug"`
	Description     string         `json:"description"`
	SpotifyUrl      string         `json:"spotify_url"`
	ThumbUrl        sql.NullString `json:"thumb_url"`
	IsPublished     bool           `json:"is_published"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	SeriesID        uint64         `json:"series_id"`
	SeriesName      string         `json:"series_name"`
	SeriesSlug      string         `json:"series_slug"`
	BroadcasterName sql.NullString `json:"broadcaster_name"`
}

func (q *Queries) ListPublishedPodcastsBySeriesSlug(ctx context.Context, arg ListPublishedPodcastsBySeriesSlugParams) ([]ListPublishedPodcastsBySeriesSlugRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedPodcastsBySeriesSlug, arg.Slug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedPodcastsBySeriesSlugRow{}
	for rows.Next() {
		var i ListPublishedPodcastsBySeriesSlugRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.SpotifyUrl,
			&i.ThumbUrl,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SeriesID,
			&i.SeriesName,
			&i.SeriesSlug,
			&i.BroadcasterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPodcastCreatedAt = `-- name: SetPodcastCreatedAt :exec
UPDATE podcasts SET created_at = ? WHERE id = ?
`

type SetPodcastCreatedAtParams struct {
	CreatedAt time.Time `json:"created_at"`
	ID        uint64    `json:"id"`
}

// SetPodcastCreatedAt lets the legacy importer (cmd/importpodcasts) preserve each
// episode's original publish date, so the catalog's created_at DESC ordering reflects
// real chronology instead of the single moment of import.
func (q *Queries) SetPodcastCreatedAt(ctx context.Context, arg SetPodcastCreatedAtParams) error {
	_, err := q.db.ExecContext(ctx, setPodcastCreatedAt, arg.CreatedAt, arg.ID)
	return err
}

const setPodcastDescription = `-- name: SetPodcastDescription :exec
UPDATE podcasts SET description = ? WHERE id = ?
`

type SetPodcastDescriptionParams struct {
	Description string `json:"description"`
	ID          uint64 `json:"id"`
}

// SetPodcastDescription updates only the description, leaving every other column
// untouched. Used by cmd/backfillpodcastdescriptions to fill descriptions for podcasts
// imported before the Spotify auto-fetch existed, without disturbing their other fields.
func (q *Queries) SetPodcastDescription(ctx context.Context, arg SetPodcastDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, setPodcastDescription, arg.Description, arg.ID)
	return err
}

const setPodcastPublished = `-- name: SetPodcastPublished :exec
UPDATE podcasts SET is_published = ? WHERE id = ?
`

type SetPodcastPublishedParams struct {
	IsPublished bool   `json:"is_published"`
	ID          uint64 `json:"id"`
}

func (q *Queries) SetPodcastPublished(ctx context.Context, arg SetPodcastPublishedParams) error {
	_, err := q.db.ExecContext(ctx, setPodcastPublished, arg.IsPublished, arg.ID)
	return err
}

const updatePodcast = `-- name: UpdatePodcast :exec
UPDATE podcasts
SET title = ?, slug = ?, series_id = ?, description = ?, spotify_url = ?, thumb_url = ?, is_published = ?
WHERE id = ?
`

type UpdatePodcastParams struct {
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	SeriesID    uint64         `json:"series_id"`
	Description string         `json:"description"`
	SpotifyUrl  string         `json:"spotify_url"`
	ThumbUrl    sql.NullString `json:"thumb_url"`
	IsPublished bool           `json:"is_published"`
	ID          uint64         `json:"id"`
}

func (q *Queries) UpdatePodcast(ctx context.Context, arg UpdatePodcastParams) error {
	_, err := q.db.ExecContext(ctx, updatePodcast,
		arg.Title,
		arg.Slug,
		arg.SeriesID,
		arg.Description,
		arg.SpotifyUrl,
		arg.ThumbUrl,
		arg.IsPublished,
		arg.ID,
	)
	return err
}
