// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: podcast_series.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createPodcastSeries = `-- name: CreatePodcastSeries :execresult
INSERT INTO podcast_series (name, slug, sort_order, is_active) VALUES (?, ?, ?, ?)
`

type CreatePodcastSeriesParams struct {
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	SortOrder int32  `json:"sort_order"`
	IsActive  bool   `json:"is_active"`
}

func (q *Queries) CreatePodcastSeries(ctx context.Context, arg CreatePodcastSeriesParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPodcastSeries,
		arg.Name,
		arg.Slug,
		arg.SortOrder,
		arg.IsActive,
	)
}

const deletePodcastSeries = `-- name: DeletePodcastSeries :exec
DELETE FROM podcast_series WHERE id = ?
`

func (q *Queries) DeletePodcastSeries(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deletePodcastSeries, id)
	return err
}

const getPodcastSeries = `-- name: GetPodcastSeries :one
SELECT id, name, slug, sort_order, created_at, updated_at, is_active FROM podcast_series WHERE id = ?
`

func (q *Queries) GetPodcastSeries(ctx context.Context, id uint64) (PodcastSeries, error) {
	row := q.db.QueryRowContext(ctx, getPodcastSeries, id)
	var i PodcastSeries
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const getPodcastSeriesBySlug = `-- name: GetPodcastSeriesBySlug :one
SELECT id, name, slug, sort_order, created_at, updated_at, is_active FROM podcast_series WHERE slug = ?
`

func (q *Queries) GetPodcastSeriesBySlug(ctx context.Context, slug string) (PodcastSeries, error) {
	row := q.db.QueryRowContext(ctx, getPodcastSeriesBySlug, slug)
	var i PodcastSeries
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const listActivePodcastSeries = `-- name: ListActivePodcastSeries :many
SELECT id, name, slug, sort_order, created_at, updated_at, is_active FROM podcast_series
WHERE is_active = 1
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListActivePodcastSeries(ctx context.Context) ([]PodcastSeries, error) {
	rows, err := q.db.QueryContext(ctx, listActivePodcastSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PodcastSeries{}
	for rows.Next() {
		var i PodcastSeries
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPodcastSeries = `-- name: ListPodcastSeries :many
SELECT id, name, slug, sort_order, created_at, updated_at, is_active FROM podcast_series
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListPodcastSeries(ctx context.Context) ([]PodcastSeries, error) {
	rows, err := q.db.QueryContext(ctx, listPodcastSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PodcastSeries{}
	for rows.Next() {
		var i PodcastSeries
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePodcastSeries = `-- name: UpdatePodcastSeries :exec
UPDATE podcast_series SET name = ?, slug = ?, sort_order = ?, is_active = ? WHERE id = ?
`

type UpdatePodcastSeriesParams struct {
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	SortOrder int32  `json:"sort_order"`
	IsActive  bool   `json:"is_active"`
	ID        uint64 `json:"id"`
}

func (q *Queries) UpdatePodcastSeries(ctx context.Context, arg UpdatePodcastSeriesParams) error {
	_, err := q.db.ExecContext(ctx, updatePodcastSeries,
		arg.Name,
		arg.Slug,
		arg.SortOrder,
		arg.IsActive,
		arg.ID,
	)
	return err
}
