// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: programs.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const addProgramBroadcaster = `-- name: AddProgramBroadcaster :exec
INSERT INTO program_broadcasters (program_id, broadcaster_id) VALUES (?, ?)
`

type AddProgramBroadcasterParams struct {
	ProgramID     uint64 `json:"program_id"`
	BroadcasterID uint64 `json:"broadcaster_id"`
}

func (q *Queries) AddProgramBroadcaster(ctx context.Context, arg AddProgramBroadcasterParams) error {
	_, err := q.db.ExecContext(ctx, addProgramBroadcaster, arg.ProgramID, arg.BroadcasterID)
	return err
}

const addScheduleBroadcaster = `-- name: AddScheduleBroadcaster :exec
INSERT INTO schedule_broadcasters (schedule_id, broadcaster_id) VALUES (?, ?)
`

type AddScheduleBroadcasterParams struct {
	ScheduleID    uint64 `json:"schedule_id"`
	BroadcasterID uint64 `json:"broadcaster_id"`
}

func (q *Queries) AddScheduleBroadcaster(ctx context.Context, arg AddScheduleBroadcasterParams) error {
	_, err := q.db.ExecContext(ctx, addScheduleBroadcaster, arg.ScheduleID, arg.BroadcasterID)
	return err
}

const clearProgramBroadcasters = `-- name: ClearProgramBroadcasters :exec
DELETE FROM program_broadcasters WHERE program_id = ?
`

func (q *Queries) ClearProgramBroadcasters(ctx context.Context, programID uint64) error {
	_, err := q.db.ExecContext(ctx, clearProgramBroadcasters, programID)
	return err
}

const clearScheduleBroadcasters = `-- name: ClearScheduleBroadcasters :exec
DELETE FROM schedule_broadcasters WHERE schedule_id = ?
`

func (q *Queries) ClearScheduleBroadcasters(ctx context.Context, scheduleID uint64) error {
	_, err := q.db.ExecContext(ctx, clearScheduleBroadcasters, scheduleID)
	return err
}

const countPrograms = `-- name: CountPrograms :one
SELECT COUNT(*) FROM programs
WHERE title LIKE ? OR slug LIKE ?
`

type CountProgramsParams struct {
	Search string `json:"search"`
}

func (q *Queries) CountPrograms(ctx context.Context, arg CountProgramsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrograms, arg.Search, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProgram = `-- name: CreateProgram :execresult
INSERT INTO programs (title, slug, description, image_url, sort_order, is_active)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateProgramParams struct {
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	SortOrder   int32          `json:"sort_order"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProgram,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ImageUrl,
		arg.SortOrder,
		arg.IsActive,
	)
}

const createSchedule = `-- name: CreateSchedule :execresult

INSERT INTO program_schedules (program_id, day_of_week, start_time, end_time)
VALUES (?, ?, ?, ?)
`

type CreateScheduleParams struct {
	ProgramID uint64 `json:"program_id"`
	DayOfWeek int8   `json:"day_of_week"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
}

// CreateSchedule is :execresult rather than :exec because the caller needs the new
// slot's id to write its schedule_broadcasters rows.
func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSchedule,
		arg.ProgramID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
}

const deleteProgram = `-- name: DeleteProgram :exec
DELETE FROM programs WHERE id = ?
`

func (q *Queries) DeleteProgram(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteProgram, id)
	return err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM program_schedules WHERE id = ? AND program_id = ?
`

type DeleteScheduleParams struct {
	ID        uint64 `json:"id"`
	ProgramID uint64 `json:"program_id"`
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, arg.ID, arg.ProgramID)
	return err
}

const deleteSchedulesForProgram = `-- name: DeleteSchedulesForProgram :exec
DELETE FROM program_schedules WHERE program_id = ?
`

func (q *Queries) DeleteSchedulesForProgram(ctx context.Context, programID uint64) error {
	_, err := q.db.ExecContext(ctx, deleteSchedulesForProgram, programID)
	return err
}

const getProgram = `-- name: GetProgram :one
SELECT id, title, slug, description, image_url, sort_order, is_active, created_at, updated_at FROM programs WHERE id = ?
`

func (q *Queries) GetProgram(ctx context.Context, id uint64) (Program, error) {
	row := q.db.QueryRowContext(ctx, getProgram, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProgramBySlug = `-- name: GetProgramBySlug :one
SELECT id, title, slug, description, image_url, sort_order, is_active, created_at, updated_at FROM programs WHERE slug = ?
`

func (q *Queries) GetProgramBySlug(ctx context.Context, slug string) (Program, error) {
	row := q.db.QueryRowContext(ctx, getProgramBySlug, slug)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePrograms = `-- name: ListActivePrograms :many
SELECT id, title, slug, description, image_url, sort_order, is_active, created_at, updated_at FROM programs
WHERE is_active = 1
ORDER BY sort_order ASC, title ASC
`

func (q *Queries) ListActivePrograms(ctx context.Context) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listActivePrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPrograms = `-- name: ListAllPrograms :many
SELECT id, title, slug, description, image_url, sort_order, is_active, created_at, updated_at FROM programs
ORDER BY sort_order ASC, title ASC
`

func (q *Queries) ListAllPrograms(ctx context.Context) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listAllPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSchedulesWithProgram = `-- name: ListAllSchedulesWithProgram :many
SELECT
  s.id, s.program_id, s.day_of_week, s.start_time, s.end_time,
  (SELECT GROUP_CONCAT(b.name ORDER BY b.sort_order, b.name SEPARATOR ', ')
     FROM broadcasters b
    WHERE b.id IN (
      SELECT sb.broadcaster_id FROM schedule_broadcasters sb WHERE sb.schedule_id = s.id
      UNION
      SELECT pb.broadcaster_id FROM program_broadcasters pb
       WHERE pb.program_id = p.id
         AND NOT EXISTS (SELECT 1 FROM schedule_broadcasters x WHERE x.schedule_id = s.id)
    )) AS broadcaster_name,
  p.title AS program_title, p.slug AS program_slug,
  p.image_url AS program_image_url
FROM program_schedules s
JOIN programs p ON p.id = s.program_id
WHERE p.is_active = 1
ORDER BY s.day_of_week ASC, s.start_time ASC
`

type ListAllSchedulesWithProgramRow struct {
	ID              uint64         `json:"id"`
	ProgramID       uint64         `json:"program_id"`
	DayOfWeek       int8           `json:"day_of_week"`
	StartTime       string         `json:"start_time"`
	EndTime         string         `json:"end_time"`
	BroadcasterName sql.NullString `json:"broadcaster_name"`
	ProgramTitle    string         `json:"program_title"`
	ProgramSlug     string         `json:"program_slug"`
	ProgramImageUrl sql.NullString `json:"program_image_url"`
}

func (q *Queries) ListAllSchedulesWithProgram(ctx context.Context) ([]ListAllSchedulesWithProgramRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllSchedulesWithProgram)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSchedulesWithProgramRow{}
	for rows.Next() {
		var i ListAllSchedulesWithProgramRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.BroadcasterName,
			&i.ProgramTitle,
			&i.ProgramSlug,
			&i.ProgramImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramBroadcasters = `-- name: ListProgramBroadcasters :many

SELECT b.id, b.name, b.slug, b.role, b.photo_url, b.bio, b.birth_place, b.birth_date, b.instagram, b.twitter, b.sort_order, b.is_active, b.created_at, b.updated_at, b.tiktok FROM program_broadcasters pb
JOIN broadcasters b ON b.id = pb.broadcaster_id
WHERE pb.program_id = ?
ORDER BY b.sort_order ASC, b.name ASC
`

// Broadcaster assignments. Both sets are written clear-then-insert, so there is no
// update query; the junction rows go away with their parent via ON DELETE CASCADE.
func (q *Queries) ListProgramBroadcasters(ctx context.Context, programID uint64) ([]Broadcaster, error) {
	rows, err := q.db.QueryContext(ctx, listProgramBroadcasters, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Broadcaster{}
	for rows.Next() {
		var i Broadcaster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.PhotoUrl,
			&i.Bio,
			&i.BirthPlace,
			&i.BirthDate,
			&i.Instagram,
			&i.Twitter,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tiktok,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrograms = `-- name: ListPrograms :many

SELECT p.id, p.title, p.slug, p.description, p.image_url, p.sort_order, p.is_active, p.created_at, p.updated_at,
  (SELECT GROUP_CONCAT(b.name ORDER BY b.sort_order, b.name SEPARATOR ', ')
     FROM broadcasters b
     JOIN program_broadcasters pb ON pb.broadcaster_id = b.id
    WHERE pb.program_id = p.id) AS broadcaster_name
FROM programs p
WHERE p.title LIKE ? OR p.slug LIKE ?
ORDER BY
  CASE WHEN ? = 'title' AND ? = 'asc' THEN p.title END ASC,
  CASE WHEN ? = 'title' AND ? = 'desc' THEN p.title END DESC,
  CASE WHEN ? = 'slug' AND ? = 'asc' THEN p.slug END ASC,
  CASE WHEN ? = 'slug' AND ? = 'desc' THEN p.slug END DESC,
  CASE WHEN ? = 'sort_order' AND ? = 'asc' THEN p.sort_order END ASC,
  CASE WHEN ? = 'sort_order' AND ? = 'desc' THEN p.sort_order END DESC,
  p.sort_order ASC, p.title ASC, p.id ASC
LIMIT ? OFFSET ?
`

type ListProgramsParams struct {
	Search string      `json:"search"`
	Sort   interface{} `json:"sort"`
	Dir    interface{} `json:"dir"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListProgramsRow struct {
	ID              uint64         `json:"id"`
	Title           string         `json:"title"`
	Slug            string         `json:"slug"`
	Description     sql.NullString `json:"description"`
	ImageUrl        sql.NullString `json:"image_url"`
	SortOrder       int32          `json:"sort_order"`
	IsActive        bool           `json:"is_active"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	BroadcasterName sql.NullString `json:"broadcaster_name"`
}

// broadcaster_name here is the program's *default* set (program_broadcasters) only, not
// the effective per-slot set the schedule queries below expose under the same name: the
// admin list has no slot to resolve against, and this column mirrors the Broadcasters
// multiselect on the edit form. Same single-scalar-subquery constraint applies - see the
// comment above ListSchedulesForProgram.
func (q *Queries) ListPrograms(ctx context.Context, arg ListProgramsParams) ([]ListProgramsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPrograms,
		arg.Search,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramsRow{}
	for rows.Next() {
		var i ListProgramsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BroadcasterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleBroadcasterIDsForProgram = `-- name: ListScheduleBroadcasterIDsForProgram :many

SELECT sb.schedule_id, sb.broadcaster_id
FROM schedule_broadcasters sb
JOIN program_schedules s ON s.id = sb.schedule_id
JOIN broadcasters b ON b.id = sb.broadcaster_id
WHERE s.program_id = ?
ORDER BY b.sort_order ASC, b.name ASC
`

// ListScheduleBroadcasterIDsForProgram returns every slot assignment of one program in
// a single round trip, so the edit form can mark each slot's <select multiple> without
// a query per row.
func (q *Queries) ListScheduleBroadcasterIDsForProgram(ctx context.Context, programID uint64) ([]ScheduleBroadcaster, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleBroadcasterIDsForProgram, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleBroadcaster{}
	for rows.Next() {
		var i ScheduleBroadcaster
		if err := rows.Scan(&i.ScheduleID, &i.BroadcasterID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByDay = `-- name: ListSchedulesByDay :many
SELECT
  s.id, s.program_id, s.day_of_week, s.start_time, s.end_time,
  (SELECT GROUP_CONCAT(b.name ORDER BY b.sort_order, b.name SEPARATOR ', ')
     FROM broadcasters b
    WHERE b.id IN (
      SELECT sb.broadcaster_id FROM schedule_broadcasters sb WHERE sb.schedule_id = s.id
      UNION
      SELECT pb.broadcaster_id FROM program_broadcasters pb
       WHERE pb.program_id = p.id
         AND NOT EXISTS (SELECT 1 FROM schedule_broadcasters x WHERE x.schedule_id = s.id)
    )) AS broadcaster_name,
  p.title AS program_title, p.slug AS program_slug,
  p.image_url AS program_image_url
FROM program_schedules s
JOIN programs p ON p.id = s.program_id
WHERE s.day_of_week = ? AND p.is_active = 1
ORDER BY s.start_time ASC
`

type ListSchedulesByDayRow struct {
	ID              uint64         `json:"id"`
	ProgramID       uint64         `json:"program_id"`
	DayOfWeek       int8           `json:"day_of_week"`
	StartTime       string         `json:"start_time"`
	EndTime         string         `json:"end_time"`
	BroadcasterName sql.NullString `json:"broadcaster_name"`
	ProgramTitle    string         `json:"program_title"`
	ProgramSlug     string         `json:"program_slug"`
	ProgramImageUrl sql.NullString `json:"program_image_url"`
}

func (q *Queries) ListSchedulesByDay(ctx context.Context, dayOfWeek int8) ([]ListSchedulesByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulesByDay, dayOfWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulesByDayRow{}
	for rows.Next() {
		var i ListSchedulesByDayRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.BroadcasterName,
			&i.ProgramTitle,
			&i.ProgramSlug,
			&i.ProgramImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesForProgram = `-- name: ListSchedulesForProgram :many

SELECT s.id, s.program_id, s.day_of_week, s.start_time, s.end_time,
  (SELECT GROUP_CONCAT(b.name ORDER BY b.sort_order, b.name SEPARATOR ', ')
     FROM broadcasters b
    WHERE b.id IN (
      SELECT sb.broadcaster_id FROM schedule_broadcasters sb WHERE sb.schedule_id = s.id
      UNION
      SELECT pb.broadcaster_id FROM program_broadcasters pb
       WHERE pb.program_id = p.id
         AND NOT EXISTS (SELECT 1 FROM schedule_broadcasters x WHERE x.schedule_id = s.id)
    )) AS broadcaster_name,
  EXISTS (SELECT 1 FROM schedule_broadcasters sb WHERE sb.schedule_id = s.id) AS has_own_broadcasters
FROM program_schedules s
JOIN programs p ON p.id = s.program_id
WHERE s.program_id = ?
ORDER BY s.day_of_week ASC, s.start_time ASC
`

type ListSchedulesForProgramRow struct {
	ID                 uint64         `json:"id"`
	ProgramID          uint64         `json:"program_id"`
	DayOfWeek          int8           `json:"day_of_week"`
	StartTime          string         `json:"start_time"`
	EndTime            string         `json:"end_time"`
	BroadcasterName    sql.NullString `json:"broadcaster_name"`
	HasOwnBroadcasters bool           `json:"has_own_broadcasters"`
}

// broadcaster_name below is the *effective* broadcaster line for a slot, joined as
// "Anda, Yeni": the slot's own set (schedule_broadcasters) if it has one, otherwise the
// program's whole default set (program_broadcasters). The NOT EXISTS guard on the second
// half of the UNION is that set-level override. Every consumer treats this as one
// display string, so the join happens here rather than in Go.
//
// It has to be one scalar subquery rather than the more obvious COALESCE of two: sqlc
// types a lone GROUP_CONCAT subquery as sql.NullString, but wrapping it in COALESCE
// defeats its inference and the field lands as interface{}.
//
// has_own_broadcasters lets admin views tell an inherited line from an explicitly
// assigned one; it replaced the old scalar s.broadcaster_id.
func (q *Queries) ListSchedulesForProgram(ctx context.Context, programID uint64) ([]ListSchedulesForProgramRow, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulesForProgram, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulesForProgramRow{}
	for rows.Next() {
		var i ListSchedulesForProgramRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.BroadcasterName,
			&i.HasOwnBroadcasters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProgram = `-- name: UpdateProgram :exec
UPDATE programs
SET title = ?, slug = ?, description = ?, image_url = ?, sort_order = ?, is_active = ?
WHERE id = ?
`

type UpdateProgramParams struct {
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	SortOrder   int32          `json:"sort_order"`
	IsActive    bool           `json:"is_active"`
	ID          uint64         `json:"id"`
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) error {
	_, err := q.db.ExecContext(ctx, updateProgram,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ImageUrl,
		arg.SortOrder,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updateSchedule = `-- name: UpdateSchedule :exec
UPDATE program_schedules
SET day_of_week = ?, start_time = ?, end_time = ?
WHERE id = ? AND program_id = ?
`

type UpdateScheduleParams struct {
	DayOfWeek int8   `json:"day_of_week"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
	ID        uint64 `json:"id"`
	ProgramID uint64 `json:"program_id"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error {
	_, err := q.db.ExecContext(ctx, updateSchedule,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.ID,
		arg.ProgramID,
	)
	return err
}
