// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: programs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createProgram = `-- name: CreateProgram :execresult
INSERT INTO programs (title, slug, description, host, image_url, sort_order, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateProgramParams struct {
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	Host        sql.NullString `json:"host"`
	ImageUrl    sql.NullString `json:"image_url"`
	SortOrder   int32          `json:"sort_order"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProgram,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Host,
		arg.ImageUrl,
		arg.SortOrder,
		arg.IsActive,
	)
}

const createSchedule = `-- name: CreateSchedule :exec
INSERT INTO program_schedules (program_id, day_of_week, start_time, end_time, host)
VALUES (?, ?, ?, ?, ?)
`

type CreateScheduleParams struct {
	ProgramID uint64         `json:"program_id"`
	DayOfWeek int8           `json:"day_of_week"`
	StartTime string         `json:"start_time"`
	EndTime   string         `json:"end_time"`
	Host      sql.NullString `json:"host"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) error {
	_, err := q.db.ExecContext(ctx, createSchedule,
		arg.ProgramID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.Host,
	)
	return err
}

const deleteProgram = `-- name: DeleteProgram :exec
DELETE FROM programs WHERE id = ?
`

func (q *Queries) DeleteProgram(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteProgram, id)
	return err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM program_schedules WHERE id = ? AND program_id = ?
`

type DeleteScheduleParams struct {
	ID        uint64 `json:"id"`
	ProgramID uint64 `json:"program_id"`
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, arg.ID, arg.ProgramID)
	return err
}

const deleteSchedulesForProgram = `-- name: DeleteSchedulesForProgram :exec
DELETE FROM program_schedules WHERE program_id = ?
`

func (q *Queries) DeleteSchedulesForProgram(ctx context.Context, programID uint64) error {
	_, err := q.db.ExecContext(ctx, deleteSchedulesForProgram, programID)
	return err
}

const getProgram = `-- name: GetProgram :one
SELECT id, title, slug, description, host, image_url, sort_order, is_active, created_at, updated_at FROM programs WHERE id = ?
`

func (q *Queries) GetProgram(ctx context.Context, id uint64) (Program, error) {
	row := q.db.QueryRowContext(ctx, getProgram, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Host,
		&i.ImageUrl,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProgramBySlug = `-- name: GetProgramBySlug :one
SELECT id, title, slug, description, host, image_url, sort_order, is_active, created_at, updated_at FROM programs WHERE slug = ?
`

func (q *Queries) GetProgramBySlug(ctx context.Context, slug string) (Program, error) {
	row := q.db.QueryRowContext(ctx, getProgramBySlug, slug)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Host,
		&i.ImageUrl,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePrograms = `-- name: ListActivePrograms :many
SELECT id, title, slug, description, host, image_url, sort_order, is_active, created_at, updated_at FROM programs
WHERE is_active = 1
ORDER BY sort_order ASC, title ASC
`

func (q *Queries) ListActivePrograms(ctx context.Context) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listActivePrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Host,
			&i.ImageUrl,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSchedulesWithProgram = `-- name: ListAllSchedulesWithProgram :many
SELECT
  s.id, s.program_id, s.day_of_week, s.start_time, s.end_time, s.host AS slot_host,
  p.title AS program_title, p.slug AS program_slug, p.host AS program_host
FROM program_schedules s
JOIN programs p ON p.id = s.program_id
WHERE p.is_active = 1
ORDER BY s.day_of_week ASC, s.start_time ASC
`

type ListAllSchedulesWithProgramRow struct {
	ID           uint64         `json:"id"`
	ProgramID    uint64         `json:"program_id"`
	DayOfWeek    int8           `json:"day_of_week"`
	StartTime    string         `json:"start_time"`
	EndTime      string         `json:"end_time"`
	SlotHost     sql.NullString `json:"slot_host"`
	ProgramTitle string         `json:"program_title"`
	ProgramSlug  string         `json:"program_slug"`
	ProgramHost  sql.NullString `json:"program_host"`
}

func (q *Queries) ListAllSchedulesWithProgram(ctx context.Context) ([]ListAllSchedulesWithProgramRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllSchedulesWithProgram)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSchedulesWithProgramRow{}
	for rows.Next() {
		var i ListAllSchedulesWithProgramRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.SlotHost,
			&i.ProgramTitle,
			&i.ProgramSlug,
			&i.ProgramHost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrograms = `-- name: ListPrograms :many
SELECT id, title, slug, description, host, image_url, sort_order, is_active, created_at, updated_at FROM programs
ORDER BY sort_order ASC, title ASC
`

func (q *Queries) ListPrograms(ctx context.Context) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Host,
			&i.ImageUrl,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByDay = `-- name: ListSchedulesByDay :many
SELECT
  s.id, s.program_id, s.day_of_week, s.start_time, s.end_time, s.host AS slot_host,
  p.title AS program_title, p.slug AS program_slug, p.host AS program_host,
  p.image_url AS program_image_url
FROM program_schedules s
JOIN programs p ON p.id = s.program_id
WHERE s.day_of_week = ? AND p.is_active = 1
ORDER BY s.start_time ASC
`

type ListSchedulesByDayRow struct {
	ID              uint64         `json:"id"`
	ProgramID       uint64         `json:"program_id"`
	DayOfWeek       int8           `json:"day_of_week"`
	StartTime       string         `json:"start_time"`
	EndTime         string         `json:"end_time"`
	SlotHost        sql.NullString `json:"slot_host"`
	ProgramTitle    string         `json:"program_title"`
	ProgramSlug     string         `json:"program_slug"`
	ProgramHost     sql.NullString `json:"program_host"`
	ProgramImageUrl sql.NullString `json:"program_image_url"`
}

func (q *Queries) ListSchedulesByDay(ctx context.Context, dayOfWeek int8) ([]ListSchedulesByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulesByDay, dayOfWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulesByDayRow{}
	for rows.Next() {
		var i ListSchedulesByDayRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.SlotHost,
			&i.ProgramTitle,
			&i.ProgramSlug,
			&i.ProgramHost,
			&i.ProgramImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesForProgram = `-- name: ListSchedulesForProgram :many
SELECT id, program_id, day_of_week, start_time, end_time, host FROM program_schedules
WHERE program_id = ?
ORDER BY day_of_week ASC, start_time ASC
`

func (q *Queries) ListSchedulesForProgram(ctx context.Context, programID uint64) ([]ProgramSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulesForProgram, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgramSchedule{}
	for rows.Next() {
		var i ProgramSchedule
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.Host,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProgram = `-- name: UpdateProgram :exec
UPDATE programs
SET title = ?, slug = ?, description = ?, host = ?, image_url = ?, sort_order = ?, is_active = ?
WHERE id = ?
`

type UpdateProgramParams struct {
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	Host        sql.NullString `json:"host"`
	ImageUrl    sql.NullString `json:"image_url"`
	SortOrder   int32          `json:"sort_order"`
	IsActive    bool           `json:"is_active"`
	ID          uint64         `json:"id"`
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) error {
	_, err := q.db.ExecContext(ctx, updateProgram,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Host,
		arg.ImageUrl,
		arg.SortOrder,
		arg.IsActive,
		arg.ID,
	)
	return err
}
