// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: programs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countPrograms = `-- name: CountPrograms :one
SELECT COUNT(*) FROM programs
WHERE title LIKE ? OR slug LIKE ?
`

type CountProgramsParams struct {
	Search string `json:"search"`
}

func (q *Queries) CountPrograms(ctx context.Context, arg CountProgramsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrograms, arg.Search, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProgram = `-- name: CreateProgram :execresult
INSERT INTO programs (title, slug, description, image_url, broadcaster_id, sort_order, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateProgramParams struct {
	Title         string         `json:"title"`
	Slug          string         `json:"slug"`
	Description   sql.NullString `json:"description"`
	ImageUrl      sql.NullString `json:"image_url"`
	BroadcasterID sql.NullInt64  `json:"broadcaster_id"`
	SortOrder     int32          `json:"sort_order"`
	IsActive      bool           `json:"is_active"`
}

func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProgram,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ImageUrl,
		arg.BroadcasterID,
		arg.SortOrder,
		arg.IsActive,
	)
}

const createSchedule = `-- name: CreateSchedule :exec
INSERT INTO program_schedules (program_id, day_of_week, start_time, end_time, broadcaster_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateScheduleParams struct {
	ProgramID     uint64        `json:"program_id"`
	DayOfWeek     int8          `json:"day_of_week"`
	StartTime     string        `json:"start_time"`
	EndTime       string        `json:"end_time"`
	BroadcasterID sql.NullInt64 `json:"broadcaster_id"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) error {
	_, err := q.db.ExecContext(ctx, createSchedule,
		arg.ProgramID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.BroadcasterID,
	)
	return err
}

const deleteProgram = `-- name: DeleteProgram :exec
DELETE FROM programs WHERE id = ?
`

func (q *Queries) DeleteProgram(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteProgram, id)
	return err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM program_schedules WHERE id = ? AND program_id = ?
`

type DeleteScheduleParams struct {
	ID        uint64 `json:"id"`
	ProgramID uint64 `json:"program_id"`
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, arg.ID, arg.ProgramID)
	return err
}

const deleteSchedulesForProgram = `-- name: DeleteSchedulesForProgram :exec
DELETE FROM program_schedules WHERE program_id = ?
`

func (q *Queries) DeleteSchedulesForProgram(ctx context.Context, programID uint64) error {
	_, err := q.db.ExecContext(ctx, deleteSchedulesForProgram, programID)
	return err
}

const getProgram = `-- name: GetProgram :one
SELECT id, title, slug, description, image_url, sort_order, is_active, created_at, updated_at, broadcaster_id FROM programs WHERE id = ?
`

func (q *Queries) GetProgram(ctx context.Context, id uint64) (Program, error) {
	row := q.db.QueryRowContext(ctx, getProgram, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BroadcasterID,
	)
	return i, err
}

const getProgramBySlug = `-- name: GetProgramBySlug :one
SELECT id, title, slug, description, image_url, sort_order, is_active, created_at, updated_at, broadcaster_id FROM programs WHERE slug = ?
`

func (q *Queries) GetProgramBySlug(ctx context.Context, slug string) (Program, error) {
	row := q.db.QueryRowContext(ctx, getProgramBySlug, slug)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BroadcasterID,
	)
	return i, err
}

const listActivePrograms = `-- name: ListActivePrograms :many
SELECT id, title, slug, description, image_url, sort_order, is_active, created_at, updated_at, broadcaster_id FROM programs
WHERE is_active = 1
ORDER BY sort_order ASC, title ASC
`

func (q *Queries) ListActivePrograms(ctx context.Context) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listActivePrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BroadcasterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPrograms = `-- name: ListAllPrograms :many
SELECT id, title, slug, description, image_url, sort_order, is_active, created_at, updated_at, broadcaster_id FROM programs
ORDER BY sort_order ASC, title ASC
`

func (q *Queries) ListAllPrograms(ctx context.Context) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listAllPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BroadcasterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSchedulesWithProgram = `-- name: ListAllSchedulesWithProgram :many
SELECT
  s.id, s.program_id, s.day_of_week, s.start_time, s.end_time, s.broadcaster_id,
  b.name AS broadcaster_name,
  p.title AS program_title, p.slug AS program_slug,
  p.image_url AS program_image_url
FROM program_schedules s
JOIN programs p ON p.id = s.program_id
LEFT JOIN broadcasters b ON b.id = COALESCE(s.broadcaster_id, p.broadcaster_id)
WHERE p.is_active = 1
ORDER BY s.day_of_week ASC, s.start_time ASC
`

type ListAllSchedulesWithProgramRow struct {
	ID              uint64         `json:"id"`
	ProgramID       uint64         `json:"program_id"`
	DayOfWeek       int8           `json:"day_of_week"`
	StartTime       string         `json:"start_time"`
	EndTime         string         `json:"end_time"`
	BroadcasterID   sql.NullInt64  `json:"broadcaster_id"`
	BroadcasterName sql.NullString `json:"broadcaster_name"`
	ProgramTitle    string         `json:"program_title"`
	ProgramSlug     string         `json:"program_slug"`
	ProgramImageUrl sql.NullString `json:"program_image_url"`
}

func (q *Queries) ListAllSchedulesWithProgram(ctx context.Context) ([]ListAllSchedulesWithProgramRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllSchedulesWithProgram)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSchedulesWithProgramRow{}
	for rows.Next() {
		var i ListAllSchedulesWithProgramRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.BroadcasterID,
			&i.BroadcasterName,
			&i.ProgramTitle,
			&i.ProgramSlug,
			&i.ProgramImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrograms = `-- name: ListPrograms :many
SELECT id, title, slug, description, image_url, sort_order, is_active, created_at, updated_at, broadcaster_id FROM programs
WHERE title LIKE ? OR slug LIKE ?
ORDER BY
  CASE WHEN ? = 'title' AND ? = 'asc' THEN title END ASC,
  CASE WHEN ? = 'title' AND ? = 'desc' THEN title END DESC,
  CASE WHEN ? = 'slug' AND ? = 'asc' THEN slug END ASC,
  CASE WHEN ? = 'slug' AND ? = 'desc' THEN slug END DESC,
  CASE WHEN ? = 'sort_order' AND ? = 'asc' THEN sort_order END ASC,
  CASE WHEN ? = 'sort_order' AND ? = 'desc' THEN sort_order END DESC,
  sort_order ASC, title ASC, id ASC
LIMIT ? OFFSET ?
`

type ListProgramsParams struct {
	Search string      `json:"search"`
	Sort   interface{} `json:"sort"`
	Dir    interface{} `json:"dir"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListPrograms(ctx context.Context, arg ListProgramsParams) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listPrograms,
		arg.Search,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Sort,
		arg.Dir,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BroadcasterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByDay = `-- name: ListSchedulesByDay :many
SELECT
  s.id, s.program_id, s.day_of_week, s.start_time, s.end_time, s.broadcaster_id,
  b.name AS broadcaster_name,
  p.title AS program_title, p.slug AS program_slug,
  p.image_url AS program_image_url
FROM program_schedules s
JOIN programs p ON p.id = s.program_id
LEFT JOIN broadcasters b ON b.id = COALESCE(s.broadcaster_id, p.broadcaster_id)
WHERE s.day_of_week = ? AND p.is_active = 1
ORDER BY s.start_time ASC
`

type ListSchedulesByDayRow struct {
	ID              uint64         `json:"id"`
	ProgramID       uint64         `json:"program_id"`
	DayOfWeek       int8           `json:"day_of_week"`
	StartTime       string         `json:"start_time"`
	EndTime         string         `json:"end_time"`
	BroadcasterID   sql.NullInt64  `json:"broadcaster_id"`
	BroadcasterName sql.NullString `json:"broadcaster_name"`
	ProgramTitle    string         `json:"program_title"`
	ProgramSlug     string         `json:"program_slug"`
	ProgramImageUrl sql.NullString `json:"program_image_url"`
}

func (q *Queries) ListSchedulesByDay(ctx context.Context, dayOfWeek int8) ([]ListSchedulesByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulesByDay, dayOfWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulesByDayRow{}
	for rows.Next() {
		var i ListSchedulesByDayRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.BroadcasterID,
			&i.BroadcasterName,
			&i.ProgramTitle,
			&i.ProgramSlug,
			&i.ProgramImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesForProgram = `-- name: ListSchedulesForProgram :many

SELECT s.id, s.program_id, s.day_of_week, s.start_time, s.end_time, s.broadcaster_id, b.name AS broadcaster_name
FROM program_schedules s
JOIN programs p ON p.id = s.program_id
LEFT JOIN broadcasters b ON b.id = COALESCE(s.broadcaster_id, p.broadcaster_id)
WHERE s.program_id = ?
ORDER BY s.day_of_week ASC, s.start_time ASC
`

type ListSchedulesForProgramRow struct {
	ID              uint64         `json:"id"`
	ProgramID       uint64         `json:"program_id"`
	DayOfWeek       int8           `json:"day_of_week"`
	StartTime       string         `json:"start_time"`
	EndTime         string         `json:"end_time"`
	BroadcasterID   sql.NullInt64  `json:"broadcaster_id"`
	BroadcasterName sql.NullString `json:"broadcaster_name"`
}

// broadcaster_name below is the *effective* broadcaster: the slot's own if set,
// otherwise the program's default (programs.broadcaster_id). The selected
// s.broadcaster_id stays the slot's own value so admin views can tell an
// inherited broadcaster from an explicitly assigned one.
func (q *Queries) ListSchedulesForProgram(ctx context.Context, programID uint64) ([]ListSchedulesForProgramRow, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulesForProgram, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulesForProgramRow{}
	for rows.Next() {
		var i ListSchedulesForProgramRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.BroadcasterID,
			&i.BroadcasterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProgram = `-- name: UpdateProgram :exec
UPDATE programs
SET title = ?, slug = ?, description = ?, image_url = ?, broadcaster_id = ?, sort_order = ?, is_active = ?
WHERE id = ?
`

type UpdateProgramParams struct {
	Title         string         `json:"title"`
	Slug          string         `json:"slug"`
	Description   sql.NullString `json:"description"`
	ImageUrl      sql.NullString `json:"image_url"`
	BroadcasterID sql.NullInt64  `json:"broadcaster_id"`
	SortOrder     int32          `json:"sort_order"`
	IsActive      bool           `json:"is_active"`
	ID            uint64         `json:"id"`
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) error {
	_, err := q.db.ExecContext(ctx, updateProgram,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ImageUrl,
		arg.BroadcasterID,
		arg.SortOrder,
		arg.IsActive,
		arg.ID,
	)
	return err
}
