// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountAggregatedNews(ctx context.Context, arg CountAggregatedNewsParams) (int64, error)
	CountAllHotRelease(ctx context.Context, search string) (int64, error)
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CountClassiers(ctx context.Context, arg CountClassiersParams) (int64, error)
	CountPrograms(ctx context.Context, arg CountProgramsParams) (int64, error)
	CountPublishedNews(ctx context.Context) (int64, error)
	CountPublishedNewsBySource(ctx context.Context, source NewsItemsSource) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateClassier(ctx context.Context, arg CreateClassierParams) (sql.Result, error)
	CreateHotRelease(ctx context.Context, arg CreateHotReleaseParams) (sql.Result, error)
	// Same as CreateHotRelease but also records the source article's URL on the old
	// site (classyfm.co.id), used by cmd/importhotrelease to dedupe on re-runs.
	CreateHotReleaseImported(ctx context.Context, arg CreateHotReleaseImportedParams) (sql.Result, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error
	CreateProgram(ctx context.Context, arg CreateProgramParams) (sql.Result, error)
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteClassier(ctx context.Context, id uint64) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteNewsItem(ctx context.Context, id uint64) error
	DeleteProgram(ctx context.Context, id uint64) error
	DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error
	DeleteSchedulesForProgram(ctx context.Context, programID uint64) error
	DeleteSession(ctx context.Context, token string) error
	DeleteSessionsByUserID(ctx context.Context, userID uint64) error
	DeleteUser(ctx context.Context, id uint64) error
	GetActiveClassierBySlug(ctx context.Context, slug string) (Classier, error)
	GetClassier(ctx context.Context, id uint64) (Classier, error)
	GetFeedSource(ctx context.Context, source FeedSourcesSource) (FeedSource, error)
	GetNewsItem(ctx context.Context, id uint64) (NewsItem, error)
	GetProgram(ctx context.Context, id uint64) (Program, error)
	GetProgramBySlug(ctx context.Context, slug string) (Program, error)
	GetPublishedNewsItemBySlug(ctx context.Context, slug sql.NullString) (NewsItem, error)
	GetSession(ctx context.Context, token string) (GetSessionRow, error)
	GetSetting(ctx context.Context, k string) (Setting, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uint64) (User, error)
	GetValidPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	ListActiveClassiers(ctx context.Context) ([]Classier, error)
	ListActivePrograms(ctx context.Context) ([]Program, error)
	ListAggregatedNews(ctx context.Context, arg ListAggregatedNewsParams) ([]NewsItem, error)
	ListAllHotRelease(ctx context.Context, arg ListAllHotReleaseParams) ([]NewsItem, error)
	ListAllSchedulesWithProgram(ctx context.Context) ([]ListAllSchedulesWithProgramRow, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListClassiers(ctx context.Context, arg ListClassiersParams) ([]Classier, error)
	ListFeedSources(ctx context.Context) ([]FeedSource, error)
	ListHotRelease(ctx context.Context, limit int32) ([]NewsItem, error)
	ListLatestPublished(ctx context.Context, limit int32) ([]NewsItem, error)
	ListMediaLinks(ctx context.Context) ([]MediaLink, error)
	ListPrograms(ctx context.Context, arg ListProgramsParams) ([]Program, error)
	ListPublishedNews(ctx context.Context, arg ListPublishedNewsParams) ([]NewsItem, error)
	ListPublishedNewsBySource(ctx context.Context, arg ListPublishedNewsBySourceParams) ([]NewsItem, error)
	ListSchedulesByDay(ctx context.Context, dayOfWeek int8) ([]ListSchedulesByDayRow, error)
	ListSchedulesForProgram(ctx context.Context, programID uint64) ([]ProgramSchedule, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkPasswordResetTokenUsed(ctx context.Context, tokenHash string) error
	SetNewsItemFeatured(ctx context.Context, arg SetNewsItemFeaturedParams) error
	SetNewsItemPublished(ctx context.Context, arg SetNewsItemPublishedParams) error
	UpdateClassier(ctx context.Context, arg UpdateClassierParams) error
	UpdateFeedSourceConfig(ctx context.Context, arg UpdateFeedSourceConfigParams) error
	UpdateFeedSourceStatus(ctx context.Context, arg UpdateFeedSourceStatusParams) error
	UpdateHotRelease(ctx context.Context, arg UpdateHotReleaseParams) error
	UpdateMediaLinkURL(ctx context.Context, arg UpdateMediaLinkURLParams) error
	UpdateProgram(ctx context.Context, arg UpdateProgramParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Inserts a new aggregated item as published, or refreshes content fields on an
	// existing one. is_published/is_featured are intentionally left untouched on
	// conflict so an admin's publish/feature decision survives the next fetch.
	UpsertNewsItem(ctx context.Context, arg UpsertNewsItemParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
