// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AddPodcastBroadcaster(ctx context.Context, arg AddPodcastBroadcasterParams) error
	AddProgramBroadcaster(ctx context.Context, arg AddProgramBroadcasterParams) error
	AddScheduleBroadcaster(ctx context.Context, arg AddScheduleBroadcasterParams) error
	ClearPodcastBroadcasters(ctx context.Context, podcastID uint64) error
	ClearProgramBroadcasters(ctx context.Context, programID uint64) error
	ClearScheduleBroadcasters(ctx context.Context, scheduleID uint64) error
	CountAggregatedNews(ctx context.Context, arg CountAggregatedNewsParams) (int64, error)
	CountAllHotRelease(ctx context.Context, search string) (int64, error)
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CountBroadcasters(ctx context.Context, arg CountBroadcastersParams) (int64, error)
	CountHeroSlides(ctx context.Context, arg CountHeroSlidesParams) (int64, error)
	CountPodcasts(ctx context.Context, search string) (int64, error)
	CountPrograms(ctx context.Context, arg CountProgramsParams) (int64, error)
	CountPublishedNews(ctx context.Context) (int64, error)
	CountPublishedNewsBySource(ctx context.Context, source NewsItemsSource) (int64, error)
	CountPublishedPodcasts(ctx context.Context) (int64, error)
	CountPublishedPodcastsBySeriesSlug(ctx context.Context, slug string) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateAdBanner(ctx context.Context, arg CreateAdBannerParams) (sql.Result, error)
	CreateAdBannerPage(ctx context.Context, arg CreateAdBannerPageParams) error
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateBroadcaster(ctx context.Context, arg CreateBroadcasterParams) (sql.Result, error)
	CreateHeroSlide(ctx context.Context, arg CreateHeroSlideParams) (sql.Result, error)
	CreateHotRelease(ctx context.Context, arg CreateHotReleaseParams) (sql.Result, error)
	// Same as CreateHotRelease but also records the source article's URL on the old
	// site (classyfm.co.id), used by cmd/importhotrelease to dedupe on re-runs.
	CreateHotReleaseImported(ctx context.Context, arg CreateHotReleaseImportedParams) (sql.Result, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error
	CreatePodcast(ctx context.Context, arg CreatePodcastParams) (sql.Result, error)
	CreatePodcastSeries(ctx context.Context, arg CreatePodcastSeriesParams) (sql.Result, error)
	CreateProgram(ctx context.Context, arg CreateProgramParams) (sql.Result, error)
	// CreateSchedule is :execresult rather than :exec because the caller needs the new
	// slot's id to write its schedule_broadcasters rows.
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (sql.Result, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteAdBanner(ctx context.Context, id uint64) error
	DeleteAdBannerPages(ctx context.Context, bannerID uint64) error
	DeleteBroadcaster(ctx context.Context, id uint64) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteHeroSlide(ctx context.Context, id uint64) error
	DeleteNewsItem(ctx context.Context, id uint64) error
	DeletePodcast(ctx context.Context, id uint64) error
	DeletePodcastSeries(ctx context.Context, id uint64) error
	DeleteProgram(ctx context.Context, id uint64) error
	DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error
	DeleteSchedulesForProgram(ctx context.Context, programID uint64) error
	DeleteSession(ctx context.Context, token string) error
	DeleteSessionsByUserID(ctx context.Context, userID uint64) error
	DeleteUser(ctx context.Context, id uint64) error
	GetAboutBanner(ctx context.Context) (AboutPageBanner, error)
	GetActiveBroadcasterBySlug(ctx context.Context, slug string) (Broadcaster, error)
	GetAdBanner(ctx context.Context, id uint64) (AdBanner, error)
	GetAdBannerPages(ctx context.Context, bannerID uint64) ([]AdBannerPagesPage, error)
	GetBroadcaster(ctx context.Context, id uint64) (Broadcaster, error)
	GetFeedSource(ctx context.Context, source FeedSourcesSource) (FeedSource, error)
	// Home page hero slideshow. The public side reads exactly two of these
	// (settings + active slides) and mixes the result with the latest news; see
	// internal/handlers/public/hero.go. The rest serve /admin/hero.
	GetHeroSettings(ctx context.Context) (HeroSetting, error)
	GetHeroSlide(ctx context.Context, id uint64) (HeroSlide, error)
	GetListenerDay(ctx context.Context, statDate time.Time) (ListenerStat, error)
	GetNewsItem(ctx context.Context, id uint64) (NewsItem, error)
	// Used by the feed worker to check what's already stored before overwriting
	// image_url/thumb_url on a refresh, so a transient resolution failure can't
	// downgrade an already-upgraded image (see feeds.PreferImage).
	GetNewsItemImages(ctx context.Context, arg GetNewsItemImagesParams) (GetNewsItemImagesRow, error)
	GetPodcast(ctx context.Context, id uint64) (Podcast, error)
	GetPodcastBySlug(ctx context.Context, slug string) (Podcast, error)
	GetPodcastSeries(ctx context.Context, id uint64) (PodcastSeries, error)
	GetPodcastSeriesBySlug(ctx context.Context, slug string) (PodcastSeries, error)
	GetProgram(ctx context.Context, id uint64) (Program, error)
	GetProgramBySlug(ctx context.Context, slug string) (Program, error)
	GetPublishedNewsItemBySlug(ctx context.Context, slug sql.NullString) (NewsItem, error)
	GetPublishedPodcastBySlug(ctx context.Context, slug string) (Podcast, error)
	GetSession(ctx context.Context, token string) (GetSessionRow, error)
	GetSetting(ctx context.Context, k string) (Setting, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uint64) (User, error)
	GetValidPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	// Listener history: written by internal/listeners.Sampler, read by the admin
	// dashboard's listener chart (internal/handlers/admin/dashboard_charts.go).
	// See migration 0028 for why the daily rollup and the raw trail are separate.
	InsertListenerSample(ctx context.Context, arg InsertListenerSampleParams) error
	ListAboutSegments(ctx context.Context) ([]AboutPageSegment, error)
	ListActiveAdBannersForPage(ctx context.Context, page AdBannerPagesPage) ([]AdBanner, error)
	ListActiveBroadcasters(ctx context.Context) ([]Broadcaster, error)
	// The admin form requires an image, but the image_url <> '' guard keeps a
	// hand-edited or otherwise blank row from reaching the template, where it would
	// emit <img src=""> - which browsers resolve against the page URL and actually
	// fetch.
	ListActiveHeroSlides(ctx context.Context, limit int32) ([]HeroSlide, error)
	ListActivePrograms(ctx context.Context) ([]Program, error)
	ListAdBannerPages(ctx context.Context) ([]AdBannerPage, error)
	ListAdBanners(ctx context.Context) ([]AdBanner, error)
	ListAdSlots(ctx context.Context) ([]AdSlot, error)
	ListAggregatedNews(ctx context.Context, arg ListAggregatedNewsParams) ([]NewsItem, error)
	ListAllBroadcasters(ctx context.Context) ([]Broadcaster, error)
	ListAllHotRelease(ctx context.Context, arg ListAllHotReleaseParams) ([]NewsItem, error)
	ListAllPrograms(ctx context.Context) ([]Program, error)
	ListAllSchedulesWithProgram(ctx context.Context) ([]ListAllSchedulesWithProgramRow, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	// ListBroadcasterProgramLinks, by contrast, must stay exactly effective-per-slot: it
	// feeds the "on air now" badge, which needs a real time slot to measure against. Hence
	// the UNION - slot assignments, plus the program's defaults for the slots that have no
	// assignment of their own.
	ListBroadcasterProgramLinks(ctx context.Context) ([]ListBroadcasterProgramLinksRow, error)
	ListBroadcasters(ctx context.Context, arg ListBroadcastersParams) ([]Broadcaster, error)
	ListBroadcastersForProgram(ctx context.Context, arg ListBroadcastersForProgramParams) ([]Broadcaster, error)
	ListFeedSources(ctx context.Context) ([]FeedSource, error)
	ListHeroSlides(ctx context.Context, arg ListHeroSlidesParams) ([]HeroSlide, error)
	ListHotRelease(ctx context.Context, limit int32) ([]NewsItem, error)
	ListLatestPublished(ctx context.Context, limit int32) ([]NewsItem, error)
	// Backs the dashboard chart's intraday groupings. Bounded by the caller's window
	// (24h at most, so ~288 rows at the default sampling interval) and covered end to
	// end by idx_listener_samples_sampled_at.
	ListListenerSamples(ctx context.Context, sampledAt time.Time) ([]ListenerSample, error)
	ListListenerStats(ctx context.Context, statDate time.Time) ([]ListenerStat, error)
	ListMediaLinks(ctx context.Context) ([]MediaLink, error)
	// Broadcaster assignments are written clear-then-insert, so there is no update query;
	// the junction rows go away with their parent via ON DELETE CASCADE.
	ListPodcastBroadcasters(ctx context.Context, podcastID uint64) ([]Broadcaster, error)
	ListPodcastSeries(ctx context.Context) ([]PodcastSeries, error)
	ListPodcasts(ctx context.Context, arg ListPodcastsParams) ([]ListPodcastsRow, error)
	// Broadcaster assignments. Both sets are written clear-then-insert, so there is no
	// update query; the junction rows go away with their parent via ON DELETE CASCADE.
	ListProgramBroadcasters(ctx context.Context, programID uint64) ([]Broadcaster, error)
	// broadcaster_name here is the program's *default* set (program_broadcasters) only, not
	// the effective per-slot set the schedule queries below expose under the same name: the
	// admin list has no slot to resolve against, and this column mirrors the Broadcasters
	// multiselect on the edit form. Same single-scalar-subquery constraint applies - see the
	// comment above ListSchedulesForProgram.
	ListPrograms(ctx context.Context, arg ListProgramsParams) ([]ListProgramsRow, error)
	// The two queries below answer "who presents this program" / "what does this broadcaster
	// present" for chip lists, and deliberately take the loose reading: a program's default
	// broadcaster counts even if every slot happens to override them. They are display
	// lists, and someone assigned to the program is one of its broadcasters regardless of
	// which slots they actually cover.
	ListProgramsForBroadcaster(ctx context.Context, arg ListProgramsForBroadcasterParams) ([]Program, error)
	ListPublishedNews(ctx context.Context, arg ListPublishedNewsParams) ([]NewsItem, error)
	ListPublishedNewsBySource(ctx context.Context, arg ListPublishedNewsBySourceParams) ([]NewsItem, error)
	// broadcaster_name is the podcast's broadcaster set joined as "Anda, Yeni". Every
	// consumer treats it as one display string, so the join happens here. It has to be a
	// single scalar GROUP_CONCAT subquery, not a COALESCE of two: sqlc types a lone
	// GROUP_CONCAT subquery as sql.NullString, but wrapping it in COALESCE defeats its
	// inference and the field lands as interface{}. See the same note in programs.sql.
	ListPublishedPodcasts(ctx context.Context, arg ListPublishedPodcastsParams) ([]ListPublishedPodcastsRow, error)
	ListPublishedPodcastsBySeriesSlug(ctx context.Context, arg ListPublishedPodcastsBySeriesSlugParams) ([]ListPublishedPodcastsBySeriesSlugRow, error)
	// Raw arrival timestamps for the dashboard's ingest chart, bucketed into days by the
	// caller. Deliberately not a GROUP BY DATE(created_at): that buckets by whatever
	// timezone the MySQL session runs in - the host's - while the chart has to read in the
	// station's (Asia/Jakarta). Grouping in Go against schedule.Loc is correct by
	// construction, and two weeks of two columns is a few hundred rows.
	// hot_release is excluded because those rows arrive in one historical import (a
	// thousand-plus on a single day), which would flatten every real day to nothing.
	ListRecentNewsArrivals(ctx context.Context, since time.Time) ([]ListRecentNewsArrivalsRow, error)
	// ListScheduleBroadcasterIDsForProgram returns every slot assignment of one program in
	// a single round trip, so the edit form can mark each slot's <select multiple> without
	// a query per row.
	ListScheduleBroadcasterIDsForProgram(ctx context.Context, programID uint64) ([]ScheduleBroadcaster, error)
	ListSchedulesByDay(ctx context.Context, dayOfWeek int8) ([]ListSchedulesByDayRow, error)
	// broadcaster_name below is the *effective* broadcaster line for a slot, joined as
	// "Anda, Yeni": the slot's own set (schedule_broadcasters) if it has one, otherwise the
	// program's whole default set (program_broadcasters). The NOT EXISTS guard on the second
	// half of the UNION is that set-level override. Every consumer treats this as one
	// display string, so the join happens here rather than in Go.
	//
	// It has to be one scalar subquery rather than the more obvious COALESCE of two: sqlc
	// types a lone GROUP_CONCAT subquery as sql.NullString, but wrapping it in COALESCE
	// defeats its inference and the field lands as interface{}.
	//
	// has_own_broadcasters lets admin views tell an inherited line from an explicitly
	// assigned one; it replaced the old scalar s.broadcaster_id.
	ListSchedulesForProgram(ctx context.Context, programID uint64) ([]ListSchedulesForProgramRow, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkPasswordResetTokenUsed(ctx context.Context, tokenHash string) error
	// One row per news source for the admin dashboard: how many items exist, how many
	// are published (the rest are the newsfeed review queue), how many arrived since
	// `since`, and when the newest published one was dated. latest_published_at is the
	// real staleness signal - feed_sources.last_fetched_at only says the worker ran,
	// not that anything new came back.
	//
	// Every CAST here is load-bearing, same family of trap as the scalar subqueries in
	// programs.sql: a bare SUM() is DECIMAL and a bare MAX() of a DATETIME is untyped as
	// far as sqlc is concerned, and both come back as interface{} instead of a number /
	// time.Time. CAST(... AS SIGNED) and CAST(... AS DATETIME) pin them down. The
	// DATETIME cast can't produce a NULL that breaks the time.Time scan: published_at is
	// NOT NULL and GROUP BY never yields an empty group.
	NewsStatsBySource(ctx context.Context, since time.Time) ([]NewsStatsBySourceRow, error)
	PruneListenerSamples(ctx context.Context, sampledAt time.Time) error
	SetNewsItemFeatured(ctx context.Context, arg SetNewsItemFeaturedParams) error
	SetNewsItemPublished(ctx context.Context, arg SetNewsItemPublishedParams) error
	// SetPodcastCreatedAt lets the legacy importer (cmd/importpodcasts) preserve each
	// episode's original publish date, so the catalog's created_at DESC ordering reflects
	// real chronology instead of the single moment of import.
	SetPodcastCreatedAt(ctx context.Context, arg SetPodcastCreatedAtParams) error
	// SetPodcastDescription updates only the description, leaving every other column
	// untouched. Used by cmd/backfillpodcastdescriptions to fill descriptions for podcasts
	// imported before the Spotify auto-fetch existed, without disturbing their other fields.
	SetPodcastDescription(ctx context.Context, arg SetPodcastDescriptionParams) error
	SetPodcastPublished(ctx context.Context, arg SetPodcastPublishedParams) error
	UpdateAboutBanner(ctx context.Context, arg UpdateAboutBannerParams) error
	UpdateAboutSegment(ctx context.Context, arg UpdateAboutSegmentParams) error
	UpdateAdBanner(ctx context.Context, arg UpdateAdBannerParams) error
	UpdateAdSlot(ctx context.Context, arg UpdateAdSlotParams) error
	UpdateBroadcaster(ctx context.Context, arg UpdateBroadcasterParams) error
	UpdateFeedSourceConfig(ctx context.Context, arg UpdateFeedSourceConfigParams) error
	UpdateFeedSourceStatus(ctx context.Context, arg UpdateFeedSourceStatusParams) error
	UpdateHeroSettings(ctx context.Context, arg UpdateHeroSettingsParams) error
	UpdateHeroSlide(ctx context.Context, arg UpdateHeroSlideParams) error
	UpdateHotRelease(ctx context.Context, arg UpdateHotReleaseParams) error
	UpdateMediaLinkURL(ctx context.Context, arg UpdateMediaLinkURLParams) error
	// Used by one-off backfill tools (e.g. cmd/upgradeimages) to swap in a
	// higher-resolution image (and/or its list-sized thumbnail) for an
	// already-aggregated item without touching anything else about the row.
	UpdateNewsItemImages(ctx context.Context, arg UpdateNewsItemImagesParams) error
	UpdatePodcast(ctx context.Context, arg UpdatePodcastParams) error
	UpdatePodcastSeries(ctx context.Context, arg UpdatePodcastSeriesParams) error
	UpdateProgram(ctx context.Context, arg UpdateProgramParams) error
	UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Folds one sample into its day's row, monotonic in peak_listeners so a quiet
	// afternoon can never lower the morning's peak.
	//
	// peak_at is assigned before peak_listeners on purpose: MySQL evaluates the SET
	// list left to right, so the comparison has to run while peak_listeners still
	// holds the old value.
	UpsertListenerDay(ctx context.Context, arg UpsertListenerDayParams) error
	// Inserts a new aggregated item as published, or refreshes content fields on an
	// existing one. is_published/is_featured are intentionally left untouched on
	// conflict so an admin's publish/feature decision survives the next fetch.
	UpsertNewsItem(ctx context.Context, arg UpsertNewsItemParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
