// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seo_settings.sql

package sqlc

import (
	"context"
)

const getSeoSettings = `-- name: GetSeoSettings :one
SELECT id, keywords, updated_at, default_description, og_image_url FROM seo_settings WHERE id = 1
`

func (q *Queries) GetSeoSettings(ctx context.Context) (SeoSetting, error) {
	row := q.db.QueryRowContext(ctx, getSeoSettings)
	var i SeoSetting
	err := row.Scan(
		&i.ID,
		&i.Keywords,
		&i.UpdatedAt,
		&i.DefaultDescription,
		&i.OgImageUrl,
	)
	return i, err
}

const updateSeoSettings = `-- name: UpdateSeoSettings :exec
UPDATE seo_settings
SET keywords = ?, default_description = ?, og_image_url = ?
WHERE id = 1
`

type UpdateSeoSettingsParams struct {
	Keywords           string `json:"keywords"`
	DefaultDescription string `json:"default_description"`
	OgImageUrl         string `json:"og_image_url"`
}

func (q *Queries) UpdateSeoSettings(ctx context.Context, arg UpdateSeoSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSeoSettings, arg.Keywords, arg.DefaultDescription, arg.OgImageUrl)
	return err
}
