// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seo_settings.sql

package sqlc

import (
	"context"
)

const getSeoSettings = `-- name: GetSeoSettings :one
SELECT id, keywords, updated_at, default_description, og_image_url, google_verification, bing_verification FROM seo_settings WHERE id = 1
`

func (q *Queries) GetSeoSettings(ctx context.Context) (SeoSetting, error) {
	row := q.db.QueryRowContext(ctx, getSeoSettings)
	var i SeoSetting
	err := row.Scan(
		&i.ID,
		&i.Keywords,
		&i.UpdatedAt,
		&i.DefaultDescription,
		&i.OgImageUrl,
		&i.GoogleVerification,
		&i.BingVerification,
	)
	return i, err
}

const updateSeoSettings = `-- name: UpdateSeoSettings :exec
UPDATE seo_settings
SET keywords = ?, default_description = ?, og_image_url = ?, google_verification = ?, bing_verification = ?
WHERE id = 1
`

type UpdateSeoSettingsParams struct {
	Keywords           string `json:"keywords"`
	DefaultDescription string `json:"default_description"`
	OgImageUrl         string `json:"og_image_url"`
	GoogleVerification string `json:"google_verification"`
	BingVerification   string `json:"bing_verification"`
}

func (q *Queries) UpdateSeoSettings(ctx context.Context, arg UpdateSeoSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSeoSettings,
		arg.Keywords,
		arg.DefaultDescription,
		arg.OgImageUrl,
		arg.GoogleVerification,
		arg.BingVerification,
	)
	return err
}
