// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlc

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT k, v FROM settings WHERE k = ?
`

func (q *Queries) GetSetting(ctx context.Context, k string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, k)
	var i Setting
	err := row.Scan(&i.K, &i.V)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT k, v FROM settings ORDER BY k
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.K, &i.V); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (k, v) VALUES (?, ?)
ON DUPLICATE KEY UPDATE v = VALUES(v)
`

type UpsertSettingParams struct {
	K string `json:"k"`
	V string `json:"v"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.K, arg.V)
	return err
}
