INSERT INTO classiers (name, slug, role, photo_url, bio, birth_place, birth_date, instagram, twitter, facebook, sort_order) VALUES
('Andahayani', 'andahayani', 'Classier',
 '/static/img/classiers/andahayani.jpg',
 'It''s Not About How Life is Treating You but You Are Treating Life. Suka public speaking, broadcasting, dan menjelajahi tempat baru.',
 'Jambi', '17 Oktober', 'anda_joseph', 'anda_joseph', 'Andahayani Yoseph', 1),
('Dara Rinjani', 'dara-rinjani', 'Reporter',
 '/static/img/classiers/dara-rinjani.jpg',
 'Berbuat Baik dan Mandiri. Suka traveling, jurnalistik, dan pencinta kucing.',
 'Riau', '11 Januari', NULL, NULL, 'Zulia Yandani', 2),
('Dhanny Yudiska', 'dhanny-yudiska', 'Classier',
 '/static/img/classiers/dhanny-yudiska.png',
 'Im a grown man... I do whatever i want! Suka musik, film, broadcasting, dan hal-hal yang membawa kebahagiaan.',
 'Maninjau', '18 Agustus', 'dhannyyudiska', 'dhannyyudiska', 'dhanny''arif''yudiska', 3),
('Edo Prussiano', 'edo-prussiano', 'Classier',
 '/static/img/classiers/edo-prussiano.jpg',
 'Kalo mau kaya, ya harus capek! Suka healing.',
 'Padang', '28 Juni', 'edo_pruss17', 'edo_pruss17', NULL, 4),
('Jasmine Andrea', 'jasmine-andrea', 'Classier',
 '/static/img/classiers/jasmine-andrea.jpg',
 'Live is Art. Suka membaca, menulis, musik, film, dan seni.',
 'Batusangkar', '06 September', 'Jasmine Andrea', 'jasmineandrea06', NULL, 5),
('Puti Adelya', 'puti-adelya', 'Classier',
 NULL,
 'It''s just a bad day, not a bad life. Suka buku, film, seni, dan proyek sosial.',
 'Padang', '31 Mei', 'karzmp', NULL, NULL, 6),
('Via Helvita', 'via-helvita', 'Classier',
 '/static/img/classiers/via-helvita.png',
 'Hidup Gak Neko Neko. Suka traveling.',
 'Jakarta', '30 Oktober', 'vivi_chressya', 'vivi_chressya', 'Vivi d'' Chressya', 7),
('Yeni Maiasnita', 'yeni-maiasnita', 'Classier',
 '/static/img/classiers/yeni-maiasnita.png',
 'Always Do The Best And Enjoy Your Life. Suka film, broadcasting, human interest, dan psikologi. Membawakan "Communitalk with Yeni Maiasnita".',
 'Sawahlunto', '28 Mei', 'aunty.cantik', 'auntycantiq', 'aunty cantik', 8);
